### ISSUE TITLE
Control+Enter shortcut only runs the code if there's nothing written in the code box

### ISSUE THREAD

**Issue by Th-eo** [GDQuest/learn-gdscript#100]
**Describe the bug**
When testing the "show()" lesson, possibly other lessons too, Control+Enter is meant to be the shortcut to run the code (the tooltip over Run says so), but unless there's just one empty line of code, it won't run.

**To Reproduce**
Steps to reproduce the bug:
1. Go to the "show()" lesson called "Make the Character Visible"
2. Type the code to run
3. Press Control+Enter (image 1)
4. Code isn't ran, and instead it just adds a new line (image 2)

**Expected behavior**

**Screenshots**
![imagen](https://user-images.githubusercontent.com/42318572/148094431-51ceebb0-1eda-4d03-a6ed-ca21a73719e6.png)
![imagen](https://user-images.githubusercontent.com/42318572/148094454-edeb51db-41c3-4053-a3c9-4934bc801671.png)

**Information about your device (please complete the following information):**
 - Win11, Firefox

**Comment by NathanLovato** [comment]
The text edit must be swallowing the input, I'll fix it, thanks.
