### ISSUE TITLE
Keyboard on mobile

### ISSUE THREAD

**Issue by dusk2340** [GDQuest/learn-gdscript#1012]
**Describe the bug**
The keyboard on mobile won't appear for me

**To Reproduce**
Steps to reproduce the bug:
1. Open practice.
2. select text field.
3.  keyboard doesn't appear. 

**Expected behavior**
 the keyboard should come up to edit the text field. 

**Screenshots**
![Screenshot_20241025_105913_Chrome](https://github.com/user-attachments/assets/ba1751a5-cc2b-4248-b8c0-e4546489ae38)

**Information about your device (please complete the following information):**
 - Operating System: [android version 14, one ui version 6.1]
 - Browser: [Chrome on android]

**Additional context**
I only have my phone available at this time and i was hoping this would work.

**Comment by NathanLovato** [comment]
You might have gotten a warning when first launching the app indicating it doesn't support mobile fully. This is not a bug per se; the app just does not support on-screen keyboards and this cannot be added easily. See https://github.com/GDQuest/learn-gdscript/issues/847 for more information
