### ISSUE TITLE
Add mention that you can select multiple options in multiple choice quizzes

### ISSUE THREAD

**Issue by v01t3ch** [GDQuest/learn-gdscript#103]
**Describe the bug**
In the end of Lesson 3, when I choose first or second question doesnt matter, it won't submit as a right answer, the whole block blinks red.

**To Reproduce**
Steps to reproduce the bug:
1. Go to Lesson 3
2. Click on either answer of the final question What does the code below do?
3. Click on Submit

**Expected behavior**
It should accept the first answer as a correct one and let me continue with the course

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/10830442/148115983-ef5a7f52-e0b6-40a0-9cef-680f255101b5.png)
![obrazek](https://user-images.githubusercontent.com/10830442/148116021-3d9e2bde-eead-4249-9cdf-f8677905cab0.png)

**Information about your device (please complete the following information):**
 - Windows 11 64bit Czech, updated
 - Firefox, updated to latest update

**Additional context**

**Comment by duianto** [comment]
Both choices need to be checked.

But it's not clear, since the previous questions only accepted one choice,
clicking on one unchecked the other.

This is the first question that accepts both.

Maybe a hint could say: "Almost correct"
When only one is chosen.

**Comment by NathanLovato** [comment]
Yes, it's that you need to check both answers. We can add a hint to this first multiple-choice quiz.

**Comment by NathanLovato** [comment]
I'm not sure how to make it clear UX-wise. Here, the issue is you didn't see or think you could select multiple answers at once, right? To you, toggleable checkboxes don't suggest you can select multiple at once?

**Comment by v01t3ch** [comment]
Hi Nathan, It was realy weird, because both answers were correct, right :). But I thought, as I'm in a gamedev course, it was asking for precise technical answer - which is calling a function. So no I understand multiple options can be correct.

**Comment by Mark-Karnowski** [comment]
Standardized test questions in the US usually have 4 options wth one correct response. If there are multiple correct answers, there will often be an indication of this in the stem of the test item, for example:

**What does the code below do? (_select all that apply_)**

Not sure that the presence of toggleable check boxes vs. radio buttons is enough of an indicator for all students...

**Comment by Xananax** [comment]
It is indeed good UX practice to always specify if one or multiple answers are possible/desired, even when the UI itself makes it clear. It's standard in questionnaires and tests.

**Comment by NathanLovato** [comment]
That's a good way to do it, we'll add an explicit mention.
