### ISSUE TITLE
Improve the highlight of the selected choice

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#106]
**Is your feature request related to a problem? Please describe.**

The choices at the bottom of the lesson:
4. Drawing a Rectangle
https://gdquest.github.io/learn-gdscript/#course/lesson-4-drawing-a-rectangle/lesson.tres

Doesn't make it obvious which choice is selected.

The unselected choices are shown with a filled in circle to the left.
This might be seen as if all choices are selected.

![nothing selected](https://user-images.githubusercontent.com/13420573/148132654-5bfde7a3-471b-4a04-aa36-0bcda639041b.png)

The selected choice gets an unfilled circle to the left and the text becomes bold.
The bold text is slightly brighter than the unselected choices.

But the unselected choices still have the filled in circle.
Which might be seen as if they are selected.

![pixels selected, current behavior](https://user-images.githubusercontent.com/13420573/148132925-c880e6ce-e34c-497e-8306-73f46a3ab381.png)

**Describe the solution you'd like**

Some possible solutions might be to:
- Show unselected choices with the unfilled circle,
and the selected choice with a filled circle.
This makes it stand out more.

![pixels selected, highlighted dot](https://user-images.githubusercontent.com/13420573/148133038-a5f2a7ec-bb36-4cc2-ab47-fe9c1a5d0f41.png)

- Or if only the selected choice had a filled circle,
and the unselected didn't have a circle at all.
Then it would be more obvious which choice is selected.

![pixels selected, only dot](https://user-images.githubusercontent.com/13420573/148133136-74ca2b79-2949-4be6-aec9-31e209b5efd9.png)

- It would be helpful if the background color of the selected choice was different from the unselected choices.

**Comment by pycbouh** [comment]
Previously there were no icons there for the buttons in single-answer quizzes, so bold was standing out more. If the change to use the radios wasn't accidental, we just need to make theme-appropriate icons for our theme.

Nathan also experimented with color there a bit, but we deemed it was too much. Can revisit it in some form too though.

**Comment by NathanLovato** [comment]
That's weird, the disappearing radio elements or multiple circles filles is definitely a bug. Yes, the use of radio buttons was intentional - I thought people would be used to them from web forms.

For example, from Google forms, which work similarly:

- square boxes are for forms accepting multiple answers
- circles are for forms accepting only one of multiple options

We should theme those and see what works best. If it's clear without the icon, we can just remove it.

**Comment by NathanLovato** [comment]
@duianto when you first saw this quiz, did you think "all answers are selected" ? Did you personally have trouble selecting options and completing the quiz?

**Comment by NathanLovato** [comment]
Does this look clearer?

![image](https://user-images.githubusercontent.com/12694995/148159414-d79460a6-87b5-4de2-936d-f64409bb0ab8.png)

**Comment by duianto** [comment]
>when you first saw this quiz, did you think "all answers are selected" ?

No, I thought that the filled circles just were decorations.
But when one choice was selected, then it's circle became unfilled,
and the text became bold (slightly brighter).

This made it look like the circles and the bold text said opposite things.
Unfilled circle = unselected
Bold text = selected

>Did you personally have trouble selecting options and completing the quiz?

No, I assumed that the choice I clicked on would be checked as expected.

I just thought that it could be made clear which choice one had selected.
For example if one made a choice, and had to step away.
Then it wouldn't be obvious which choice was selected.

>Does this look clearer?

Yes, that makes it clear which choice is selected.
