### ISSUE TITLE
Lesson 6: awkard phrasing in multiple-choice answer

### ISSUE THREAD

**Issue by Teschnique** [GDQuest/learn-gdscript#107]
In Lesson 6 "Your First Function Parameter" the choices are:

- **A label you give to a value function the function receives.**
- The name of a function
- A number you use to make calculations

The first choice does not read well.  It should be "**A label you give to a value the function receives**" since you aren't given a label to a "value function".

![image](https://user-images.githubusercontent.com/519151/148152356-c0397122-2298-48d7-811d-7ca998d791de.png)

**Comment by NathanLovato** [comment]
It's a typo, I'll fix it now, thanks
