### ISSUE TITLE
Lesson 6 practice "Drawing rectangles of any size" solution has an extra turn_right(90)

### ISSUE THREAD

**Issue by Poonaka** [GDQuest/learn-gdscript#108]
After entering the solution, the rectangles are drawn correctly. However the output produces the following error:

"ERROR The drawn shapes don't have the expected length and height. Did you forget to use the length and height parameter?"

<img width="1744" alt="Screen Shot 2022-01-04 at 9 56 40 PM" src="https://user-images.githubusercontent.com/5330520/148153897-550a5131-f6e4-4d12-a06a-d43d213157da.png">

Clicking the show solution button shows that an extra turn_right(90) is needed at the end of the draw_rectangle function, when it shouldn't be needed.

**Comment by NathanLovato** [comment]
The solution is correct considering how the turtle works.

It's something we planned to address with #5. You do need to turn the turtle a fourth time to make it look back to its start direction - otherwise, your function turns it 270 degrees in total and turns every other rectangle (hence the error, the second rectangle doesn't have the expected height).

**Comment by Poonaka** [comment]
That makes sense now but you may need to include a different error message as I think that could trip others up. The drawn rectangles in my screenshot have the correct length and height, although the second one isn't numbered right due to the missing turn_right(90).

**Comment by NathanLovato** [comment]
The second rectangle doesn't have the expected length and height, as I mentioned. It should be vertical (so length and height should be swapped compared to what you have)

Like this:

![image](https://user-images.githubusercontent.com/12694995/151089624-2679b7c7-a8a2-4ab9-a214-72252ebd60d4.png)

Hopefully, making the turtle turn should make things clearer.

**Comment by sogaiu** [comment]
> That makes sense now but you may need to include a different error message as I think that could trip others up. The drawn rectangles in my screenshot have the correct length and height, although the second one isn't numbered right due to the missing turn_right(90).

I was indeed tripped up by the message.

Is it true that the length and height are incorrect without the last turn instruction?  It doesn't seem so to me.

**Comment by NathanLovato** [comment]
Because web apps are sandboxes, unfortunately, you can't copy and paste outside the app (except in Chrome in some cases, it'll ask for permission). See #34's discussion for more information.
