### ISSUE TITLE
Double scrollbars, difficult to scroll the inner section

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#115]
**Describe the bug**
It's difficult to scroll the text in the Goals section.
If the hints have been opened, so that the whole left panel,
gets its own scrollbar.

**To Reproduce**
Steps to reproduce the bug:
1. Go to the lesson:
`6. Your First Function Parameter/Drawing corners of different sizes/Using multiple parameters/Drawing squares of any size`
https://gdquest.github.io/learn-gdscript/#course/lesson-6-multiple-function-parameters/practice-v5tT6n1T.tres
(note: loading this url directly shows the outer scrollbar without opening any hints, more info below)
2. Open all four hints
3. Move the mouse pointer over the text in the Goals section.
4. Turn the mouse wheel.
5. Now both the Goals text and the whole left panel scrolls.

**Expected behavior**
Only scroll the section with the mouse pointer.
- On the Goals section
- Outside the Goals section

**Screenshots**

https://user-images.githubusercontent.com/13420573/148236913-a4ff0e38-a656-400b-9020-1ccee36b4151.mp4

**Information about your device (please complete the following information):**
Operating System: Windows 10 21H1
Browser: Microsoft Edge 96.0.1054.62 (Official build) (64-bit)

**Additional context**
On a 1920x1080 resolution display.
It's enough to open one hint, to show the outer scrollbar.

But opening all four hints is more likely to show the outer scrollbar on a taller display.

**Workaround**
It works to drag the inner scrollbar.
Or to close the hints before turning the mouse wheel over the Goals section.

But it would probably be better if only the section, with the mouse pointer, scrolled.

**Continued from step 1**
Loading the url directly:
https://gdquest.github.io/learn-gdscript/#course/lesson-6-multiple-function-parameters/practice-v5tT6n1T.tres

Shows the outer scrollbar without having to open any hints.
It has a small scrollbar "handle". Meaning that it's a long page.

Scrolling down shows that most of the page is empty.

https://user-images.githubusercontent.com/13420573/148238362-9adec4a5-a17d-473e-bbd4-c7d701357166.mp4

**Comment by NathanLovato** [comment]
Note for the team: we need to have the frontmost scroll container consume the mouse wheel input, probably using _gui_input().
