### ISSUE TITLE
Typo: missing space "app,we"

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#117]
https://github.com/GDQuest/learn-gdscript/blob/64fb16ebf22406825099ae90c8c59d06b89bad9f/course/lesson-8-defining-variables/content-lkGx0c7D.tres#L9

Missing space after the comma: `app,we`

**Comment by NathanLovato** [comment]
Thanks much for reporting those. Note that when you spot a typo like this, you can directly correct it from the file on GitHub. You should be able to edit the file by clicking the pencil icon in the top-right, when viewing the file in question on GitHub.

![image](https://user-images.githubusercontent.com/12694995/148282239-13b5fe25-411e-44d6-88cd-d5e5d34b5f3f.png)

**Comment by NathanLovato** [comment]
Fixed by fde15064d3ce0157a6cc82436492cb01527c576c
