### ISSUE TITLE
GDQuestBoy

### ISSUE THREAD

**Issue by Mark-Karnowski** [GDQuest/learn-gdscript#124]
The code result box is labeled "GDQuestBoy". Unclear meaning. Suggest something more generic like "Code Results".

**Comment by pycbouh** [comment]
It's not supposed to label the area in any practical way. It's just additional flair, an imitation of a screen and a body of a handheld videogame console to better embed the game that the students are making into the UI of the application.

**Comment by Mark-Karnowski** [comment]
Oh, of course! I missed the humor. I never owned a GameBoy...

**Comment by NathanLovato** [comment]
I'll have Kay look at the output's design and maybe do something more appealing visually and maybe use some bevel or something on the text to make it look more like a fantasy console. Closing for now, but taking note of this.
