### ISSUE TITLE
Unsupported webgl driver version, the app runs slowly

### ISSUE THREAD

**Issue by Chllea** [GDQuest/learn-gdscript#129]
**Describe the bug**
My computer is decent at least it is better than my mobile so when i ran the app using my computer it say that my drivers does not support any of the supported webGl versions i tried to update chrome but nothing changed but when i go back to an older version of my driver it can run the app but its soo slow and it become soo hot on the other side my mobile don't have any problem running it even if its doesn't optimizied for mobiles. 

**To Reproduce**
Steps to reproduce the bug:
1. You just need to enter the app. 
**Expected behavior**
I expected it to work :) 
**Screenshots**
I don't have

**Information about your device (please complete the following information):**
 - Operating System: windows 10 
 - Browser chrome

**Additional context**
My labtob have 4 gb ram and intel basic graphics card when its opening the app but slow when i update it it doesn't work at all
While my mobile is huawei y 6 2019
I hope you find a solution

**Comment by NathanLovato** [comment]
You need to give us more information. Which computer? What's your hardware? Which web browser? Did you try with other web browsers?

Please fill the issue's body when reporting issues. Otherwise, we can't take your report into account.

**Comment by Chllea** [comment]
Ok i will report a new issue with the full details

**Comment by pycbouh** [comment]
You don't need to open a new issue when probed for additional details, just reply here.

**Comment by NathanLovato** [comment]
I just copied over the details you wrote in a separate issue. Note you can edit anytime.

What happens is your graphics card has an old driver and doesn't support the technology this app uses. It runs smoothly on your phone because your phone has more recent hardware, with a more recent driver that supports the technology.

We could consider downgrading the project to OpenGL ES 2 instead of 3.

@pycbouh @Xananax what do you think? I think this could be fine?

**Comment by Xananax** [comment]
We don't use any specific shaders or anything that could stand in the way of a downgrade. I'm in favor

**Comment by pycbouh** [comment]
It may result in reduced performance, but I guess it's not important here. Device support is definitely greater (if the reports on the Godot repo are to be believed from the time WebGL 1 support was implemented).

**Comment by NathanLovato** [comment]
Let's use GL ES 2 then. I just tested it and couldn't find any issue. Can I let another one of you try it as well? If it works for you, please push the change and close the issue.

**Comment by Chllea** [comment]
Do you mean xananax and pycbouh or me?

**Comment by NathanLovato** [comment]
Sorry, I meant my teammates, @Xananax @pycbouh.

**Comment by Xananax** [comment]
I tested, I see nothing to report either
