### ISSUE TITLE
The app is so slow on the pc but in the mobile it is ok 

### ISSUE THREAD

**Issue by Chllea** [GDQuest/learn-gdscript#132]
**Describe the bug**
My computer is decent at least it is better than my mobile so when i ran the app using my computer it say that my drivers does not support any of the supported webGl versions i tried to update chrome but nothing changed but when i go back to an older version of my driver it can run the app but its soo slow and it become soo hot on the other side my mobile don't have any problem running it even if its doesn't optimizied for mobiles. 

**To Reproduce**
Steps to reproduce the bug:
1. You just need to enter the app. 
**Expected behavior**
I expected it to work :) 
**Screenshots**
I don't have

**Information about your device (please complete the following information):**
 - Operating System: windows 10 
 - Browser chrome

**Additional context**
My labtob have 4 gb ram and intel basic graphics card when its opening the app but slow when i update it it doesn't work at all
While my mobile is huawei y 6 2019
I hope you find a solution

**Comment by pycbouh** [comment]
Please keep the discussion to the single issue

https://github.com/GDQuest/learn-gdscript/issues/129
