### ISSUE TITLE
Typos and missing keywords in CodeEditorEnhancer

### ISSUE THREAD

**Issue by Yagich** [GDQuest/learn-gdscript#135]
**Issue description:**
There are two typos in the [`CodeEditorEnhancer` class](https://github.com/GDQuest/learn-gdscript/blob/main/ui/components/CodeEditorEnhancer.gd): `rad2deg` and `deg2rad` are misspelled as `rad2def` [(line 101)](https://github.com/GDQuest/learn-gdscript/blob/main/ui/components/CodeEditorEnhancer.gd#L101) and `def2rad` [(line 69)](https://github.com/GDQuest/learn-gdscript/blob/main/ui/components/CodeEditorEnhancer.gd#L69), respectively.

There are also a few missing keywords, such as `in`, `not`, `or` (`and` is present), `puppet`, and probably others I have missed.

**Comment by pycbouh** [comment]
There are also combined keywords for networking, "remotesync", "mastersync", "puppetsync".

Doesn't seem like anything else is amiss, though GDScript also considers these as keywords:

```
	"PI", "TAU", "INF", "NAN",
	"null", "true", "false",
```

I've opted not to use them for now, but we may later.
