### ISSUE TITLE
Inconsistent use of I and we in lesson 7

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#136]
We wrote the course using the 1st person, but lesson 7 uses we in a part. we should correct that and make the pronouns consistent.

Related discussion: https://github.com/GDQuest/learn-gdscript/discussions/134

**Comment by johnnygossdev** [comment]
To clarify, are we using "I" or "we"?

My preference is "we" for the same reasons mentioned in the discussion.

https://github.com/GDQuest/learn-gdscript/discussions/134#discussioncomment-1945075
