### ISSUE TITLE
Course builder: Insert block bar does not always show on hover 

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#14]
It can be a bit difficult to get the blue bar to insert a new block to appear. I often have to wiggle my mouse a bit to get it to show up

**Comment by johnnygossdev** [comment]
I've not had a problem with this personally. Moving the cursor to the right spot and waiting < 1.0 second consistantly brings it up for me.

**Comment by pycbouh** [comment]
I've made it a tad faster still, let me know @NathanLovato if it helps. Wiggling your mouse shouldn't have any affect, the fade in timer counts as long as your mouse is over the hotzone, which is slightly taller than the visual element itself.

**Comment by NathanLovato** [comment]
I see, I didn't expect it to work on a timer: I expected it to show instantly (or almost instantly) as I hover over the correct area.
