### ISSUE TITLE
Lesson progress bar text, difficult to read, white on bright green

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#144]
**Describe the bug**
Difficult to read the course index lesson progress bar text.
White text on a bright green background.

**To Reproduce**
Steps to reproduce the bug:
With a completed lesson 100%.
1. Go to the Course Index
2. See the lesson progress bar text

![msedge_2UoRxjpZiA](https://user-images.githubusercontent.com/13420573/149351627-79d6fdb3-32b4-49bf-a119-7eefcd7f076d.png)

**Expected behavior**
The progress bar text should be easy to read.

**Information about your device (please complete the following information):**
 - Operating System: Windows 10 21H1
 - Browser: Microsoft Edge | 96.0.1054.62 (Official build) (64-bit)

**Comment by pycbouh** [comment]
I gave them an outline, which seems fitting with the design that we have. Also gave a similar treatment to big green buttons:

![image](https://user-images.githubusercontent.com/11782833/149548994-3cd22852-5aa0-479b-9fd2-4d9754e262ab.png)
