### ISSUE TITLE
ErrorOverlay not using new Revealer properly

### ISSUE THREAD

**Issue by Xananax** [GDQuest/learn-gdscript#147]
Lines 36 and 37  https://github.com/GDQuest/learn-gdscript/blob/45f5baf3c844c1336da64fff6a201e15ea051a6a/ui/components/popups/ErrorOverlayPopup.gd#L36

were erroring, so they've been commented out, but it seems they had something to do with the ErrorOverlay's UI logic because the first revealer is not occupying the full space no matter what

**Comment by pycbouh** [comment]
Closed by https://github.com/GDQuest/learn-gdscript/commit/0578193cbb36005fb749d451c7b7f0db1a344222
