### ISSUE TITLE
Add completion signal to practices to indicate when the animation/execution is completed

### ISSUE THREAD

**Issue by pycbouh** [GDQuest/learn-gdscript#148]
In https://github.com/GDQuest/learn-gdscript/commit/e4d259acb5f4b537cfdfbfe7577c28f4736c1bcb we've improved the practice flow to only run tests after the game output has fully completed whatever it needs to do. However, currently this is run off of a 5 second fixed timer, and that timer is only a fallback in case practice code doesn't emit the signal appropriately.

So this task is here to update all practices to emit the signal when appropriate (like, after the turtle has drawn its rectangle). The signal is:
```
Events.emit_signal("practice_run_completed")
```

I think you need to have a slight pause after it's done before firing it, to provide less jarring experience. In case of 0-input lessons, like the first one, just give it a short timer in practice code (like a second), and then emit the signal. Should be good enough.

**Comment by johnnygossdev** [comment]
I can do this when I do a pass on pronouns in the lessons.
