### ISSUE TITLE
Animate quizzes

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#15]
When giving the right answer, the quizz panel pops instantly. It’d be nice to animate the height. We could also animate the panel when showing a hint, see Consider adding optional hint to quizzes

**Comment by mathmods** [comment]
I'm working on this enhancement.

I'm considering using the existing tween object on a ColorRect (invisible by modulation) to change the size of the container without jumps. (Also adding a modulation tween to the resultview to ensure text doesn't "pop").

> We could also animate the panel when showing a hint, see Consider adding optional hint to quizzes

With this I'll consider making a "_switch_view" function that takes two views and animates the transition between the elements.

**Comment by NathanLovato** [comment]
Thanks for the help! Tweening the rect_min_size of some element would definitely be the way to go. Youĺl likely have to tween the size of the root container of the quiz UI so it properly moves elements around it in the lesson UI.

You can also set some container node to Clip Content during the transition to animate the container size. I think Revealer.tscn is a good example of how to approach UI animation like that.

And I see the referenced issue in my top post didn´t get linked correctly, itś #16

**Comment by mathmods** [comment]
Thanks for the tips! I'll look into that.
Clipping content will probably look better in code (and practice) than the thing I attempted last night (yielding to timers to hide and show the items).

And I now see how the help is supposed to work, I'll deal with that once I've gotten it to actually change size properly.
Might add an internal function that just checks the size of it's own contents and then animates to fit. (Upon size change of the margin container perhaps)
