### ISSUE TITLE
Drawing a Bigger Rectangle - Creating a valid rectangle generates error if using negative values

### ISSUE THREAD

**Issue by ChrisMacDee** [GDQuest/learn-gdscript#154]
**Describe the bug**
On the "Drawing a Bigger Rectangle" exercise, if you try to draw a rectangle using move_forward and turn_right, but use -90 instead of 90 for the turn_right, the app reports the resulting rectangle as incorrect when it isn't. (Realise this might be pedantic, but the error states that "The drawn shape is not a rectangle with a width of 220 and a length of 260", but it is. I assume the validation is being done on the code produced and not the resulting object. This may be a trivial example, but maybe prove to be a problem for more complicated modules later on.

**To Reproduce**
Steps to reproduce the bug:
1. Go to Drawing a Bigger Rectangle exercise.
2. Write the code like so:
`
move_forward(220)
turn_right(-90)
move_forward(260)
turn_right(-90)
move_forward(220)
turn_right(-90)
move_forward(260)
`

**Expected behavior**
Pass test as the generated rectangle is 220 x 260 pixels and is using the move forward and turn right functions. 

**Screenshots**
<img width="957" alt="image" src="https://user-images.githubusercontent.com/4313233/150162897-3e8d9d35-68e9-4132-a737-ed67300847ce.png">

**Information about your device (please complete the following information):**
 - Operating System: Windows 10
 - Browser: Brave, Chrome

**Additional context**
- None

**Comment by NathanLovato** [comment]
The validator is on the generated vertices. I think it's just we don't make coordinates absolute and so some vertices with negative coordinates make the test fail. We need to call abs() on the vertices on all those tests.

**Comment by ChrisMacDee** [comment]
Managed to find the test in question; I'm happy to take a look at it? I'm .Net/Web developer with 9 years experience, have also been noodling around with Godot for a while, so relatively safe hands :)

**Comment by johnnygossdev** [comment]
PRs are welcome!

**Comment by NathanLovato** [comment]
There are a couple places to update; I'll fix them now.

**Comment by ChrisMacDee** [comment]
No problem Nathan. 😊
