### ISSUE TITLE
Program Crashes, when not using "var"

### ISSUE THREAD

**Issue by Mustafa-the-king** [GDQuest/learn-gdscript#155]
# **In lesson 8 of the program, in the practice section:**
![image](https://user-images.githubusercontent.com/68613194/150326726-94cb4746-a5c5-4c6a-ab14-d35abffa6038.png)
### when I type in `health = 100` instead of `var health = 100`,  the app just _crashes_ (after clicking on run) and switches to the Godot window
![image](https://user-images.githubusercontent.com/68613194/150327454-187a0637-a725-452f-b778-2040bdcde4e6.png)
## Then switches to this:
![image](https://user-images.githubusercontent.com/68613194/150327812-d3375ed1-9ab3-4fb6-9aae-f514cb542c3f.png)

**Comment by pycbouh** [comment]
You need Godot 3.4.1+, 3.4 doesn't have this method yet.
