### ISSUE TITLE
Improve delta example in lesson 11

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#163]
Following the discussion in #3:

> Regarding the delta example in lesson 11, it's confusing to me as it is. I think there shouldn't be a reference row but only a version with and without delta. Also, there's a lot of choppiness in the motion and it's hard to understand.
> 
> If you want to get across the idea of varying time deltas, I would recommend not doing it like this as right now, both with and without delta, it just looks like neither approach works. I think showing only the character overshooting the target is enough.
> 
> In general, I think it'll be easier for students if we try to show only one thing at a time. If you want to illustrate variations in delta, then I'd make a different visualization. Maybe a graph of the value over time, something like that.

**Comment by NathanLovato** [comment]
Here's how I envision the example, assuming that the goal is to show why you want to use `delta`.

First is the reason: the time between frames varies, so to make characters move relative to time, we need to take into account the time between frames. If we don't, on different computers, with the same input, game entities will end up in different places, making the gameplay different.

So I would show just that: two characters moving in real-time, with the frame count and the time displayed. One uses delta, one doesn't, and after 1 or 2 seconds of walking, one ends up on the desired target location and one doesn't.

@johnnygossdev @Xananax what do you think?

**Comment by johnnygossdev** [comment]
This seems like a better, cleaner approach 👍🏻
