### ISSUE TITLE
Make lesson resources self-contained (single file)

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#165]
We have lots of files for lessons. This task is about embedding all subresources inside lessons. This will simplify proofing as we'd be able to run a proofing program straight on one lesson file and edit it as one text file.

It will also simplify code reviews for pull requests that add or modify a lesson as content won't be spread across many files anymore.

**Comment by pycbouh** [comment]
Note about implementation: we currently rely on resource paths for navigation. This needs to be adjusted because files will no longer be present on the disk (but we can still use similar identifiers to locate specific resources).
