### ISSUE TITLE
Program crashes during "Delta" lesson.

### ISSUE THREAD

**Issue by thayusmc** [GDQuest/learn-gdscript#166]
**Describe the bug**
In lesson 11, adding "* delta" to the first practice activity throws an error message and makes it freeze up.

**To Reproduce**
Steps to reproduce the bug:
1. Go to lesson 11
2. Try the first practice task
3. Type "* delta" after "rotate(2)"
4. Run the program and see the error.

**Expected behavior**
It should run the program in the application.

**Screenshots**
![image](https://user-images.githubusercontent.com/88183641/151047456-759a24a0-a57a-4870-b3ab-43d258656d6e.png)

![image](https://user-images.githubusercontent.com/88183641/151047391-c3f26ea6-ccd8-48ac-83d0-8191644e35c0.png)

**Information about your device (please complete the following information):**
 - Windows
 - Opera GX

**Comment by thayusmc** [comment]
I now realize I did the practice wrong -- the solution is rotate(2 * delta)

Silly me.

**Comment by NathanLovato** [comment]
Yes, that's an error in your code. If you run online with the language server, it'll just log the error in your console.
