### ISSUE TITLE
Using the scroll wheel inside a code box scrolls the whole screen down

### ISSUE THREAD

**Issue by thayusmc** [GDQuest/learn-gdscript#168]
**Is your feature request related to a problem? Please describe.**
It's a bit annoying when you use the scroll wheel on one of the code preview boxes, and the whole page scrolls with it.

**Describe the solution you'd like**
If the mouse is inside the code preview box and you use the scroll wheel, only scroll the box, not the page.

**Additional context**
![image](https://user-images.githubusercontent.com/88183641/151052778-2faab9d8-9657-41c1-aebe-289d470c5bb1.png)
^^^ These are the boxes I'm referring to.

**Comment by NathanLovato** [comment]
I just tried fixing this by consuming scroll input events from the code text boxes. Unfortunately, it seems there's no way to detect if a TextEdit has scrolling - the Vscrollbar node is always visible, and even if there's nothing to scroll, scroll_vertical or the bar's value are not capped.

That prevents us from consuming input only when there's a visible scroll bar from the user, making the experience a bit poor.

So I think that to fix this issue, we'd better work around it: avoid scrollbars altogether, like we did for UIPractice. Implementing #8 should address this issue as the main reason scroll bars appear is when increasing the font size.

**Comment by NathanLovato** [comment]
Otherwise, I think we'd need to make changes to Godot itself to make this work.

**Comment by NathanLovato** [comment]
Okay I implemented #8 but it wasn't enough. We also need to resize the code text boxes vertically

**Comment by NathanLovato** [comment]
The latest commit should do. It makes the code blocks increase height when the font size changes, which seems to prevent scroll bars from appearing. That way, no more nested scrolling containers and no more issues with those!
