### ISSUE TITLE
add linux/windows/mac os releases 

### ISSUE THREAD

**Issue by allaeddineomc** [GDQuest/learn-gdscript#171]
a lot of people have unstable internet connection or have low ram machines , and these people will get into trouble trying to use the web app , so it would be great to have native os executable releases

**Comment by NathanLovato** [comment]
It's a web app only. You need to connect to the server to get your code tested and validated, so that won't happen. The best you could do is run the server locally via the command line, which is not a good experience. For that reason, we won't do desktop releases for now.
