### ISSUE TITLE
Use typographical quotation marks instead of straight quotation marks

### ISSUE THREAD

**Issue by MaaaxiKing** [GDQuest/learn-gdscript#173]
I cannot stand universal quotation marks (“"”).
In my opinion, the typographical quotation marks ““” and “”” should be used in case the expression doesn't refer to code.
Possibly, it could be complicated because of unicode characters, but it's worth it.

**Comment by NathanLovato** [comment]
What's the issue exactly? That you don't like the straight quotes we use in computer code `"`?

**Comment by MaaaxiKing** [comment]
Yes, typographical ones make clear whether they start or end the expression whereas the universal ones don't.

**Comment by NathanLovato** [comment]
Do you really have trouble reading straight quotes? That's what we use in all codebases.

If it's about accessibility and it makes a real difference for some users reading, for some reason, I'm okay bothering to do that.

If it's more of an aesthetic thing and a pet peeve of someone, then we'll let a contributor outside the team tackle that instead.

**Comment by MaaaxiKing** [comment]
My problem with it is only due to style.

**Comment by NathanLovato** [comment]
Thanks, then I'll leave this up to a community member to tackle if someone wants to do it. This should be automated through a script/regex replace as we write in bbcode, using straight quotes.

**Comment by NathanLovato** [comment]
I discussed this issue with the team and we decided to stick to straight quotes. As a result, I'll close the issue.
