### ISSUE TITLE
Lesson 13 exercises allow setting the health directly as the solution

### ISSUE THREAD

**Issue by Nuoska** [GDQuest/learn-gdscript#178]
**Issue description:**
In lesson 13 the checks in the last two exercises are lacking. It's possible to clear them with unintended solutions.
```
func heal(amount):
    health = 80

func take_damage(amount):
    health = 0
```
Not sure if this counts as a bug or content issue.

**Comment by NathanLovato** [comment]
That's a limitation from our access to the GDScript compiler. I'm not sure if this is the bug I think, but if so, we may not be able to fix this. I'll try to address this later.

**Comment by NathanLovato** [comment]
I just checked and yes that's the issue I thought. We don't have access to the function's internals so you'll be able to cheat on those kinds of practices in general. I'll think of a workaround.

**Comment by NathanLovato** [comment]
Note for the team: as a workaround, we can run functions multiple times and save the state multiple times. Then run a check on that.
