### ISSUE TITLE
Some BBCode still not parsing

### ISSUE THREAD

**Issue by Haledire** [GDQuest/learn-gdscript#179]
**Describe the bug**
The method to add "(select all that apply)" in italics for UIQuizChoice.gd is not working.  The  `+=` operator is being used on `bbcode_text` as seen here: [fix: bbcode formatting appearing...](https://github.com/GDQuest/learn-gdscript/commit/89c4d2f0edacb64fbbd7a8c5202e0074168277be)

This seems to be failing somehow in the web app.  On a local install of 3.4.2 this behavior doesn't happen in my testing.

As described in the Godot Documentation:

> Note: It is unadvised to use the += operator with bbcode_text (e.g. bbcode_text += "some string") as it replaces the **whole text** and can cause slowdowns. Use append_bbcode for adding text instead, unless you absolutely need to close a tag that was opened in an earlier method call.

The method should probably be either:
```
if quiz_choice.is_multiple_choice:
               _question.append_bbcode(" [i]" + tr("(select all that apply)") + "[/i]")
```
 or the more verbose method:
```
if quiz_choice.is_multiple_choice:
               _question.push_italics()
               _question.add_text( tr("(select all that apply)"))
               _question.pop()
```
 to maintain the tag stack.

**To Reproduce**
Steps to reproduce the bug:
Case 1:
1. Go to [Lesson 3](https://gdquest.github.io/learn-gdscript/#course/lesson-3-standing-on-shoulders-of-giants/lesson.tres)
2. Scroll down to the Quiz 3/4 of the page down.
3. See the Quiz block with the `select all that apply` text.

Case 2:
1. Go to [Lesson 5](https://gdquest.github.io/learn-gdscript/#course/lesson-5-your-first-function/lesson.tres)
2. Scroll down to the bottom of the page.
3. See the Quiz block at the bottom with the header displaying bbcode tags

**Expected behavior**
The text should be bolding and italicizing properly

**Screenshots**
![image](https://user-images.githubusercontent.com/164616/151264294-ca79cd3a-6eac-4a6a-867a-9f447b0cf018.png)

![image](https://user-images.githubusercontent.com/164616/151264063-e1972097-8908-470a-9bca-e060dd6771ff.png)

**Information about your device (please complete the following information):**
 - Operating System: [e.g. iOS, Windows]
 Windows 10
Chrome, Firefox, Brave

**Comment by NathanLovato** [comment]
The bug's fixed already, it's just you tried the last stable release of the app. It's normal it doesn't have the latest bug fixes.
