### ISSUE TITLE
Give note and spoiler blocks a more appropriate look

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#18]
Currently they use a plain revealer and don’t really stand out. The idea with those blocks was to have them folded by default as they provide info that goes beyond the lesson. But they could use a better presentation.

**Comment by pycbouh** [comment]
Here's a new look

https://user-images.githubusercontent.com/11782833/149360066-9c261b0f-275a-4c0f-81f2-305fba7fdd82.mp4
