### ISSUE TITLE
No text style on section 3

### ISSUE THREAD

**Issue by mefjak** [GDQuest/learn-gdscript#188]
![image](https://user-images.githubusercontent.com/22888465/151358099-f3655161-89e7-4fdf-bbf2-47750383a7e0.png)

**Comment by pycbouh** [comment]
Thanks for the report, this was reported (https://github.com/GDQuest/learn-gdscript/issues/170, https://github.com/GDQuest/learn-gdscript/issues/179) and fixed already :)

**Comment by mefjak** [comment]
Thanks and sorry for duplicate :)
