### ISSUE TITLE
_process function can run once a second

### ISSUE THREAD

**Issue by MaaaxiKing** [GDQuest/learn-gdscript#193]
**Issue description:**
In lesson “10. The Game Loop”, only the answer saying the process function runs multiple times a second is correct, but this is wrong because the framerate could be 1 and the function is called every frame.

**Comment by NathanLovato** [comment]
I don't think this kind of accuracy is good for students. You should expect game updates to occur many times per second. If your frame time is one second, there's a huge problem with your game.

Saying the framerate could theoretically go to 1 or less than 1 gives you the wrong mental model about games: that should never happen.

**Comment by MaaaxiKing** [comment]
Of course it's unlikely, but spreading wrong information is neither good.

**Comment by NathanLovato** [comment]
It's not wrong info, as explained above.
