### ISSUE TITLE
Multiple choice quizzes fail tu parse question bb code

### ISSUE THREAD

**Issue by noidexe** [GDQuest/learn-gdscript#194]
**Describe the bug**
You can see [b], [i], etc in the question for all quizzes with checkboxes. It doesn't happen with the ones using radio buttons. 

**To Reproduce**
Steps to reproduce the bug:
Go to https://gdquest.github.io/learn-gdscript/#course/lesson-12-using-variables/lesson.tres and scroll to the bottom

**Expected behavior**
Should show text correctly formatted

**Screenshots**
![image](https://user-images.githubusercontent.com/526829/151379096-a7aba563-8466-4697-81c4-7417f37bf58f.png)

**Information about your device (please complete the following information):**
- Windows 10
- Firefox x64 96.0.2

**Comment by pycbouh** [comment]
This has already been reported and fixed, but thanks nonetheless!

**Comment by NathanLovato** [comment]
Fixed already #179
