### ISSUE TITLE
BBcode not interpreted on quiz for lesson 3

### ISSUE THREAD

**Issue by matthewpaul-us** [GDQuest/learn-gdscript#195]
**Describe the bug**
The BBcode for the question on lesson 3 is not interpreted and rather shows the plaintext including the tags.

**To Reproduce**
Steps to reproduce the bug:
1. Go to [Lesson 3](https://gdquest.github.io/learn-gdscript/#course/lesson-3-standing-on-shoulders-of-giants/lesson.tres)
2. Scroll to bottom where the quiz is
3. Note the BBcode tags

**Expected behavior**
The BBcode tags are interpreted; the title is bolded and the italics are italicised

**Screenshots**
![image](https://user-images.githubusercontent.com/1484070/151383462-203bdc72-7af8-4d37-a155-c450313d8164.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows 11
 - Browser Microsoft Edge

**Additional context**
I do run adblockers both locally and through pi-hole. The client adblocker isn't blocking anything. Haven't checked yet on the pi-hole, but I can if need be.
[gdquest-1643295008014.log](https://github.com/GDQuest/learn-gdscript/files/7951333/gdquest-1643295008014.log)

**Comment by NathanLovato** [comment]
Please use the latest version of the app to report bugs, not the stable release. This was reported 5 times already, it's already fixed.

**Comment by matthewpaul-us** [comment]
Many apologies! I clicked the link in the email and thought it was the latest. I will switch to [Staging](https://gdquest.github.io/learn-gdscript/staging/) for my further testing.
