### ISSUE TITLE
HTML displayed in lessons 11 and 13

### ISSUE THREAD

**Issue by zircher** [GDQuest/learn-gdscript#199]
The second question in this lesson is displaying HTML tags.

**Comment by zircher** [comment]
The last quiz question on Lesson 13 also has this issue.

**Comment by johnnygossdev** [comment]
This isn't happening on my browser (Firefox). Can you supply more information please? What browser are you using? If you could supply screenshots, that would help too.

**Comment by NathanLovato** [comment]
Can't reproduce. Could you share a screenshot? Also, on which browser is this happening and on which OS?

**Comment by zircher** [comment]
Using Brave (Chromium) on Win10.  No screen shot since the questions disappear when answered.  Will post if I see it again.

**Comment by NathanLovato** [comment]
Was it perhaps bbcode inside quizzes? like [b]Question here[/b]? If so, the bug's already fixed and a duplicate of #179 #195 etc.

Or is it really HTML code, like <p>...</p>? That shouldn't be possible as the app uses WebGL and not HTML internally.

**Comment by zircher** [comment]
Ah yes, it was the BB code.  Sorry about the confusion there.  But, it did not happen for all questions, only a couple.

**Comment by NathanLovato** [comment]
Okay, then it's already fixed.
