### ISSUE TITLE
Course builder: show confirmation dialog before changing quizz type between choice and input field

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#20]
Changing the quizz type causes the creation of a new quizz resource and loss of the answers.

**Comment by mathmods** [comment]
I'm working on this enhancement.
I'm thinking of adding a script variable that tracks the choice. The confirm function will then use the variable to commit the change.

**Comment by NathanLovato** [comment]
Thanks! Sounds good. You can copy some code to popup confirmation dialogs in classes like LessonPracticeHint.gd too.
