### ISSUE TITLE
PracticeDonePopup is displayed off-screen when testing a single practice from the course builder

### ISSUE THREAD

**Issue by johnnygossdev** [GDQuest/learn-gdscript#202]
**Describe the bug**
PracticeDonePopup displays in the bottom right corner of the screen.

**To Reproduce**
Steps to reproduce the bug:
1. Go to [Any practice]
2. Successfully Complete it

**Expected behavior**
Well done pannel shown in the centre of the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/3285214/151542461-43cb9a3c-f9db-4e66-a3ea-ff35fa06eb3f.png)

**Information about your device (please complete the following information):**
 - Operating System: [Windows]
 - Tested in the editor on main

**Comment by NathanLovato** [comment]
This is only when testing from the course builder, isn't it? I've only seen this happen when testing a practice in isolation. Or does it also happen when testing the whole app with F5?

**Comment by johnnygossdev** [comment]
> This is only when testing from the course builder, isn't it? I've only seen this happen when testing a practice in isolation. Or does it also happen when testing the whole app with F5?

You're correct, F5 doesn't seem to have a problem.
