### ISSUE TITLE
Modulo needs further explaination

### ISSUE THREAD

**Issue by Feniks-Gaming** [GDQuest/learn-gdscript#203]
**Issue description:**
A clear and concise description of what the issue is.

I was looking at lesson with modulo and all examples of reminder are used with first bigger number and modulo number being smaller for example `11 % 4` however later student is asked to do something like 1 % 3 which is confusing because in ordinary maths lessons we are almost never ask students to calculate the remainder of dividing smaller number by bigger number. It will probably be confusing to most people. Why 1 % 3 is 1 not 0. I tested it on my daughter who is 10 and has done all the basic maths they teach them including finding remainder in her head remainder of dividing 1 by any number larger than 1 is 0. I have also done a quick test by asking my partner and she also stated that 1 % 3 is 0 because there isn't a remainder . I think this needs to be explained as to why this works they way it works.

**Comment by johnnygossdev** [comment]
I agree, it's tricky and not needed. I think Nathan clamped the modulo example so it doesn't handle cases where the divisor is larger, but the lesson and practices need updating to refelct this change

**Comment by NathanLovato** [comment]
> Nathan clamped the modulo example so it doesn't handle cases where the divisor is larger

It's already reverted and the patch is live in 0.2.1.

The lesson just needs an extra example to emphasize that indeed 1 % 3 is valid. 1 / 3 == 0, with a remainder of 1.
