### ISSUE TITLE
Lesson 5: Draw Multiple Squares – Inaccurate Fail Reason

### ISSUE THREAD

**Issue by MarioLiebisch** [GDQuest/learn-gdscript#205]
**Describe the bug**
If you move the cursor/turtle after the third rectangle, the checks will claim you drew more than 3 rectangles, which actually isn't necessarily the case. If the turtle position is important, this should specifically mention the position.

**To Reproduce**
Implement the solution using a for loop (which calls `jump()` one extra time):

```py
func draw_three_squares():
	for n in 3:
		draw_square()
		jump(300, 300)
```
The reported error is:

> You drew more than three squares. You need to draw only three!

**Expected behavior**
While it can be argued, the solution shouldn't be accepted (since the turtle is in the wrong position), the error message should clearly state this instead of claiming there'd be more than three squares:

> The turtle isn't on the last rectangle.

(Or something similar)

**Comment by NathanLovato** [comment]
Makes sense. It's that calling jump() not only moves the turtle but also initializes a new polygon. That's why the code sees one extra shape. This is an app for people learning to code from zero - at this point, students aren't supposed to know about loops. But we'll take that into consideration.

**Comment by MarioLiebisch** [comment]
Yeah no worries, at some point I was tempted to find out how far I can go and it still accepting it. 😉

But great app, so far – and fun, even if you know your way around the language.👍
