### ISSUE TITLE
In lesson 9 the robot that takes 25 health doesn't stop at 0 and continues to negative number.  edit: oh never mind should of read the rest of the lesson.

### ISSUE THREAD

**Issue by Raxvier** [GDQuest/learn-gdscript#211]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug:

**Expected behavior**

**Screenshots**
If applicable, drag and drop screenshots h
![image_2022-01-29_193559](https://user-images.githubusercontent.com/98636812/151669117-7740c016-a45c-4b03-9329-f676c01fe579.png)
ere to help explain your problem.

**Information about your device (please complete the following information):**
 - Operating System: [e.g. iOS, Windows]

**Additional context**

**Comment by NathanLovato** [comment]
It's on purpose and explained in the lesson

![image](https://user-images.githubusercontent.com/12694995/151669214-c8c6c926-21c4-4052-b334-d29a9c7d4de5.png)
