### ISSUE TITLE
Invalid code make the app crash instead of showing an error

### ISSUE THREAD

**Issue by astrale-sharp** [GDQuest/learn-gdscript#215]
**Describe the bug**
Tested on commit : dbb78a282d57dd456d21d778ce539df2391366c2

In the code editor of the app, for any lesson, some invalid code will make the app crash with the obscure error "Invalid call, Nonexistent function 'get_rect_at_line_column' in base 'TextEdit' (SliceEditor.gd)".

For instance the code `var angular-speed` (which is invalid but is likely to be written by a beginner taking lesson 12 on variable) will make the app crash

**To Reproduce**
Steps to reproduce the bug:
1. Open the project in the editor
2. Run the main scene (F5)
3. Go to Continue course (or Start Course)
4. In the code editor, copy paste one of the following snippets
```gdscript
var angular-speed = 4
```
```gdscript
func _process(delta):
    rotate(4 * delta) var
```
5. Press the Run button

**Expected behavior**
A parsing error should appear (ideally pointing the solution for some specific example, writing "my-var" instead of "my_var" for instance)

**Screenshots**
![image](https://user-images.githubusercontent.com/53686698/151720260-d4f2ae4c-6beb-400e-aef0-f06011900f3c.png)

**Information about your device (please complete the following information):**
 - Operating System: 
```
 ██████████████████  ████████     astrale@Hubris
 ██████████████████  ████████     OS: Manjaro 21.2.1 Qonos
 ██████████████████  ████████     Kernel: x86_64 Linux 5.10.89-1-MANJARO
 ██████████████████  ████████     Uptime: 6h 29m
 ████████            ████████     Packages: 1461
 ████████  ████████  ████████     Shell: fish 3.3.1
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: KDE 5.89.0 / Plasma 5.23.4
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Breath [GTK2/3]
 ████████  ████████  ████████     Icon Theme: breeze-dark
 ████████  ████████  ████████     Disk: 2,2T / 4,0T (59%)
 ████████  ████████  ████████     CPU: AMD Ryzen 7 4800H with Radeon Graphics @ 16x 2.9GHz
 ████████  ████████  ████████     GPU: AMD/ATI
                                  RAM: 6016MiB / 15462MiB

```
 - In the Godot editor, Godot 3.4.stable.official

**Comment by NathanLovato** [comment]
The app is designed to run on the web. It's not a crash: you're running Godot in debug mode, so the debugger pauses execution when it encounters a parse error, like any Godot project in debug mode.

Here's what happens when running the app in release mode

![image](https://user-images.githubusercontent.com/12694995/151725938-ace47abf-3204-4f12-9219-4d59dbf70f55.png)
