### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#22]
We need to dump the content of all course resources to text documents or something. Ideally po files.
Our i18n program can convert text files to .po files, so we could just convert lessons etc. to text files.
Godot supports .po files natively and for an efficient translation workflow (pro stuff) it’s more efficient than using CSV (pro translation programs work with formats like .po).
We need to figure out how to handle translation keys.
Translations should also work for the GDScript errors, using their simple keys

**Comment by brean** [comment]
I would highly appreciate/like to help with (German) translations.
I am teaching Game Development with Godot in Hackathons (with the Code+Design organization) to school children in Germany. This would help a lot for basic understanding before or after the Hackathon so the students could teach themselves and learn more than just importing graphics and changing templates.

**Comment by NathanLovato** [comment]
We'll make a call for community translations once we have localization support. For now, though, there's quite a bit of work to extract all the translation strings from the app.

**Comment by NathanLovato** [comment]
We need to translate:

- Button labels
- Tooltips
- Lessons and practices
- The welcome and end screens
- Messages in popups
- The code reference (documentation.csv)
- Error explanations (error_database.csv)

Translation files should be in the gettext format so professional translators can easily work on it.

As far as translation files, I'd like to have, if possible:

- One file for all UI translations (buttons, tooltips, help messages, popups, etc.).
- One file per lesson, including its practices (to make it easy to translate content sequentially and ship partial translations of the course).
- One file for error explanations.
- One file for the code reference.

Does that sound like a reasonable number of files @pycbouh?

**Comment by NathanLovato** [comment]
@pycbouh thanks for your work on this.

I just tested the .pot files, there's one detail to change: the output files have `\r\n` for line returns, but the translation program warns that we shouldn't have `\r` for internationalization, only `\n`.

**Comment by pycbouh** [comment]
> I just tested the .pot files, there's one detail to change: the output files have `\r\n` for line returns, but the translation program warns that we shouldn't have `\r` for internationalization, only `\n`.

That's not something that we explicitly control, but I'll see what we can do.

**Comment by pycbouh** [comment]
Okay, just replacing it while extracting seems to solve the issue, so I'll leave it at that.

**Comment by pycbouh** [comment]
Localization should now be supported throughout the app. There may still be missing pieces of the UI, or properties that we don't extract, so please open bugs if you run into something. There are a couple of peculiarities and weird issues too, I've made sure to comment on those in code.

I've also added a doc on working with translations here: https://github.com/GDQuest/learn-gdscript/blob/main/i18n/working-with-translations.md
