### ISSUE TITLE
Lesson 13 : reset button don't reset to the original value

### ISSUE THREAD

**Issue by survivant** [GDQuest/learn-gdscript#224]
When we start the Lesson, the value is 75
![image](https://user-images.githubusercontent.com/191879/151893922-5649e014-ad14-4eb5-b028-66f49894d0d8.png)

if you press Heal and do reset after, the value will be 1. 
![image](https://user-images.githubusercontent.com/191879/151893869-f993e652-4484-4d13-9274-d0b59cd076c4.png)

If we do a reset, it needs to return to the original value

**Comment by Michael-Sjogren** [comment]
Im not sure if this is a bug. what would be the expected value when pressing reset? 75?

**Comment by NathanLovato** [comment]
Fixed by 14fb1aeaa28148e68b5828f0fc8358a40a8d86b1
