### ISSUE TITLE
max_screen icon issue

### ISSUE THREAD

**Issue by survivant** [GDQuest/learn-gdscript#226]
if I check at this screen (when the course is complete)
![image](https://user-images.githubusercontent.com/191879/151899725-81618718-6370-4e0a-be9e-7b48ebaa21d5.png)

if I click on the icon, the app will take the full screen
![image](https://user-images.githubusercontent.com/191879/151899775-e95e7df0-deb9-4b61-9e6b-2572f0c795f3.png)

but if I click again on the icon, the screen return to normal, but the icon changed
![image](https://user-images.githubusercontent.com/191879/151899812-e3fdecd1-1cef-420b-b323-8e079d2407a1.png)

**Comment by NathanLovato** [comment]
This only happens in the browser. I checked the code, it's supposedly correct and behaving as intended on the desktop. But once it gets to the browser, it fails, suggesting that the value of `OS.window_fullscreen` doesn't work the same as on desktop. For now, I don't know how to fix this.

**Comment by survivant** [comment]
is it possible to detect if you are in a browser, if that's the case, you could save the screen size value before clicking on the button and use those values when you click again.

**Comment by NathanLovato** [comment]
I found a workaround. We still need to get some kind of event or something from the browser when the user toggles fullscreen from outside the app - I'm unsure we can, but let's see, I'll open a separate task
