### ISSUE TITLE
Play different animation when clicking 'previous practice'-button

### ISSUE THREAD

**Issue by SpyrexDE** [GDQuest/learn-gdscript#227]
**Describe the bug**
When clicking on the "<-" button on a practice screen, a slide from right to left animation gets played. It's really irritating.

**To Reproduce**
Steps to reproduce the bug:
1. Open a practice
2. Click on the -> button
3. Click on the <- button
4. Same animation

**Expected behavior**
Playing a left to right slide animation when "<-" was clicked

**Comment by pycbouh** [comment]
That's because buttons at the bottom are not to go back in history. They open the previous practice in the lesson, not the previous page. They actually move you forward in history. The button at the top of the page is for going back in history, those are not. Consider how on a page listing goods at a marketplace you have pagination with arrows allowing you to go back or forth by one page. Those actions move you forward in history. Same applies here.

**Comment by SpyrexDE** [comment]
Okay, but the animation is still very confusing.

**Comment by pycbouh** [comment]
The animation is consistent. It opens a new page, a new page is opened on the right. Clicking the back button at the top and clicking the previous practice button at the bottom are different actions.

Case 1:
1. You're in Practice 1
2. You finish it and go to Practice 2
3. You click the back button at the top
4. You get to the old page with Practice 1

Your history is:
P1
P1 -> P2
P1

Case 2:
1. You're in Practice 1
2. You finish it and go to Practice 2
3. You click on the "open previous practice" button at the bottom
4. You open a new page with Practice 1

Your history is:
P1
P1 -> P2
P1 -> P2 -> P1

-----

It's the same difference as when you navigate on any multipage website in your browser. Using in-site navigation moves you forward in history, even if you open the same page as the one you've previously visited. Using in-browser navigation allows you to move back in history. The back button on top is akin to the in-browser back button (in fact, in this app, they are exactly equivalent). The bottom panel practice navigation is akin to the in-site navigation.

**Comment by SpyrexDE** [comment]
Yeah, I already understood that and it also makes sense to me now. But clicking on an arrow pointing to the left making you move to the right feels wrong at first glance. And I am sure that I am not the only one who thinks like that.

**Comment by pycbouh** [comment]
Yeah, I can see what you mean. If they are confusing, we may just as well remove them. There is not much point in quickly moving left and right, you can use the full practice list to open any practice directly and the "Continue" button to progress.
