### ISSUE TITLE
Animate checks in UIPractice

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#23]
To grab the user’s attention and make it clear when some check(s) failed

**Comment by pycbouh** [comment]
https://user-images.githubusercontent.com/11782833/150353888-41ca63ef-23f6-46e1-9472-2c5f52cf5323.mp4

https://user-images.githubusercontent.com/11782833/150353896-52b12cec-1f6f-4fb5-b1fc-cbe64ac8a26d.mp4
