### ISSUE TITLE
Lesson 11, correct solution not accepted with `ctrl enter`, but Run button and F5 works

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#230]
**Describe the bug**

The practice exercises in Lesson 11.
Doesn't accept the correct solution when `ctrl enter` is pressed.
>ERROR There's something wrong here.

But it works:
- when mouse-clicking on the `Run` button
- or when pressing: `F5`

**To Reproduce**
Steps to reproduce the bug:
1. Go to either of the practice exercises:
https://gdquest.github.io/learn-gdscript/#course/lesson-11-time-delta/practice-UdOCQiGj.tres
https://gdquest.github.io/learn-gdscript/#course/lesson-11-time-delta/practice-x0c7DDiz.tres
2. Click on the `Solution` button
3. Focus the code editor by mouse clicking on it
4. Press `ctrl enter`

**Expected behavior**

The "Well done!" message should appear.

Just like it does when clicking on the `Run` button, or when pressing `F5`

**Observed**

The Checks section on the left side says:
> X Rotating Characters Is Time Dependent

The Output panel on the right side says:
>ERROR There's something wrong here.

**Information about your device (please complete the following information):**
 - Operating System: Windows 21H1
 - Browser: Microsoft Edge | 97.0.1072.69 (Official build) (64-bit)

**Additional context**

`ctrl enter` works in lessons 9 and 10, haven't tried 12 or later yet.

**Comment by NathanLovato** [comment]
I can't reproduce the issue, the shortcut works here and the solution works the same as pressing run or F5.

Didn't you insert a typo by accident somehow? Or does pressing the shortcut insert a character in the text editor for you?

**Comment by duianto** [comment]
It happens every time.

**Comment by duianto** [comment]
The same thing happens in Firefox 96.0.3 (64-bit)

**Comment by duianto** [comment]
The cursor also moves in both lesson 12 practice exercises,
when `ctrl enter` is pressed, but the solutions are accepted without any errors.

https://gdquest.github.io/learn-gdscript/#course/lesson-12-using-variables/practice-lkGx0c7D.tres
https://gdquest.github.io/learn-gdscript/#course/lesson-12-using-variables/practice-KUdOCQiG.tres

**Comment by duianto** [comment]
Just learned about the staging version. https://github.com/GDQuest/learn-gdscript/issues/236#issuecomment-1027040024

`ctrl enter` also shows an error in its Lesson 11:
https://gdquest.github.io/learn-gdscript/staging/#course/lesson-11-time-delta/practice-UdOCQiGj.tres

And just like in the stable version, `ctrl enter` works in both:
- Lesson 10
https://gdquest.github.io/learn-gdscript/staging/#course/lesson-10-the-game-loop/practice-tKRHJMQ2.tres
- and Lesson 12
https://gdquest.github.io/learn-gdscript/staging/#course/lesson-12-using-variables/practice-lkGx0c7D.tres
