### ISSUE TITLE
Lesson 11, 2nd exercise, "towards its left hand" sounds like it wants a negative value

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#232]
**Issue description:**

In lesson 11, the second practice exercise:
https://gdquest.github.io/learn-gdscript/#course/lesson-11-time-delta/practice-x0c7DDiz.tres

In the Goals section. The second paragraph says:
>To get this movement, the robot should rotate 2 radians per second and move 100 pixels per second towards its left hand.

`towards its left hand`, sounds like we should be moving to the left, by using a negative value.

The correct solution uses a positive value.

**Comment by Xananax** [comment]
Using "clockwise", "counter clockwise" terms may be better?

**Comment by duianto** [comment]
Ok, it was referring to the left hand from the character's point of view,
not the hand on the left side of the character.

Maybe it could say something like:
>To get this movement, the robot should rotate 2 radians per second and move 100 pixels per second to the right, so that it rotates clockwise.
