### ISSUE TITLE
Keyboard support on the "Well done!" message

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#233]
**Is your feature request related to a problem? Please describe.**

Add keyboard support to the "Well done!" message, 
that appears when a practice exercise is solved.

This would also solve the unexpected behavior, 
that occurs when someone tries to select the `stay` button, by pressing the `left` key.
The page switches to the previous page.

**Reproduction steps**

The unexpected behavior seems to happen in all exercises, but open:
https://gdquest.github.io/learn-gdscript/#course/lesson-11-time-delta/practice-UdOCQiGj.tres
- Click on the `solution` button
- Click on the `run` button
When the  "Well done!" message appears
- Press the `left` arrow key

**Observed**
The page switches to the previous page,

**Expected**

- `left` arrow key, select the `stay` button
- `right` arrow key, select the `continue` button
- `enter` press the selected button
- `esc`, the same behavior as the `stay` button (it closes the "Well done!" message)

**Additional context**

Currently, when the "Well done!" message is shown.

If the lesson was solved:
- by pressing: `ctrl enter` or `F5`, then the code editor remains focused,
and the arrow keys move the cursor in the background behind the message.
- by clicking on the `run` button, then the buttons at the bottom middle are focused,
and now the arrow keys navigate between the buttons.
`right`, `down`, and `up` works as expected.

Pressing `right` from the `reset` or `continue` buttons,
highlights the buttons in the top right corner:
`Report an issue`, then `Configure the app` and finally `Toggle the app full-screen`

The code editor becomes focused,
- when the `up` key is pressed, when a top row button (at the bottom middle) is selected
- or when the `down` key is pressed, when a top right corner button is selected

**Comment by NathanLovato** [comment]
Thanks for the report. This one's a bug, that shouldn't happen.

**Comment by NathanLovato** [comment]
I'm working on this now. I found that pressing the left key on the button triggers a ui_back event. Even though it's set to Ctrl Alt Left and you're only pressing left, in this context it still fires up, which seems like a Godot-side bug. I'll add a workaround shortly to fix this.
