### ISSUE TITLE
Lesson 13, health bar differs between page load and Reset button

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#236]
**Is your feature request related to a problem? Please describe.**

In lesson 13:
https://gdquest.github.io/learn-gdscript/#course/lesson-13-conditions/lesson.tres

The first example shows a health bar with `health = 75`.
But when the `Reset` button is pressed, then it goes down to `health = 1`.

It might be more consistent to have the same initial and `Reset` values.

**Comment by NathanLovato** [comment]
Thanks for the reports. Just so you know, you should test this version of the app: https://gdquest.github.io/learn-gdscript/staging/

We update it more often than the stable release, which is the one you've been testing.

**Comment by duianto** [comment]
>you should test this version of the app: https://gdquest.github.io/learn-gdscript/staging/

👍 

The same thing is observed in the staging version.
