### ISSUE TITLE
Lesson 4: reset button doesn't reset fully

### ISSUE THREAD

**Issue by unfa** [GDQuest/learn-gdscript#237]
**Describe the bug**
The demonstration of line drawing doesn't reset fully on "Reset" button press.

![image](https://user-images.githubusercontent.com/491704/152003951-bf257b3b-c882-4c62-a940-dd398108a00e.png)

URL: https://gdquest.github.io/learn-gdscript/#course/lesson-4-drawing-a-rectangle/lesson.tres

**To Reproduce**
Steps to reproduce the bug:
1. Go to Lesson 4
2. Click on Run
4. Click on Reset
5. See error

**Information about your device (please complete the following information):**
 - Operating System: Arch Linux, KDE
 - Browser Brave (Chromium-Based)

**Additional context**

**Comment by NathanLovato** [comment]
It's already fixed. You can try the latest version of the app (staging/pre-release) here: https://gdquest.github.io/learn-gdscript/staging/

Here's the lesson in staging: https://gdquest.github.io/learn-gdscript/staging/#course/lesson-4-drawing-a-rectangle/lesson.tres

**Comment by unfa** [comment]
Ah, I see. Thanks!
