### ISSUE TITLE
Lesson 13  :button back doesn't work

### ISSUE THREAD

**Issue by survivant** [GDQuest/learn-gdscript#244]
I click on the button and nothing happen
![image](https://user-images.githubusercontent.com/191879/152079125-9e321076-5787-41d8-9da7-c72efe58ed16.png)

**Comment by pycbouh** [comment]
It's disabled...

**Comment by NathanLovato** [comment]
Yeah the button is disabled, there's no navigation history.

Where would you expect to go back? To the course outliner? To the welcome screen?

**Comment by survivant** [comment]
I was expecting to back to the previous section like Lesson 12.  Or.. if it's a "back button" for the current lesson, the button should be hidden when you're on the first page of the lesson.  I think it will make for sense with the second option

**Comment by NathanLovato** [comment]
It's for back navigation / history. We shouldn't hide the button and change the interface I think. When a button isn't usable, throughout Godot and the app, it gets disabled.

We'll see if we can make things clearer.

**Comment by NathanLovato** [comment]
@pycbouh do you think we should add the ability to go back to the outliner or welcome screen, depending on where the user came from? I think a user could expect that when seeing the button.

Otherwise, the simple fix here would be to update the hint on hover, saying something like

> Go back in your navigation history (no history)

When the button's disabled. What do you think?

**Comment by pycbouh** [comment]
I don't think there is a good reason to change the behavior. A disabled back button is a normal occurrence in browser with which we are sort of trying to match our behavior here. But we can update the tooltip.
