### ISSUE TITLE
Lesson 4. Drawing a rectangle

### ISSUE THREAD

**Issue by AltSHADOW** [GDQuest/learn-gdscript#246]
**Describe the bug**
If U press "Run" it draws a line and number, but if "Reset" is pressed then the line and number just move to the left and stay visible.

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'Lesson 4. Drawing a rectangle'
2. Click on 'Run' button
3. Click on 'Reset' button

**Expected behavior**
As I think line and number must disappear once "Reset" is pressed

**Information about your device (please complete the following information):**
 - Operating System: Windows 10
 - Browser Chrome
![image](https://user-images.githubusercontent.com/38314080/152162900-8278bf3b-679b-4132-91a3-8a42af8ebf30.png)

**Comment by mathmods** [comment]
It's already fixed on the latest version by #181 and #237 
You can try the latest (non-stable) version on https://gdquest.github.io/learn-gdscript/staging/
