### ISSUE TITLE
Solution panel doesn't show when using `Play Current` button in the editor

### ISSUE THREAD

**Issue by johnnygossdev** [GDQuest/learn-gdscript#250]
**Describe the bug**
We currently can't use the solution panel while testing practices via the `Play Current` button because it doesn't appear.

**Screenshots**
Here's a video showing first that the solution works when running the app, then how it doesn't show when using the `Play Current` button.

https://user-images.githubusercontent.com/3285214/152370714-754e626e-6dc4-4ad5-8419-2ddc4ebaa047.mp4

**Information about your device (please complete the following information):**
 - Operating System: [Windows]

**Comment by pycbouh** [comment]
Eh, judging by this and https://github.com/GDQuest/learn-gdscript/issues/202, I think that when the UIPractice scene is played separately it doesn't get its anchors in the correct place, or some of it doesn't. Should probably add some setting for anchors and margins on ready for some of the root controls there.

**Comment by pycbouh** [comment]
It was due to pause mode. We set it to "process" on the top-most control in the whole project (UICore), so when we run the practice scene individually, it doesn't have that and defaults to pausing. Now it won't.
