### ISSUE TITLE
Chapter 15 Modulo wrong order of example

### ISSUE THREAD

**Issue by thorstenSchmitz** [GDQuest/learn-gdscript#252]
**Issue description:**
The Traffic Light examples are in the wrong order, so they don't fit the description text. 

<img width="624" alt="Bildschirmfoto 2022-02-03 um 18 59 36" src="https://user-images.githubusercontent.com/4238585/152403774-f2540080-d70c-44c2-876c-816d3ce9f44c.png">

**Comment by NathanLovato** [comment]
This is already fixed: #241
