### ISSUE TITLE
Lession 5 function syntax rule contradiction

### ISSUE THREAD

**Issue by AimVaguely** [GDQuest/learn-gdscript#254]
**Issue description:**
In lesson 5 under the subtitle "Names in code have rules" it says that GDScript uses underscores (`_`) to represent spaces in functions. Then in the quiz you use the function name `make3NewCharacters` as an example with having a number in a function, without mentioning that it is breaking the common syntax rules by using camel case instead of snake case. This is still valid code, but it contradicts itself and I feel might cause unnecessary confusion to beginners (I assumed that it was an incorrect answer, and only though my programming experience with knowing that it would work anyway got it right the second time).

**Recommendation**
If it was me I would either change the function name to `make_3_new_characters` or leave it as is and explain that it would work but is bad to not follow the naming guidelines.

Disclaimer: I am a programmer and not a UX designer.

**Comment by NathanLovato** [comment]
> it is breaking the common syntax rules

It's not breaking the syntax: there are no spaces. It's not conventional or idiomatic in GDScript, but it's still respecting the syntax rules. I'll try to rephrase to make this clearer though.

**Comment by AimVaguely** [comment]
By "common syntax rules", I meant something along the line of code guidelines or coding conventions. More specially naming conventions (e.g. [C# naming conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#naming-conventions)), I just couldn't think of the name of it at the time.

**Comment by NathanLovato** [comment]
Sure, gotcha!
