### ISSUE TITLE
`Expected "(" after the identifier` explanation missing possible cause

### ISSUE THREAD

**Issue by AimVaguely** [GDQuest/learn-gdscript#255]
**Issue description:**
The explanation only says that this can happen if you put the keyword in the wrong place or are missing the name, it doesn't cover the potential problem of writing something like `func draw_square:` and forgetting the parentheses `()`. This is interesting because the raw error talks about this possible cause, but your cleaner explanation doesn't. This lack of explanation for this possible cause is in both "Why this happens" and "How to fix this".

This was discovered in [lesson 5 - A function to draw squares](https://gdquest.github.io/learn-gdscript/#course/lesson-5-your-first-function/practice-QiGjB7tK.tres).

An easy way to bring this up is to go to the previously mentioned practice lesson, click solution and remove the parentheses in the function name, after pressing run it will give the error.

**Comment by NathanLovato** [comment]
It's because we categorize similar errors. We'll add a mention for that though, it's a good thing to specify.
