### ISSUE TITLE
Runnable code doesn't reflect changes in editable block in lesson 8

### ISSUE THREAD

**Issue by AimVaguely** [GDQuest/learn-gdscript#257]
**Describe the bug**
In lesson 8 under "Defining a variable" if you change the value in `var health = 100` to `var health = 120` or even `var health = 'aaaaa'` and run the runnable code directly after it, it always outputs `100`. I have a feeling like this text box is not meant to be modifiable, so that might be what this bug is about instead.

**To Reproduce**
Steps to reproduce the bug:
1. Go to [lesson 8](https://gdquest.github.io/learn-gdscript/#course/lesson-8-defining-variables/lesson.tres)
2. Scroll down to "Defining a variable" subtitle
3. Click in text box that says `var health = 100`
4. Change value to `var health = 'aaaaaa'`
5. Click `Run` button on runnable code block that says `print(health)`
6. Output on left says `100`

**Expected behavior**

Either:
1. Text box is not modifiable, so you can't change the `health` value from `100`
2. The output of runnable code block matches the change value for `health`, even after the user changes it

**Information about your device (please complete the following information):**
 - Operating System: Linux x64 (manjaro)
 - Browser: Firefox 96.0.3 (64-bit)

**Additional context**
It is pretty clear that both of those contexts refer to different variables, but based on the text where you say `After defining your variable, you can access its value by writing the variable's name` it sounds like it is the same variable, and might cause confusion on why it is not reflecting that. In the following text and other runnable code block, it also demonstrates that the variable is carried across text boxes, even though this bug contradicts that. I personally think that I was not meant to modify the code in that text block, but I can, and therefore I did, and other people might assume that you are meant to be able to do that.

**Comment by NathanLovato** [comment]
Definitely, those shouldn't be editable. That's fixed now
