### ISSUE TITLE
Unclear error message when using quoted number in lesson 8

### ISSUE THREAD

**Issue by AimVaguely** [GDQuest/learn-gdscript#258]
**Describe the bug**
In [lesson 8 practice](https://gdquest.github.io/learn-gdscript/#course/lesson-8-defining-variables/practice-lkGx0c7D.tres) if you enter `var health = "100"` the error message in unclear

**To Reproduce**
Steps to reproduce the bug:
1. Go to [lesson 8 practice](https://gdquest.github.io/learn-gdscript/#course/lesson-8-defining-variables/practice-lkGx0c7D.tres)
2. Enter `var health = "100"` into text box
3. Press run

**Observed behaviour**
The error it gives is `ERROR Health variable's values is 100; It should be 100`. This error seemingly makes no sense, and I imagine a though process along the line of "You are saying it should be 100, but it is 100, so why are you telling me it is wrong then?" might happen.

**Expected behaviour**
It should either:
- give error `ERROR Health variable's values is "100"; It should be 100` or something similar to clearly state that it is a quote, not a number
- Inform user that values in quotation marks is not the same thing as a value without though some other means (see more info in additional context)

**Information about your device (please complete the following information):**
 - Operating System: Linux x64 (Manjaro)
 - Browser: Firefox 96.0.3 (64-bit)

**Additional context**
This might not be a real problem for someone learning to program, they might just not think to put quotation marks around it (you did show doing this previously, so it might be possible) I did this because I was curious how the error looked if I did so, and it looks like it might cause confusion, so I reported it. If no testers that are in the intended target audience (complete beginners to programming) then this might not be worth solving. I have a feeling this is something to do with how Godot output the message, and if it is, then there might need to be a special case with an extra error message to explain why the error message seemingly makes no sense.

**Comment by NathanLovato** [comment]
I don't think that's a problem. It seems you're not a beginner and you were pushing the app's error checking.

What we need here are actual things people in the target audience do. At this stage, they haven't even learned about strings, so that shouldn't be a problem.

If beginners start to do things like those, then we should probably add some general type-checking mechanism. For this one, I'll try to leverage type hints perhaps, that should be enough.

**Comment by AimVaguely** [comment]
I don't think this being a problem for a beginner is an impossibility. I am an experienced programmer but a beginner with Godot and GDScript, but that fact doesn't really effect this. I could totally image when I first started learning programming (at 13 if I remember correctly) I could have stumbled into this though (I was not a smart kid). If you think that it wouldn't be a difficulty for the intended audience, then don't bother with it. I was just reporting it because I thought it might be a problem, but I wouldn't really know.

**Comment by NathanLovato** [comment]
As I mentioned above, I'll try to use strong typing to provide better errors in case of using the wrong value type.

**Comment by AimVaguely** [comment]
That makes sense. I misunderstood what you meant by what you said.

**Comment by NathanLovato** [comment]
Using strong typing didn't work - it actually triggers the error on the comparison in the test code, so I went with a different approach, but now there'll be a clearer error message and we can reuse this in different exercises.

**Comment by AimVaguely** [comment]
While messing with it when I found this, I did try `100.0` and it said it was correct, based on the code in 317928f (the commit that closed this) that was unintended as well.

Disclaimer: I don't know GDScript, I only read that code as someone that knows C++, C# and some python, so I might be wrong on what I think it was doing.

**Comment by NathanLovato** [comment]
Did you try online? Because the change isn't live instantly, it's only when we make a new release.

**Comment by AimVaguely** [comment]
I didn't try the new version. I was talking about when I opened this issue, I tried `100.0` and it said it was correct. This new code looks like it changes that, therefore I am assuming that was a bug. I am just sort of reporting a bug that is(was) fixed by proxy.

**Comment by NathanLovato** [comment]
Ah no, it'll still say 100.0 is incorrect. But it'll now say you gave a decimal number while we expect a whole number.
