### ISSUE TITLE
ExampleRotateSprite.tscn in Lesson 3 doesn't show

### ISSUE THREAD

**Issue by johnnygossdev** [GDQuest/learn-gdscript#260]
The scene doesn't open and is not shown in the lesson because the file is corrupted.

![image](https://user-images.githubusercontent.com/3285214/152538121-cc7a7edd-b676-4d2f-bd18-558751b280e5.png)

![image](https://user-images.githubusercontent.com/3285214/152538088-965bbec1-9c06-464f-9898-fb837b89c34b.png)

**Comment by pycbouh** [comment]
Oh, that must be the scene that I saw erring a week ago! Thanks for finding it and looking into.

**Comment by johnnygossdev** [comment]
All good! As I'm re-doing the robot scene, I remade it using that. PR to follow with these changes.
