### ISSUE TITLE
Make the reset button in the code editor reset the GameViewport’s scene

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#27]
The reset button only resets the code right now. A tester was clicking it expecting it to reset everything. Another possibility, instead of this task, would be to add a tooltip or clarify the button label (reset code instead of reset).

**Comment by pycbouh** [comment]
I've added the missing logic, but it's relying on the "reset" method existing in the scene. This is similar to how in-lesson examples work. So it's up to the practice creator to implement it properly. For example, turtle examples don't seem to fully reset the camera, but maybe that's okay. Some practices have no reset, e.g. "Making the robot upright" can be completed across multiple runs of the test code adjusting it little by little. Not sure if it was intended or not.

I'm also resetting the test checks with the reset button. Made sense to include it.
