### ISSUE TITLE
Visual content blocks that should be full size receive a scroll bar and clip text

### ISSUE THREAD

**Issue by mathmods** [GDQuest/learn-gdscript#273]
**Describe the bug**
Visual content blocks containing code receive a scroll bar and clips either top or bottom text (depending on scroll).
This scroll contains one extra empty line at the bottom (does not have any line number indicating it is an empty line).

**To Reproduce**
1. Go to https://gdquest.github.io/learn-gdscript/staging/#course/lesson-13-conditions/lesson.tres
    * or any other lesson with a code block.
2. Look at the first code block or scroll to Comparisons.

**Expected behavior**
Either:
1. No scroll bar, the code block forces it's maximum size to show all content
2. Only the largest code blocks get a scroll bar due to size, and no code blocks smaller than the forced size should have it.

**Screenshots**
Lesson 13 Comparisons with scroll bar at top. Clips lightly at the bottom line.
![image](https://user-images.githubusercontent.com/8986677/152661706-cd41ad9e-e73f-459c-a6f5-f67a0f8c75ed.png)

Lesson 13 Comparisons with scroll bar at bottom. Clips an entire line from the top.
![image](https://user-images.githubusercontent.com/8986677/152661714-450b956b-eea4-45a9-b833-fb4c91895c8f.png)

Lesson 6 at the top with scroll bar at top. Clips nothing.
![image](https://user-images.githubusercontent.com/8986677/152661801-b7c7ece5-593a-4524-b636-8acf589c97df.png)

Lesson 6  at the top with scroll bar at bottom. Clips the first line and has an unnaturally large gap at the bottom.
![image](https://user-images.githubusercontent.com/8986677/152661843-489271c5-4e24-46fe-9b91-d350ad9e817e.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows 10 20H2
 - Browser: Chrome (latest release)

**Additional context**
Also mildly annoying when scrolling through due to them both catching the input, but also not stopping the main scroll bar when using the scroll wheel on them.

**Comment by johnnygossdev** [comment]
The bounds of these elements seems to be slightly smaller when deployed to HTML, which makes it tricky to assess what minimum size they should be when creating them.

It could be to do with RichTextLabel heights being unreliable. I'm sure I've seen some issues relating to that.

**Comment by pycbouh** [comment]
> RichTextLabel

Those are `TextEdit`s though, no? And text edits do always have additional line added at the bottom, per some convention. So at least that should be accounted for.

Another issue is that those don't correctly adjust to the font size changes, which can also produce scrollbars. There seems to be at least one issue with `TextEdit` itself where it correctly computes, and immediately pollutes its wrapping information (see https://github.com/GDQuest/learn-gdscript/issues/99). If we find a reliable way for it to update with font size, I think this may also be fixed along the way.

**Comment by NathanLovato** [comment]
Yeah the wrapping is the biggest difficulty with increasing the font size. I think we'd need some API to get the content's height, taking wrapping into account. The way we scale them now is simply increasing the UILesson's column width and I think TextEdit nodes' height proportionally to the font. But that's not always enough.

**Comment by johnnygossdev** [comment]
> > RichTextLabel
> 
> Those are `TextEdit`s though, no? 

Ah yes my mistake. That'll teach me to reply after just waking up.

**Comment by NathanLovato** [comment]
For now we'll have to manually increase the code examples' minimum height. We don't have a way to calculate how tall the example should be. So when you see this issue in a specific lesson, please let us know. I fixed it for lesson 13
