### ISSUE TITLE
Reuse loaded screens in UINavigator

### ISSUE THREAD

**Issue by mathmods** [GDQuest/learn-gdscript#275]
**Is your feature request related to a problem? Please describe.**
When using the UINavigator with practices and breadcrumbs, an entirely new page is loaded onto the screen stack. This makes practice navigation unwieldy as moving back and forth between practices will load new ones onto the stack.

**Describe the solution you'd like**
When navigating to a new screen check the screen stack for the same resource. If it is found use a reference to that one instead of an entirely new instance.

**Describe alternatives you've considered**
Tell the students that the practice loaded from source and that you can get to the practice through the back button.

**Comment by pycbouh** [comment]
This is done on purpose and similar to how navigation works between pages in a web browser. We can reconsider it if users express being confused by it, but at this point this was a conscious decision.
