### ISSUE TITLE
Connection Timed Out

### ISSUE THREAD

**Issue by LennyPhoenix** [GDQuest/learn-gdscript#279]
**Describe the bug**
Every practice screen yields a "Connection timed out" error when running the code.
The "Validating your code" screen will take a few seconds before disappearing.
Interestingly, the program seems to run correctly following the error, in the first practice screen "Welcome" is printed to console correctly.

**To Reproduce**
Steps to reproduce the bug:
1. Go to [Lesson 1 Practice](https://gdquest.github.io/learn-gdscript/#course/lesson-1-what-code-is-like/practice-55916.tres)
2. Run the program

**Expected behavior**
No "Connection timed out" error.

**Screenshots**
![image](https://user-images.githubusercontent.com/57148878/152879670-fad10c91-e478-4e99-b76a-9b2ce21d2ca4.png)

**Information about your device (please complete the following information):**
 - Operating System: Endeavour OS (Arch Linux distro)
 - Browser: Firefox 96.0.3

**Additional context**
N/A

**Comment by NathanLovato** [comment]
The server was down. I just restarted it manually.
