### ISSUE TITLE
 Lesson 11: Moving in a circle using delta. pass at the end of a method causes the code to be evaluated as false.

### ISSUE THREAD

**Issue by GuvnerGames** [GDQuest/learn-gdscript#280]
**Issue description:**

If you leave the pass at the end of the method the Check tells me "Moving in a circle is time dependent" fails

**Comment by mathmods** [comment]
Already fixed on the staging (non-stable) version. 
Seems to be the same bug that affected #230. (Same error message - "Something is wrong here.")

You can try the practice on the staging version here: https://gdquest.github.io/learn-gdscript/staging/#course/lesson-11-time-delta/practice-x0c7DDiz.tres
Or generally the staging version: https://gdquest.github.io/learn-gdscript/staging/

**Comment by NathanLovato** [comment]
Thanks!
