### ISSUE TITLE
Lesson 4: Hitting the reset button moves the turtle instead of reseting.

### ISSUE THREAD

**Issue by Razoric480** [GDQuest/learn-gdscript#281]
**Describe the bug**
Hitting the reset button moves the turtle and the line out of bounds and does not reset.

**To Reproduce**
Steps to reproduce the bug:
1. Go to Lesson 4's explanation
2. Run the first draw a rectangle turtle
3. Hit reset button

**Expected behavior**
It should reset back to initial state, but it just moves its origin

**Screenshots**
![image](https://user-images.githubusercontent.com/2823241/152903645-fe641b22-6493-456d-8b05-8f5ed9d17871.png)
![image](https://user-images.githubusercontent.com/2823241/152903655-08a7a1d4-d677-4fdb-a855-ba4352c593c0.png)

**Information about your device (please complete the following information):**
 - Windows 11
 - Brave

**Additional context**
Submitted by 🤖Isaias🤖 on discord

**Comment by NathanLovato** [comment]
We need to test reports with the staging version of the app. People tend to report issues in the stable release. This is already fixed
