### ISSUE TITLE
Connecting to the script verifier server

### ISSUE THREAD

**Issue by RamenFlavors** [GDQuest/learn-gdscript#282]
**Describe the bug**
When I make an error, it would say I have to connect to the server. Even though I have a stable connection and I turned off my ad blocker. So I think it might be a bug

**To Reproduce**
Steps to reproduce the bug:
1.Make error
2. Don't see help

**Expected behavior**
It should make it so why I made an error.

**Comment by NathanLovato** [comment]
The server was down, I restarted it moments ago.
