### ISSUE TITLE
Add example(s) of what Vector2 does to lesson 16

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#285]
The vector lesson is nice but it could use one or more examples of how vectors work and why the student should care about them.

I added a mention of that when reviewing #251 but something more visual would be welcome.

@johnnygossdev had a demo in mind that depends on #245. Similarly, I was thinking about a follow steering behavior, which illustrates how, with 3 lines of code, you can make an AI follow a target. It's easy with vectors, really complicated without them.

Depends on #251

**Comment by NathanLovato** [comment]
@johnnygossdev would you like to tackle this one or should I do it?

**Comment by johnnygossdev** [comment]
@NathanLovato By all means, I'm working on 17 + 18 right now
