### ISSUE TITLE
Lesson 4 : start with a simpler practice

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#30]
Creating a square from the get-go in lesson 4 is a bit difficult. We should consider a simpler practice first : creating half a square with a call to move_forward(), turn_right(), and move_forward().

This would illustrate how turn_right() works and make it clear to the student.

**Comment by johnnygossdev** [comment]
fixed via ee42998f01078dfb54c800c94097c13d7b9ec14c
