### ISSUE TITLE
Lesson 19: Creating arrays

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#305]
Solves: storing a list of related items, like a list of coordinates, items in the player's inventory, characters in the player's party, and more.

This first lesson focuses on creating an array to store some important data. For example, items in a player's inventory.

The range function we saw in the previous lesson created an array of numbers. For example, calling `range(3)` produces the value `[0, 1, 2]`. It's an array of three numbers starting from zero.

The for loop takes this array and loops over the numbers sequentially.

Arrays are a core data type in computer programs just like numbers. An array is a list of things. Those things can be whole numbers, decimal numbers, 2D vectors, or anything else.

**Comment by NathanLovato** [comment]
@johnnygossdev I don't remember if you wanted to tackle this or up to 18? You can assign yourself if you're looking to do this one, otherwise, I'll finish my tasks and start working from this.

**Comment by johnnygossdev** [comment]
Sure I can take this one too.
