### ISSUE TITLE
Lesson 22: Adding and removing elements in arrays

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#307]

**Comment by NathanLovato** [comment]
@johnnygossdev just so you know I think this will become 2 lessons: after drafting it, I feel accessing elements with [0] takes quite a bit of explanation and requires focused practice - adding append and pop_back to it makes it too much to take on at once.

**Comment by johnnygossdev** [comment]
Thanks for the heads up!
