### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by Simplifier** [GDQuest/learn-gdscript#311]
Will your code editor have the autocomplete feature?

**Comment by NathanLovato** [comment]
No, it won't. For this learning app, it isn't a feature we want - typing everything can be good to build some of that muscle memory and get used to getting the syntax right.

However, we have plans for other apps for audiences other than absolute beginners, and for those, we'd want to look into auto-completion, yes.

**Comment by Simplifier** [comment]
Some beginners (kids especially) can be bad at typing. And having to type each symbol may be nothing more than additional hurdle for them

**Comment by NathanLovato** [comment]
We'll see through practice if people in the target audience (13+, programming beginners) have trouble with the act of typing specifically. As with everything in this app, we need to get a lot of feedback from people in the target audience. If typing is an issue for a substantial number of those persons, we should definitely look into making it easier.

We had a few ideas regarding that on top of auto-completion (which we did consider) like having "fill the gaps" practice widgets and other mouse-friendly learning widgets, or practices where you have to read code and guess the output.

Unfortunately, right now, it's a bit beyond what we can do for v1. We'll have to push this and consider it again for a v2.

I'd like to take the app to a whole classroom or nonprofit and see how a whole group of people do with it sometime. That would surely raise a good deal of issues. Hopefully in some months if the situation stabilizes around here.
