### ISSUE TITLE
Add binary compilation targets to CI

### ISSUE THREAD

**Issue by Xananax** [GDQuest/learn-gdscript#316]
This would allow us to offer an alternative to the web export for people who prefer using an app.

We would create Windows, Linux, and OSX exports, and automatically save artifacts as downloadable assets on Github.

Additional features:

- [ ] also save staging binaries
- [ ] auto-add latest links to the webpage so people using the web build can get a "download desktop app" link at the bottom left
- [ ] upload builds to itch?

**Comment by NathanLovato** [comment]
Closing as the executables are on itch now: https://gdquest.itch.io/learn-godot-gdscript
