### ISSUE TITLE
DGQuest Boy solution animation not working correctly in lesson 7 practice 2

### ISSUE THREAD

**Issue by mo-moxi-gd** [GDQuest/learn-gdscript#317]
**Issue description:**
A clear and concise description of what the issue is.
The GDQuest Boy animation on this page draws the wrong way: left not right.

https://gdquest.github.io/learn-gdscript/staging/#course/lesson-7-member-variables/practice-x0c7DDiz.tres

**Comment by NathanLovato** [comment]
The bug here is that changing the turtle's position offsets the camera, so it appears the turtle goes to the left but I think it's the camera jumping to the bottom right.
