### ISSUE TITLE
Lesson 9: pass was not explained before

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#322]
The pass keyword appears in the first practice but we didn't explain it so far

**Comment by NathanLovato** [comment]
Actually, I removed the `pass` in a recent update, so this is not applicable anymore.

**Comment by NathanLovato** [comment]
Ping @johnnygossdev, just so you know, I've been changing starting code in practices to remove the need to explain pass. As there's no real-time linter, it's not as necessary as when coding in GDScript.

So the starting code for some practices is now like this:

![image](https://user-images.githubusercontent.com/12694995/154243858-48a7c681-99c8-4604-8295-5d80cce2ce8a.png)

If you're fine with it, we can stick that way.

**Comment by johnnygossdev** [comment]
Thanks for the heads up, sounds good.
