### ISSUE TITLE
Typing Paranthesis and moving backwards one step with cursor-key will loose all things typed into editor (happens only in staging version)

### ISSUE THREAD

**Issue by bir-thg** [GDQuest/learn-gdscript#330]
[**Describe the bug**]
For instance [https://gdquest.github.io/learn-gdscript/staging/#course/lesson-6-multiple-function-parameters/practice-lkGx0c7D.tres](url) is called.

After following the steps below, all changes in the editor are lost and the course index is shown.

**To Reproduce**
Steps to reproduce the bug:
1. Go for instance to [https://gdquest.github.io/learn-gdscript/staging/#course/lesson-6-multiple-function-parameters/practice-lkGx0c7D.tres](url)
2. Type into the editor:
func functionname()

3. Go backwards one step with the cursor-key-left
4. See error happens: the course index is shown, the content of the editor is lost.

**Expected behavior**
This error happens every time you go over a closing paranthesis while you are trying to fill in for instance parameters. This happens only with the staging version.

**Screenshots**
![course index shown](https://user-images.githubusercontent.com/62995369/154288549-35292e18-cd37-44db-994b-6f17a94bc16b.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows
 - Browser chrome

**Additional context**

**Comment by NathanLovato** [comment]
There's just a bug with the CI, it's stuck building a commit from over 1 month ago, see #328
