### ISSUE TITLE
Left arrow key in the code panel brings back to lesson content

### ISSUE THREAD

**Issue by Faless** [GDQuest/learn-gdscript#331]
**Describe the bug**
Pressing the Left Arrow key in the keyboard while editing code during practice sessions brings back to the lesson instead of moving the cursor.

**To Reproduce**
Steps to reproduce the bug:
1. Go to the any "Practice" session
2. Click in the code panel.
3. Press the "Left Arrow" key on your keyboard
4. Instead of moving the cursor left, the UI goes back to the Lesson content.

**Expected behavior**
The blinking cursor in the code panel should move left.

**Screenshots**

https://user-images.githubusercontent.com/1687918/154451005-28e9bc41-a865-4d08-9755-076f1bdd7bf9.mp4

**Information about your device (please complete the following information):**
 - Operating System: Linux/Ubuntu
 - Browser: Firefox 97

**Comment by NathanLovato** [comment]
This is an outdated version you tested. The CI has an issue and reverted to an old commit.  See #328

**Comment by NathanLovato** [comment]
At the moment, to test the latest version of the app, you can download the project and import it in Godot - it will work. Otherwise you have recent binaries here: https://gdquest.itch.io/learn-godot-gdscript
