### ISSUE TITLE
UX: Primary action button should be consistently on the right

### ISSUE THREAD

**Issue by luminarious** [GDQuest/learn-gdscript#332]
In the very first lesson screen already, [Reset][Run] has primary action on the right, while [Submit][Skip] has primary action on the left. In most guidelines, primary action is recommended on the right.

Side note: even better if the primary and secondary actions have different visual styles. For example, the primary button is filled, while the secondary is only outlined.

**Comment by NathanLovato** [comment]
The issue is to swap the submit and skip button in quizzes for consistency, right? Are there any other instances?

**Comment by NathanLovato** [comment]
@pycbouh what do you think regarding having a particular style or color for the quizzes' submit button, and perhaps the run code button in code examples?

There's a little visual inconsistency in the app right now, I didn't unify the button styles after re-adding the big outline buttons. The big outlines generally read well I think. But should we use them more inside lessons?

**Comment by pycbouh** [comment]
@NathanLovato 

[Quizzes](https://user-images.githubusercontent.com/11782833/154673218-607775df-0967-44b8-968e-3e223074a988.png) are probably fine, but maybe could steal the white outline on the "Submit" button from the "Continue" button in the ["Well Done" popup](https://user-images.githubusercontent.com/11782833/154673387-73c215a0-f5f9-4b90-a28a-b36e65bd5072.png). And quiz "Skip" button lacks contrast, so probably can be made the same as "Stay" button here?

Code examples are problematic. The action button definitely needs some more accent on it, and "Reset" needs to be less visible. Specifically, the fact that we write the name of the function, which starts with a lower case letter, makes the "Reset" button look more significant.

![godot windows opt tools 64_2022-02-18_14-17-57](https://user-images.githubusercontent.com/11782833/154674052-49526e12-899c-4b9c-ae5a-69c28a613616.png)

Also on the welcome screen the [button blends with the background](https://user-images.githubusercontent.com/11782833/154674074-d9deedd3-dfd2-4389-bd73-dba300538e88.png).
