### ISSUE TITLE
Using left cursors key in code editor returns the app to previous lesson

### ISSUE THREAD

**Issue by ChrisWhatever1980** [GDQuest/learn-gdscript#334]
**Describe the bug**
When pressing left cursor key in the code editor, the app returns to the previous lesson.

**To Reproduce**
Steps to reproduce the bug:

**Expected behavior**
I expected the cursor left key to work like the other cursor keys when the code editor window has the focus. 

**Information about your device (please complete the following information):**
 - Windows
 - Chrome

**Comment by NathanLovato** [comment]
It's already fixed, a bug was causing the published version of the app to be very outdated, see #328 for more information. That bug is also fixed.
