### ISSUE TITLE
UI/UX Navigation

### ISSUE THREAD

**Issue by LocoUnPocoNadaMas** [GDQuest/learn-gdscript#336]
**Is your feature request related to a problem? Please describe.**
There is no back or next button.

**Describe the solution you'd like**
Bottom buttons on both sides, left (back) and right (next).

**Describe alternatives you've considered**
Maybe it can be green.

**Additional context**
All apps need a back button.

**Comment by NathanLovato** [comment]
There's a back button already. If you tried the staging version of the app, there was a bug that caused a very outdated version to appear, see #328

It's now fixed and back navigation is available. 

![image](https://user-images.githubusercontent.com/12694995/154477403-72730046-0d4b-402e-aa97-963653f4bc6e.png)

It's mapped to Alt Left. We don't have a window showing shortcuts yet but it's also planned: #29 

However, we won't support forward navigation. Only back navigation for now.

**Comment by LocoUnPocoNadaMas** [comment]
now I can see it (so smaller), but is invisible al first of chapter
![image](https://user-images.githubusercontent.com/37430832/154484021-7a857244-5a54-4b00-a5b4-f9cf7c5ed73e.png)
![image](https://user-images.githubusercontent.com/37430832/154484100-612f4407-0bc7-4870-b981-04159f374411.png)
I can't go back to the previous chapter

**Comment by pycbouh** [comment]
> I can't go back to the previous chapter

It's disabled because there is no history. You can only navigate back within one lesson (and its practices). If you want to open another lesson, you need to use the course index (the button next to the back button in your screenshots).

**Comment by LocoUnPocoNadaMas** [comment]
But in a book you don't need to read the index to go back to the previous chapter, I get your point but it's not good for reading.

**Comment by NathanLovato** [comment]
On a reader you do need to use the index or bookmarks to navigate, this is the closest kind of device to a web app like this.

In any case, we won't provide more back and forward navigation for now, it's a matter of budget. We can't afford that much work for an improvement that would be invisible to most users.
