### ISSUE TITLE
Make runnable example and quiz buttons more visible and contrasted

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#338]
Based on feedback in #332

Comments by @pycbouh:

[Quizzes](https://user-images.githubusercontent.com/11782833/154673218-607775df-0967-44b8-968e-3e223074a988.png) are probably fine, but maybe could steal the white outline on the "Submit" button from the "Continue" button in the ["Well Done" popup](https://user-images.githubusercontent.com/11782833/154673387-73c215a0-f5f9-4b90-a28a-b36e65bd5072.png). And quiz "Skip" button lacks contrast, so probably can be made the same as "Stay" button here?

Code examples are problematic. The action button definitely needs some more accent on it, and "Reset" needs to be less visible. Specifically, the fact that we write the name of the function, which starts with a lower case letter, makes the "Reset" button look more significant.

![godot windows opt tools 64_2022-02-18_14-17-57](https://user-images.githubusercontent.com/11782833/154674052-49526e12-899c-4b9c-ae5a-69c28a613616.png)

Also on the welcome screen the [button blends with the background](https://user-images.githubusercontent.com/11782833/154674074-d9deedd3-dfd2-4389-bd73-dba300538e88.png).

_Originally posted by @pycbouh in https://github.com/GDQuest/learn-gdscript/issues/332#issuecomment-1044371390_

**Comment by NathanLovato** [comment]
And we should probably change the Practice button with the thin outline at the bottom of lessons too? It looks different from all other buttons in the app.

Also note for self: clean up unused styles after making these changes.

**Comment by razcore-rad** [comment]
I was thinking of using here the same style as the ones used for quizzes, but for some reason, the pressed stylebox state is overridden by the focus stylebox (white border). @NathanLovato, do you know why that might happen?
![image](https://user-images.githubusercontent.com/1177508/156218020-3afdcff5-17e4-4cbc-8300-ea0f7d8d2fa6.png)

**Comment by NathanLovato** [comment]
I'm not sure why that's happening, could you push to a branch or open a pr? I'd need to check it in Godot. That is, if you want me to look into it

**Comment by razcore-rad** [comment]
@NathanLovato yea sure, I was hoping maybe you know what influences the buttons for a quick fix. I made a branch update-runnable-buttons.

**Comment by NathanLovato** [comment]
Ah got it after a second read: it's because when you press the button, it gets in focus, so it gets the focus style on the background (white outline), and that takes precedence over the pressed style, at least for the background. I don't think it should but well, in Godot, it does.

One option is to remove the focus style on those buttons, but that's not great for keyboard nav. Another is to make the focus style the same as pressed.

**Comment by razcore-rad** [comment]
Wellllll... bug may be a strong word :))
![image](https://user-images.githubusercontent.com/1177508/156304219-e0d4d7ae-bb8e-49f8-990d-8f97513620b0.png)

**Comment by razcore-rad** [comment]
Yes and that's exactly what I'll do, the focus will be a super thin border over everything else. It'll turn out fine
