### ISSUE TITLE
Wrong zoom button placement in chrome windows

### ISSUE THREAD

**Issue by Xananax** [GDQuest/learn-gdscript#340]

**Comment by Xananax** [comment]
@pycbouh can you confirm the bug is fixed on [staging](https://gdquest.github.io/learn-gdscript/staging/)?

If yes, please close the issue

**Comment by pycbouh** [comment]
Not sure. It seems to be placed correctly, but I can't launch the app properly.

![chrome_2022-02-24_14-44-03](https://user-images.githubusercontent.com/11782833/155517985-303e98e4-8c94-41ea-bb08-518114350bcf.png)
![chrome_2022-02-24_14-44-18](https://user-images.githubusercontent.com/11782833/155517993-81c6ceaa-29bb-49e0-a79c-2bd90068f1ab.png)

**Comment by Xananax** [comment]
Yea, I bugged the release version, didn't notice because the debug was running fine in local web builds. Pushed another build with the fix to `staging`. Can you check again?

**Comment by pycbouh** [comment]
Sure. Seems to be in working order, both the app and the button's placement.
