### ISSUE TITLE
Scrolling on Windows seems to be sluggish in recent commits

### ISSUE THREAD

**Issue by pycbouh** [GDQuest/learn-gdscript#341]
**Describe the bug**
Scrolling with a mouse on Windows desktop has recently become very sluggish (see the clip below). Both the distance and the lack of easing when stopping makes it much harder to scroll through the content than before. Note, that when the smooth scroll container was added, it was fine. Something has changed since then.

Changing the scroll sensitivity from default (mid) to the highest value is noticeable, but is still worse than it was before. On web (Chrome), in the current staging version, it is less sluggish with the default value, and about as smooth as it's supposed to be with the highest value.

**To Reproduce**
The issue becomes apparent in any lesson while reading its content.

**Expected behavior**
Scrolling with mouse should feel smoother, in line with other applications.

**Screenshots**

This is the default scroll sensitivity and me trying to scroll with the mouse as fast as possible.

https://user-images.githubusercontent.com/11782833/154688212-8b627330-6b63-47cf-a484-71b8c928ffd5.mp4

**Information about your device (please complete the following information):**
Windows, desktop and to a degree on web, Chrome.

**Additional context**
N/a

**Comment by NathanLovato** [comment]
I don't think it's windows specifically, I don't get the issue on Windows desktop. I'm unsure about the cause, but we'll look into this.

If you have the time, one thing that'd be helpful is seeing from which commit this happened. As you said you used the app with smooth scrolling before and didn't have this issue, right?

**Comment by pycbouh** [comment]
> I don't think it's windows specifically, I don't get the issue on Windows desktop. I'm unsure about the cause, but we'll look into this.

Yes, as we assessed in the chat, this is probably about something else, like screen pixel density/system scaling factor.

> If you have the time, one thing that'd be helpful is seeing from which commit this happened. As you said you used the app with smooth scrolling before and didn't have this issue, right?

Yes, of course, I'll try bisecting on Monday.

**Comment by pycbouh** [comment]
It is, as you suspected, the throttling that caused this for me. Commit 80eead573941e009159d58277f37d83517a9d6f4. Not sure if the videos would do it justice but here's before and after:

https://user-images.githubusercontent.com/11782833/154972320-5b47fccb-a575-47cb-b8d6-1de5652c63e5.mp4


https://user-images.githubusercontent.com/11782833/154972330-84772a1d-d9d5-4970-adaf-5d8544990d04.mp4

**Comment by NathanLovato** [comment]
Okay it should be straightforward then, we'll only keep throttling on web browsers, that should do it
