### ISSUE TITLE
Can't connect to server when playing the HTML5 version on Itch.io

### ISSUE THREAD

**Issue by KesaiArts01** [GDQuest/learn-gdscript#342]
**Describe the bug**
I'm playing from a browser (itch.io) and this app says that I have to deactivate AdBlocker/ScriptBlocker. But my AdBlocker is deactivated.

**Screenshots**
![image](https://user-images.githubusercontent.com/51276652/154802150-9223c68b-b372-4078-b069-48841709d994.png)
![image](https://user-images.githubusercontent.com/51276652/154802180-4a53cb22-4eae-4a23-8c8b-0363a2979c1f.png)

**Information about your device (please complete the following information):**
Microsoft Edge

**Log File**
[gdquest-1645275815076.log](https://github.com/GDQuest/learn-gdscript/files/8102207/gdquest-1645275815076.log)

**Comment by NathanLovato** [comment]
Yes, for now, on itch, you can't connect to the server. It's a known issue, my teammate who manages the server had to take a leave, we'll look into this when he's back.

**Comment by NathanLovato** [comment]
Please use this version if you want to play in the browser: https://gdquest.github.io/learn-gdscript/staging/

We set up the itch page so people can download the desktop version. The HTML5 view is mostly so people can quickly try before downloading. But we'll fix the issue soon.

**Comment by Xananax** [comment]
Fixed, the itch build now connects. The actual domain to whitelist is `https://v6p9d9t4.ssl.hwcdn.net` and not `itch.io`, but that' was not documented anywhere.
