### ISSUE TITLE
Ask for confirmation again before removing all progress

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#347]
**Is your feature request related to a problem? Please describe.**

As a safety measure, it might be helpful to add a confirmation before all progress is removed.

**Describe the solution you'd like**

Add a confirmation pop-up before removing all progress.
When pressing the `Confirm` button on the `Confirm Resetting Progress` pop-up.

Maybe it could say something like:

All progress will be lost!
`I Understand`  `Cancel`

**Notes**

The current pop-up does say "This cannot be undone".

But it might be safer to ask a second time, to make sure.

**Comment by pycbouh** [comment]
Let me get this straight, you want to add a confirmation popup for a confirmation popup?

**Comment by duianto** [comment]
Some applications use a second confirmation to make sure that a destructive operation is intended.

It came up because of the button color confusion:
Confirm Resetting Progress, confusing button colors #346

If/when that is fixed, then this might be overkill.

**Comment by pycbouh** [comment]
> Some applications use a second confirmation to make sure that a destructive operation is intended.

Course progress is not really system critical to have obnoxious confirmations after confirmations.

> It came up because of the button color confusion:

The button for that popup was originally red to indicate that it's a dangerous operation. This should probably be restored.
