### ISSUE TITLE
character art clips through border at lesson 3

### ISSUE THREAD

**Issue by BloatedloafYT** [GDQuest/learn-gdscript#353]
character art clips through border at lesson 3

1. Go to lesson 3
2. Click on the interactive segment under the show()\hide() quiz
3. click it 4 times

**Expected behavior**
i expected for it to wrap without clipping

**Screenshots**

![Screenshot 2022-02-22 095033](https://user-images.githubusercontent.com/80492574/155145688-49e1add3-debe-46ff-ae78-cefd5d78c51c.png)

**Information about your device (please complete the following information):**
 - Operating System: [Windows]
 - Browser: [Chrome]

**Additional context**
maybe add a mask to the border

**Comment by mathmods** [comment]
I personally don't see this as a bug where it should have wrapped around. Could perhaps add a note below it explaining why it doesn't stop moving/wrap after reaching the corner. (The example code doesn't specify limits nor any wrapping functionality). 

One other way would be to add a boundary that clips content to the example, making it physically dissapear little by little once it reaches the corner. (This would be the case if you consider the window to be it's own screen and not a part of the app).

**Comment by NathanLovato** [comment]
There's code that should make the character wrap, I think I know why it's not anymore: the virtual function that provided its rect size is probably gone since we replaced the many variations of the robot with one scene.
