### ISSUE TITLE
Lesson 6 practice 1 is too difficult

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#36]
A tester really struggled with this practice. Like for lesson 4, we should start with a simpler practice as students first get to use their own function parameters here. See #30 for more information

**Comment by NathanLovato** [comment]
@johnnygossdev is this a task you could tackle?

**Comment by generrosity** [comment]
I stepped away from my computer and forgot the names of the two functions needed to complete the example - hint 3 includes the movement function but not the rotation one.  Im not sure if this is something that could be in the goal or checks reminding you have those functions 'availible'

**Comment by pycbouh** [comment]
We have documentation section in the left corner for that purpose. I've not seen the lesson recently myself, but that's where the names and the descriptions of available functions should be (or should be added).

**Comment by Xananax** [comment]
No, indeed the documentation is missing for that exercise

**Comment by generrosity** [comment]
apologies - how often does the production site get updated with changes?

**Comment by NathanLovato** [comment]
@Xananax this issue is that we need a new practice, Johnny is taking care of it. Did you close the wrong issue?

**Comment by Xananax** [comment]
Oops, yes sorry

**Comment by generrosity** [comment]
'Doc' section looks great in "7b:DrawRectanglesAtDifferentLocations", just waiting on deploy for 6. I'll hold off on further comments - thanks 😅💚

**Comment by johnnygossdev** [comment]
Ah I wondered where this issue went! 😄 I'll do this today.
