### ISSUE TITLE
Lesson 12: Duplicates in checklist for exercises

### ISSUE THREAD

**Issue by SpeCter** [GDQuest/learn-gdscript#360]
In the checklist of lesson 12 you can find multiple duplicates of the same task:
![Screenshot 2022-02-25 010309](https://user-images.githubusercontent.com/7155894/155628063-4e73a428-dec5-477e-81fe-f6e006c459a9.png)

**Comment by NathanLovato** [comment]
This happens when changing the language, seems it's a bug linked with i18n.

**Comment by SpeCter** [comment]
Ah ok...that makes sense since I'm switching back an forth to reload language files.

**Comment by SpeCter** [comment]
You can also use the russian translation that is already there, the checks don't have a translation file or are not in the current translation files yet anyway.
On my end just opening any exercise , switching to another language will duplicate the first several times(seems to depend on the total amount of checks), maybe another one and add the real checks at the end like this:

Before switching:

- Check 1
- Check 2
- Check 3
- Check 4

After switching:
- Check 1
- Check 1
- Check 3
- Check 1
- Check 2
- Check 3
- Check 4

**Comment by NathanLovato** [comment]
Got it, it only happens when there are multiple checks. We'll look into it and fix it soon.

**Comment by razcore-rad** [comment]
closed via be85b64c814c65d50744a1fd509981ef979ffde1
