### ISSUE TITLE
App window is larger than my display on desktop platforms

### ISSUE THREAD

**Issue by EyeBallTank** [GDQuest/learn-gdscript#364]
**Describe the bug**
I just opened the Windows version after downloading it from Itch io and when i opened it, the program was on the left side of my screen covering most of it, while also having some things hidden on the left side of my screen.

**To Reproduce**
Basically, i just open the program and it showed up in an awkward position on my screen.

**Expected behavior**
A windowed view that would have been placed from the center, while being at a resolution to present nicely the contents inside the window.

**Screenshots**
![not the whole screen but you get the idea](https://user-images.githubusercontent.com/93493280/155903257-d81a3058-286e-4a0c-bea1-6782a36dbddf.PNG)

**Information about your device (please complete the following information):**
OS: Windows 10
Browser: Firefox
Monitor resolution: 1280x1024 (It's an HP 1740 model)

**Additional context**
If i set to FULLSCREEEN however, it doesn't look bad.
In fact, switching to that makes it seem like an easy way to ignore the problem.
I mean, it's not the worst issues a program could have but i will write this in case it could be fixed and if anyone else is having this issue.
If someone else already wrote something about this, do let me know if i am posting an already discovered issue.
Either way, i've slacked and been interrupted enough, i want to focus more on getting creative.

**Comment by NathanLovato** [comment]
I think it might be the display resolution that's below what we currently support. The app launches by default in a window of size 1920x1080. Changing that should help. Now we provide the desktop version we likely need desktop-specific settings.
