### ISSUE TITLE
Add resolution and window options to settings on desktop platforms

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#365]
We always start the app at a fixed resolution of 1920x1080, which causes issues on desktop, see #364.

We should probably provide some window options to let people choose if the app should start full-screen, windowed, or borderless, and let them choose their render resolution.

Also, to fix #364, we probably need to lower the default window resolution.

**Comment by razcore-rad** [comment]
With Jad clarifying yesterday that he isn't working on these desktop-related resolution issues I wanted to reiterate the idea. So this only affects how the app behaves on the desktop.

---
From Discord:

I can see the app used in windowed with the full-screen option we have now + bordered by default as it is. I'd only change the start resolution. We can either hard-code it by using the test width/height project options or we can pick a default size based on the user screen resolution. For example, after I set test width to 1080 & height to 600 I have this window which I can maximize, resize or enter full-screen with the button.

![image](https://user-images.githubusercontent.com/1177508/156516870-96a1ebc6-b6c0-4fab-a04f-2d051605e579.png)

Let me know what you think. The solution with fixed smaller test width/height doesn't require any new code.

**Comment by NathanLovato** [comment]
Isn't test width/height only when running the app in debug mode? Or does it also affect released binaries? If it does, sure, lowering the start resolution sounds good.

**Comment by razcore-rad** [comment]
It affects the release binary too, it's basically the start resolution.

**Comment by NathanLovato** [comment]
Please go ahead then. Feel free to pick a couple of issues at once too, otherwise, I'll likely be working on several today.

**Comment by NathanLovato** [comment]
@razcore-rad this task was about adding resolution options to the settings menu. Your commit only addresses #364

**Comment by NathanLovato** [comment]
You think we should drop this task entirely?
