### ISSUE TITLE
Lesson 16 2D Vectors: Typo of direction as 'directoin'

### ISSUE THREAD

**Issue by arathibiju** [GDQuest/learn-gdscript#366]
**Issue description:**
Typo in lesson 16 as shown below
![Lesson 16 Typo](https://user-images.githubusercontent.com/62319771/155956685-ee461b0c-7eeb-43f2-8493-d78ad78fa45e.jpg)

**Comment by NathanLovato** [comment]
Closed by ed47b2fc3393307c03cf16f330c109cf901f2f78
