### ISSUE TITLE
Lesson 17, two examples, increment before print in one, print before increment in the other

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#369]
**Issue description:**

In lesson 17:
https://gdquest.github.io/learn-gdscript/staging/#course/lesson-17-while-loops/lesson.tres

Under the heading: `Using while loops to repeat code`

The increment number statement: `number += 1`
and the print statement: `print(number)`
doesn't match in the two code examples.

In the first example, the increment statement comes before the print statement,
but in the second example, the print statement comes first.

![image](https://user-images.githubusercontent.com/13420573/155999493-fafed329-20e2-4366-8bb5-fbcabf22e972.png)

If the code in the first example would be tested, then it would output:
```
1
2
3
4
```
The second example outputs:
```
0
1
2
3
```

### A possible solution
Maybe the first example also should have the print statement before the increment statement.

**Comment by razcore-rad** [comment]
closed via eac9135
