### ISSUE TITLE
Lesson 17, exercise expects board size var name: `size`, but goal, hint, and docs say: `board_size`

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#378]
**Describe the bug**

In Lesson 17's practice exercise: `Moving To The End Of A Board`

The code editor, and the solution, expects the board size variable name: `size`

But the `Goal`, `Hint 3` and `Documentation` calls the variable: `board_size`

Using `board_size` in the code editor results in:
>ERROR The identifier "board_size" isn't declared in the current scope.

**To Reproduce**

Steps to reproduce the bug:
1. Go to:
https://gdquest.github.io/learn-gdscript/staging/#course/lesson-17-while-loops/practice-lkGx0c7D.tres
2. Click on the code editor
3. Replace the word `pass` on the second line, with:
```
	while cell.y < board_size.y - 1:
		cell.y += 1
```
4. Press the button: `Run`

**Observed behavior**

>ERROR The identifier "board_size" isn't declared in the current scope.
in PracticeBoardWhile at line 2, column 1

**Expected behavior**

The code should have been accepted as correct.

**Information about your device (please complete the following information):**
 - Operating System: Windows 10 21H1
 - Browser: Microsoft Edge 98.0.1108.56 (Official build) (64-bit) 

**Additional context**

Press the button: `Solution`
To see that it expects `size.y`, instead of `board_size.y`:
```
func move_to_bottom():
	while cell.y < size.y - 1:
		cell += Vector2(0, 1)
```

**Note**

This might already be checked for.
But the second hint says:
>To move the robot down, cell.y needs to increase

That's what I used in the reproduction steps above: `cell.y += 1`

but the solution uses:
```
		cell += Vector2(0, 1)
```
If both methods aren't accepted already, then they probably should.

**Update**

Hint one says:
> You'll have to alter the y sub-variable of cell to move the robot downwards.

So it seems like we're expected to use: `cell.y += 1`

It might be best to update the solution, to use `cell.y += 1`, so that it matches the hints.

**Comment by NathanLovato** [comment]
Thanks!
