### ISSUE TITLE
Brave, lesson text looks strange

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#379]
**Describe the bug**

The lesson text looks strange in the Brave browser:

![brave_kVDS3HFA11](https://user-images.githubusercontent.com/13420573/156046123-8a1feb7d-dd9d-414d-bcb5-047ae551d361.png)

**To Reproduce**
Steps to reproduce the bug:
1. Go to 
(https://gdquest.github.io/learn-gdscript/staging/#course/lesson-1-what-code-is-like/lesson.tres)

**Expected behavior**

The text should appear the same as in Chrome and Edge:

![chrome_zRynNI2il5](https://user-images.githubusercontent.com/13420573/156046625-4572879b-eafe-42b2-b218-522d8c6497f8.png)

**Information about your device (please complete the following information):**

 - Operating System: Windows 10 21H1
 - Browsers:
   - Brave 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit) 
   - Google Chrome 98.0.4758.102 (Official Build) (64-bit) (cohort: Stable) 
   - Microsoft Edge 98.0.1108.56 (Official build) (64-bit)

Browsers maximized, on a display with the resolution: `1920x1080`

**Comment by NathanLovato** [comment]
Did you change the zoom level or anything else? Does this happen in a private window with default settings? We use Brave to test every release and didn't encounter this issue, we'd need to know reproduction steps.

**Comment by duianto** [comment]
The zoom level is 100% in all three browsers.
The only reproduction steps are to open the lesson.

I just noticed similar text artifacts on the practice exercise `Continue` button in both Chrome and Edge.

Before pressing the `Run` button with the correct solution:

![chrome_mbvubRcOlr](https://user-images.githubusercontent.com/13420573/156050593-9770e1c3-1269-400d-b478-bca1b88dc5a1.png)

Before pressing the `Run` button with the correct solution (lesson 1 is already solved, we just need to press `Run`):

![msedge_VtJe93MrXG](https://user-images.githubusercontent.com/13420573/156050005-52f6fbce-9c9d-47d1-b0c1-b4f8eb3cc392.png)

The text on the other buttons look fine.

This is observed in both lesson 1 and 17 (so I assume it happens in all of them, but I can check the others if it's needed)


This is so strange 😄 , the `Continue` button text is fine in Brave:

![image](https://user-images.githubusercontent.com/13420573/156050446-129c450a-0d6b-40c0-aa58-f1a32fa22f81.png)

The text issue is reversed.
The lesson text is fine in Chrome and Edge, but the Continue button looks strange.
The lesson text looks strange in Brave, but the Continue button looks fine.

**Comment by duianto** [comment]
The same behavior is observed in all three browsers in a private/incognito window.

**Comment by NathanLovato** [comment]
We changed the text rendering settings yesterday. Could you test the latest version and tell us if the issue is still present on your side? https://gdquest.github.io/learn-gdscript/staging/

**Comment by duianto** [comment]
There is no change at the moment.
The date and hash in the bottom right corner says:
`2022/03/02 18:00:10 | staging::8d28d05e0535fe4f22e679da4ed3f63cab8aed55`

I asked in the other thread:
https://github.com/GDQuest/learn-gdscript/issues/410#issuecomment-1059733765

If you could comment when staging has been updated,
or if I should check back in a couple of hours.

But if it isn't clear when the new version comes out, or you're busy,
then I'll just comment with the results in both threads,
when the new version is available.

**Comment by NathanLovato** [comment]
That's not the right version. Seems the manual build didn't trigger a re-publish. I just triggered a new build, could you check again in 5-10 minutes?

**Comment by NathanLovato** [comment]
It's up now: https://gdquest.github.io/learn-gdscript/staging/

Please be sure to select the URL bar and press Ctrl Shift R to clear the browser's cache and get it to download the latest version if it doesn't load it automatically.

**Comment by duianto** [comment]
It looks fine now.
`2022/03/05 10:13:15 | staging::7c1f32040fe7bceb243194f7fd10842bfd0b59ac`

### Brave

![image](https://user-images.githubusercontent.com/13420573/156879122-29429dff-be5b-4994-9e80-b4759bbea27c.png)

### Edge

![msedge_QAM82lwMmm](https://user-images.githubusercontent.com/13420573/156879198-b4013b7a-d214-495a-ad76-2b48ce2a9c38.png)

**Comment by NathanLovato** [comment]
Thanks!
