### ISSUE TITLE
Course index, right panel, green checkmark causes tall letters to be cut off

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#380]
**Describe the bug**

In the `Course index`, right panel.
The green checkmark to the right of the text: `Lesson read`
causes the right panel's text to shift around slightly.

With Chrome or Edge, maximized on a `1920x1080` resolution display,
the third rows tallest letters: `P` and `i`, become cut off.

Here's a screen recording, that shows what happens
when two lessons in the left panel are selected one at a time.
One has the green checkmark, and the other one doesn't.

https://user-images.githubusercontent.com/13420573/156044559-dee5300b-8d27-4b60-839b-ae4d3c914cab.mp4

**Expected behavior**

The letters shouldn't be cut off.

**Information about your device (please complete the following information):**

 - Operating System: Windows 10 21H1
- Browsers:
   - Brave 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)
   - Google Chrome 98.0.4758.102 (Official Build) (64-bit) (cohort: Stable)
   - Microsoft Edge 98.0.1108.56 (Official build) (64-bit)

**Additional context**

The tallest letters are not cut off when the text `Practice completed` appears on the second row.
This happens when lesson 8 is selected. Because it doesn't have the text: `Quizzes completed`

![msedge_W8dpK7nXcY](https://user-images.githubusercontent.com/13420573/156045660-4d611c8e-45a0-46b2-91c4-536e7f334c08.png)

In the Brave browser.
The right panel's text also shifts around when the green checkmark appears,
but the tallest letters aren't cut off.

https://user-images.githubusercontent.com/13420573/156045197-2c87ed28-5f82-41bd-a56d-499d6f9b71b4.mp4

However, Brave seems to have other text issues.
A separate issue has been opened about it:
Brave, lesson text looks strange #379

**Comment by NathanLovato** [comment]
Forgot about this issue but it should've been fixed when we updated the font resources. I'll close for now but please let me know if the issue happens again on your side and we'll reopen the issue.
