### ISSUE TITLE
H and VSeparator can disappear when they're very thin, depending on scrolling

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#383]
**Describe the bug**

A row of pixels disappears on some lines of text.

It's been observed in other lessons, but this is from lesson 19:
https://gdquest.github.io/learn-gdscript/staging/#course/lesson-19-creating-arrays/lesson.tres

This is most likely not a major issue. At least, in this case, nothing important disappears.
The text is still readable.

But it might be something to investigate, or at least be aware of.

**Workaround**

The current workaround is to just continue scrolling the page.
The text appears as expected when the page is scrolled up or down.

**To Reproduce**

Steps to reproduce the bug:
This is observed in both Chrome and Edge.
The browser is maximized on a display with the resolution: `1920x1080`
Zoom 100%.
The favorites/bookmarks bar is not visible (default setting).

1. Go to
https://gdquest.github.io/learn-gdscript/staging/#course/lesson-19-creating-arrays/lesson.tres
2. Make sure that the page is scrolled to the top: `Home`
3. Press `arrow down` twice.

**Observed**

In the paragraph that starts with: `A list of values, ...`
in the middle of the second sentence: `So we can say calling ...`
one row of pixels has disappeared.
And the top half of the text seems to be shifted down.

This causes some letters to look like they have a gap in the middle: `S`, `s`, `e`, and `a`.

Scrolling the page up or down shows the text correctly.

Here's a combined gif that compares what the text looks like, when the pixels have disappeared,
and when the page is scrolled up or down, and the text looks as expected.

![learn-gdscript-middle-row-of-pixels-cut-off](https://user-images.githubusercontent.com/13420573/156140668-8d6d4de9-a1fe-4f7e-86b2-f25cb20d001a.gif)

The issue can be repeated, but only when scrolling down.
So when the issue is shown (following the reproduction steps above).
- Pressing `arrow up` and `arrow down`, which scrolls the text upwards, shows the issue again.
- But pressing `arrow down` and `arrow up`, which scrolls the text downwards, doesn't show the issue.

**Expected behavior**

The letters should be shown without the missing pixels in the middle.

**Information about your device (please complete the following information):**

 - Operating System: Windows 10 21H1
- Browsers:
   - Google Chrome 98.0.4758.102 (Official Build) (64-bit) (cohort: Stable)
   - Microsoft Edge 98.0.1108.56 (Official build) (64-bit)

**Additional context**

The same thing is observed when scrolling to the bottom of the page: `End`
And pressing `arrow up` once.

Now the middle row of pixels have disappeared,
in the second row of the paragraph: `In upcoming lessons, ...`

The middle of the letters `e`, `a` and `s` look like there's a gap:
(just a screenshot, not a animated gif)

![msedge_FdKttMpEfG](https://user-images.githubusercontent.com/13420573/156141437-6773c9ac-59a0-4f9c-b206-4d319f3348f9.png)

And finally, the text where this issue was first discovered because it's the most obvious.
The examples above were easier to reproduce with just a few arrow key presses.

Scroll to the top of the page: `Home`
Press `arrow down`, twenty times (20).

Now the heading, `When you use arrays` is below the middle of the page.

The first sentence below the heading: `In computer programming, ...`
has the row of pixels at the top of the shorter letters cut off.

Here's a gif, that alternates between the issue and the correct-looking text, when the page is scrolled up or down.

![learn-gdscript-top-row-of-pixels-cut-off](https://user-images.githubusercontent.com/13420573/156142109-d2b0b376-ae70-4766-b0c0-26552878ab9e.gif)

**When the issue doesn't happen**

The issue doesn't happen, at least not on the same lines of text as described above:
- when the scrollbar is dragged, even slightly, probably because it scrolls the page by some number of pixels.
- when the Chrome bookmarks bar or Edge favorites bar is visible, probably because the width of the learn-gdscript app shrinks.

**Comment by NathanLovato** [comment]
It's the separator disappearing due to sub-pixel rendering issues. A teammate is looking into a fix.

**Comment by NathanLovato** [comment]
Ping @Xananax, do you think your change to scaling would help with separators disappearing (because some are still just 1px) or should we just make them thicker?

**Comment by NathanLovato** [comment]
This commit should completely fix this issue, now the lines are thicker so they shouldn't disappear
