### ISSUE TITLE
On last page: `That's it... for now!`, full-screen button overlaps `Report an issue` text

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#386]
**Describe the bug**

After finishing all lessons on:
https://gdquest.github.io/learn-gdscript/staging

On the `That's it... for now!` page.
The top right full-screen button overlaps the last two letters of the text: `Report an issue`

**To Reproduce**
Steps to reproduce the bug:
1. Finish all lessons and click `Continue` on the last practice exercise.
2. When the page opens with the title: `That's it... for now!`
4. Look in the top right corner.

**Observed behavior**

The full-screen button overlaps the last two letters of the text: `Report an issue`

**Expected behavior**

The `Report an issue` text should probably be shifted to the left.
To make room for the full-screen button.

**Screenshots**

![msedge_fvpj2fmWCO](https://user-images.githubusercontent.com/13420573/156180552-666869b7-3360-4aaa-9da5-21b68637faf2.png)

**Information about your device (please complete the following information):**

 - Operating System: Windows 10 21H1
 - Browser: Microsoft Edge 98.0.1108.56 (Official build) (64-bit)

**Comment by NathanLovato** [comment]
Thanks!
