### ISSUE TITLE
Can't go back to the lesson after going to the course index

### ISSUE THREAD

**Issue by xix-xeaon** [GDQuest/learn-gdscript#39]
**Describe the bug**
If you open the course index while in a lesson, then you can't go back to where you were. If you click the icon that replaces it (still says "course index" in tooltip) you go back to the "main screen" - which is unintuitive.

**Comment by pycbouh** [comment]
The tooltip is a small error, this is actually a "Home" button. But indeed, you cannot go back to the lesson. When you leave it, you leave it. With the text and quiz part of the lesson it's not a big deal, as you don't lose any progress (quizzes are tracked, the rest is just the text and examples that you study on your own).

For practices there can be an issue if you leave one after you've worked on the code. To that end we have https://github.com/GDQuest/learn-gdscript/issues/9 that would add a confirmation prompt when you try to do so (whether to go back to the text part of the lesson, or to the index).

**Comment by xix-xeaon** [comment]
It is a big deal from a UX perspective since it's disorienting. The progress you lose is "how far you've scrolled", that is, where you are in the text - and not just the actual scroll but mentally as well.

Menus are part of navigation and navigation is both about going somewhere And knowing where you are. I did not click the icon because I wanted to go somewhere else - I wanted to know where I was, and I also wanted to check my progress. (They kind of go together in this type of app.)

I get your explanation of what the button does but it's also completely foreign to me as a user. I did not expect to leave the lesson by simply opening a menu.

**Comment by pycbouh** [comment]
I think the misconception here is that it's a menu, when it's not. Same as an index in a book, it's just another page. The navigation in the app is designed to only allow going back, with no forward history. I guess we need to indicate that better somehow.

Also, what kind of progress do you want to check? We can add some of that information to the lesson itself. There is not much reason to go to the index other than to go to a different lesson.

**Comment by pycbouh** [comment]
So to address this what I think we should do is 
- Fix the "Home" button tooltip, obviously 🙃 
- Detect and track the last content block of the lesson that the user has seen.
- If you return to the same lesson you just left (or launch the app and click "Continue the Course") we should use that information to restore your scroll position, roughly at the same place.
- Add an ability to create bookmarks throughout the lesson page and allow to quickly navigate to these bookmarks (from the index, probably), https://github.com/GDQuest/learn-gdscript/issues/43
- Add an in-lesson table of content that would allow quickly scrolling to the top, to each named content block (#19), to each quiz, to the last viewed position, to any bookmark, https://github.com/GDQuest/learn-gdscript/issues/43

**Comment by Xananax** [comment]
I'd add "support for escape". My reflex every time I open the index by mistake is to press <kbd>esc</kbd> to go back where I was.

**Comment by NathanLovato** [comment]
I would prefer to close issues that we addressed and then reopen or let people open new ones to suggest improvements.

I'll close for now.
