### ISSUE TITLE
Lesson 20: Mismatch between pre-declared array and array used in solution

### ISSUE THREAD

**Issue by SpeCter** [GDQuest/learn-gdscript#391]
The pre-declared array for the practice is missing a value:
`var rectangle_sizes = [Vector2(200, 120), Vector2(140, 80), Vector2(80, 140)]`

vs. solution array:

`var rectangle_sizes = [Vector2(200, 120), Vector2(140, 80), Vector2(80, 140), Vector2(200, 140)]`

**Comment by NathanLovato** [comment]
Already fixed, duplicate of #385
