### ISSUE TITLE
Explain the term increment in lesson 12

### ISSUE THREAD

**Issue by SpeCter** [GDQuest/learn-gdscript#392]
Starting with Lesson 12 and the following the word increment is suddenly used but not explained.
In my opinion it is enough of a specialized term to warrant at least a little explanation what it means before using it.
Even more so because non-specialized terms like increase etc. were used in the 11 Lessons before that.

**Comment by NathanLovato** [comment]
Do you think it's a word people won't understand? It's the noun corresponding to the verb increase. If you think it need a definition then it'll be good candidate for #21

**Comment by SpeCter** [comment]
I can only speak from my own experience but 20 years ago when I started to learn programming neither the noun nor the verb form of increment where something I particularly knew or used beforehand.  Admittedly it might only be less used in German and be a non-issue in other languages. 

It just seemed odd to me while translating since it wasn't used until Lesson 12 and suddenly is used in the following lessons. Variables instead get more than a whole paragraph explaining what they are - something most people learn in math lessons right after primary school. That in mind I thought it would be more consistent to at least have a single sentence explaining that incrementing is the technical term for increasing a value by a certain amount.


I personally think it looks like a good candidate for the glossary.

**Comment by NathanLovato** [comment]
Sure, asked the team for feedback, noted we should add it in the comment above

**Comment by SpeCter** [comment]
After reading my comment again it felt kinda passive aggressive, which it wasn't meant to be. Sorry in advance if that came out wrong.

**Comment by NathanLovato** [comment]
Didn't come out wrong at all, no worries!

**Comment by NathanLovato** [comment]
Addressed by https://github.com/GDQuest/learn-gdscript/pull/404
