### ISSUE TITLE
Reorder lessons for 1.0 release

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#395]
Depends on #363 #388 and #337

We need to refine the lesson order for the final course release. We should probably move Modulo. Also consider finishing with the Dictionary lessons rather than type lessons as they're more visual.

**Comment by cramsey86** [comment]
Just my own two cents, but Modulo being after Multiplying, makes sense to me.

**Comment by NathanLovato** [comment]
Thanks. After testing and seeing people are fine with the order, we decided to leave them like this for now. We'll reconsider this when we get to add a couple more lessons.
