### ISSUE TITLE
Robot is on top of settings overlay

### ISSUE THREAD

**Issue by razcore-rad** [GDQuest/learn-gdscript#397]
**Describe the bug**
Robot is on top of settings overlay

**To Reproduce**
Steps to reproduce the bug:
1. Start course.
2. Scroll until a Robot is around the middle of the screen.
3. Open the settings panel.
4. See Robot on top of panel.

**Expected behavior**
Robot should be covered by the settings panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/1177508/156377535-6c3c7e98-c4f7-4359-b27c-3656daa70f34.png)

**Information about your device (please complete the following information):**
 - Operating System: Ubuntu 20.10 Linux pavilion 5.13.0-30-generic 
 - Dekstop

**Comment by razcore-rad** [comment]
Seems like it's on top of other pop-ups too
![image](https://user-images.githubusercontent.com/1177508/156378071-ca6fd69d-d38d-45a9-a029-6dd64e1b2cd0.png)

**Comment by razcore-rad** [comment]
This doesn't seem to be the case on the web version d5a0d7cbd23415a06476db69f389ae08cd83e72e

**Comment by razcore-rad** [comment]
It does happen on the web version of master, hash 6de164cb076cb7ae64eabd4e9e28fdcc865e3840
![image](https://user-images.githubusercontent.com/1177508/156379019-bd872127-a72e-4019-b81a-2cf2a83bc435.png)

**Comment by NathanLovato** [comment]
We need to wrap popups in a canvas layer I think. In the commit you mention part of the robot ends up behind the background, so I moved it to Z index 1

**Comment by NathanLovato** [comment]
For the robot animations the back hand needs to be at Z index 0 or -1, causing Z issues
