### ISSUE TITLE
Run the turtle examples second time draw outside rectangle.

### ISSUE THREAD

**Issue by allkhor** [GDQuest/learn-gdscript#4]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
Run the turtle examples second time draw outside rectangle.

**What is the expected behavior?**
Turtle examples draw inside rectangle when you click second time on the run button.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 
Click twice on the run button with turtle code snippet.
![image](https://user-images.githubusercontent.com/1049442/147562979-b824e725-3cb2-48ae-bba4-615d31ed7222.png)

**Comment by NathanLovato** [comment]
Thanks, we're aware of this. We'll try to fix this today.

The app is not even out in beta yet so we don´t use the github bug tracker yet - we currently track our tasks elsewhere until the release.
