### ISSUE TITLE
lesson 22, turtle following mouse, stops at different distances from the edges

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#403]
**Issue description:**

In lesson 22:
https://gdquest.github.io/learn-gdscript/staging/#course/lesson-22-functions-return-values/lesson.tres

In the example where the turtle follows the mouse.
The turtle stops at different distances from the edges.

The red areas show where the turtle stops.

![turtle stops at different distances from the edges](https://user-images.githubusercontent.com/13420573/156577412-747b7aa3-e12c-4548-b94a-8d1a9cc00e96.png)

It might look better if the turtle stopped at the same distance from all edges.

Or if there's a margin to the left and right, that can't be reduced, then feel free to close this.
This isn't important, it's just an observation.

**Comment by NathanLovato** [comment]
Yeah it's on purpose. It's a safe margin that should work with all app settings, like text sizes etc. We can likely add some code to make it look cleaner, it's just low priority.
