### ISSUE TITLE
Lesson 23, last example says pop_back() returns its value to you, but output shows two values

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#409]
**Issue description:**

In lesson 23:
https://gdquest.github.io/learn-gdscript/staging/#course/lesson-23-append-to-arrays/lesson.tres

The text, above the last example, says the following about the `pop_back()` function:
>This function removes (pops) the last value from the array and returns it to you.

But when the `run()` button is pressed, then the `Output` panel shows an array with two items.
```
[fire gem, blue gem]
```

**Cause**

It's because the `run()` function prints what's left in the `crates` array.

And the initial array had three items:
```
var crates = ["fire gem", "blue gem", "yellow gem"]
```

Pressing the `run()` button again shows only one item:
```
[fire gem]
```

Maybe the lesson text should mention that the example prints what's left in the array.
To reduce the risk of confusing beginners.

**Comment by johnnygossdev** [comment]
I thought about printing the popped value, but it would eventually print `null` which hasn't been taught yet.

I added an explanation instead.
