### ISSUE TITLE
"Drawing a rectangle" practice crash app

### ISSUE THREAD

**Issue by ArnaudDelperier** [GDQuest/learn-gdscript#41]
During exercise "drawing a rectangle", when I press "run" button after setting the correct parameters app crash and i must refresh the page.

**To Reproduce**
1. Go to https://gdquest.github.io/learn-gdscript/#course/lesson-4-drawing-a-rectangle/practice-5AJTESv5.tres
2. set functions param
3. Click on 'run'

**Comment by pycbouh** [comment]
https://github.com/GDQuest/learn-gdscript/issues/42 reports the same issue, but has more details. In the interest of clarity, we'll keep only one valid report for each issue open at any time, so I'll close this one. Feel free to add your comments to https://github.com/GDQuest/learn-gdscript/issues/42 if you have more details!
