### ISSUE TITLE
Lesson 23, practice, Completing orders: gdquest boy text looks strange

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#410]
**Describe the bug**

In lesson 23's practice exercise:  Completing orders,
after running the code with a working solution,
then the text in the top right panel looks strange.
In both the Edge and Brave browsers.

**To Reproduce**
Steps to reproduce the bug:
With the browsers Edge and Brave maximized.
On a display with the resolution: `1920x1080`

- Go to: https://gdquest.github.io/learn-gdscript/staging/#course/lesson-23-append-to-arrays/practice-KUdOCQiG.tres
- Press the `Solution` button
- Press the `Use solution` button
- Press the `Run` button
- Wait for the code to be validated, run, and tested
- See that the text in the top right gdquest boy panel looks strange.
It looks slightly different in Edge, compared to in Brave.
Maybe it's related to the issue:
Brave, lesson text looks strange #379

**Expected behavior**

The text should look like the rest of the text on the same page.

![msedge_00XSHFBAlL](https://user-images.githubusercontent.com/13420573/156718584-22d6deb8-978f-4e1e-804d-4ad672396f1f.png)

**Screenshots**

Edge

![msedge_2tZWeJV9rJ](https://user-images.githubusercontent.com/13420573/156718183-b5196d8e-4353-42c9-812f-e56f95e3fa8a.png)

Brave

![brave_IGKvhL0joY](https://user-images.githubusercontent.com/13420573/156718206-182cd165-a85f-47a7-aa54-963821e83dc1.png)

**Information about your device (please complete the following information):**

 - Operating System: Windows 10 21H1
 - Browsers:
    - Brave 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit) 
    - Microsoft Edge 98.0.1108.62 (Official build) (64-bit)

**Comment by duianto** [comment]
The same text looks fine in the example in lesson 23:
https://gdquest.github.io/learn-gdscript/staging/#course/lesson-23-append-to-arrays/lesson.tres

![msedge_xCo5eu2kJo](https://user-images.githubusercontent.com/13420573/156721624-0f896fd4-737c-4614-9655-4d5a6e19c5b2.png)

**Comment by razcore-rad** [comment]
So yes, this is a zoom/alignment issue in Godot with fonts. We can see this in the 2D viewport as well
![image](https://user-images.githubusercontent.com/1177508/156749046-24d16cdf-e754-4c74-a527-8d3fc9b77653.png)

The two options are:

1. look pixelated as above
2. look fuzzy by turning on `Settings > Use Filter`:

![image](https://user-images.githubusercontent.com/1177508/156749136-a81ac296-6111-4860-8d5b-ea769979d3af.png)

The  `Settings > Use Mipmaps` option should improve the font look when downscaling, but this is a Godot issue, we can't really do much about it on our end.

**Comment by razcore-rad** [comment]
I think generally speaking using `Settings > Use Mipmaps` and `Settings > Use Filter` for all fonts should improve the experience somewhat compared to the pixelated look. This could affect #379 as well.

**Comment by NathanLovato** [comment]
Go ahead! And I guess the scene is downsized to fit in the GDQuestBoy, is that it? Feel free to also set a thicker font-weight if necessary for this scene, if it helps with readability

**Comment by razcore-rad** [comment]
closed via 7c1f32040fe7bceb243194f7fd10842bfd0b59ac

**Comment by NathanLovato** [comment]
We need to check if that could also have fixed #379. I'll start a new staging release build, @duianto, could you test it later today and tell us if that helped?

**Comment by duianto** [comment]
There is no change at the moment.
The date and hash in the bottom right corner says:
`2022/03/02 18:00:10 | staging::8d28d05e0535fe4f22e679da4ed3f63cab8aed55`
It said the same thing yesterday.

Could you add a comment here when it's been updated?
Or should I just check again in a couple of hours?

**Comment by duianto** [comment]
In the latest version:
`2022/03/05 10:13:15 | staging::7c1f32040fe7bceb243194f7fd10842bfd0b59ac`

It's better than the screenshots in the initial post.
And it looks the same in both Brave and Edge.

![msedge_YVdc20PEca](https://user-images.githubusercontent.com/13420573/156879343-d433eb4c-4394-463c-96cc-d040a7b84eaa.png)

But as razcore-rad said:
>this is a zoom/alignment issue in Godot with fonts

So it might never not look as good as the example in the lesson:
https://github.com/GDQuest/learn-gdscript/issues/410#issuecomment-1058918980
The example is probably shown without any zoom/alignment.

**Comment by NathanLovato** [comment]
Thanks much!
