### ISSUE TITLE
In lesson 24's exercise, `Using the right crystals`, no pink gem

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#416]
**Describe the bug**

In lesson 24's exercise, `Using the right crystals`
https://gdquest.github.io/learn-gdscript/staging/#course/lesson-24-access-array-indices/practice-ErO9L4MW.tres

The `Goal` ask us to use the `pink` and `yellow` gems, but there is no `pink` gem.

**To Reproduce**
Steps to reproduce the bug:
1. Go to https://gdquest.github.io/learn-gdscript/staging/#course/lesson-24-access-array-indices/practice-ErO9L4MW.tres
2. In the left panels `Goal` section, read the second paragraph:
>They want to use the pink and yellow crystals to buff their characters. Like before, we need to find them in the array.

But there is no pink gem in the grid of gems.

**Expected behavior**

Since the accepted solution shows the message:
>using item 5: "fire pickup"

Then it seems like the `pink` color should be changed to: `red`

**Screenshots**

![msedge_umgZVD48vT](https://user-images.githubusercontent.com/13420573/156765044-8a6d5553-c9d0-4acd-9923-28d47da6cb1b.png)

**Information about your device (please complete the following information):**

 - Operating System: Windows 10 21H1
 - Browser: Microsoft Edge 98.0.1108.62 (Official build) (64-bit)

**Comment by Xananax** [comment]
I changed the text to say "fire" and "lightning" in dbdae73a1365107d48a392f93133195875874f3a, but I'm not sure it's much better.

I suggest to either have the gems with their names at the top of the display, or to use embed images in the text

**Comment by Xananax** [comment]
This is also related to #408 

We could also not use gems at all, and use sword/potion/coin/shield instead, which are much less confusing (and better for colorblind people)

**Comment by NathanLovato** [comment]
Sounds good, we have sprites at least for shield, sword, and whatnot. They should all be in the gunner project, but ping me if you need files

**Comment by johnnygossdev** [comment]
Got them thanks! I still have them from working with them.
