### ISSUE TITLE
 Lesson number doesn't match in title and url for 25, 26 and 27

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#421]
**Issue description:**

The url for lesson 25 says `lesson-26`:
https://gdquest.github.io/learn-gdscript/staging/#course/lesson-26-looping-over-dictionaries/lesson.tres

The title shows the expected number.
25. Looping over dictionaries

The same behavior is observed for:
lesson 26:
https://gdquest.github.io/learn-gdscript/staging/#course/lesson-27-value-types/lesson.tres

and lesson 27:
https://gdquest.github.io/learn-gdscript/staging/#course/lesson-28-specifying-types/lesson.tres

Lesson 24 and all earlier lessons match the lesson number in the title with number in the url.

**Comment by NathanLovato** [comment]
It's a known issue, depends on #337 and #395
