### ISSUE TITLE
Glossary pop-ups only show up once or after scrolling

### ISSUE THREAD

**Issue by SpeCter** [GDQuest/learn-gdscript#422]
The pop-ups for glossary entries only show up once. After dismissing the current entry it gets unclickable and can only be clicked again after scrolling the screen.
Scrolling back however might make it unclickable again. For example when clicking a glossary entry without having scrolled it will only turn clickable when scrolling the screen a bit. Scrolling back to the beginning will turn it unclickable again.

**Comment by NathanLovato** [comment]
Yeah noticed that, might be a Godot bug, gotta see.

**Comment by duianto** [comment]
Was the fix https://github.com/GDQuest/learn-gdscript/commit/4f0e2929eaee65c64947b16793fbff2f115d000a from an hour ago, part of the latest staging release?

`2022/03/05 10:13:15 | staging::7c1f32040fe7bceb243194f7fd10842bfd0b59ac`

Or will it be included in the next release?

And does it also fix the issues:
- The mouseover area is smaller than the pop-up.
This causes the pop-up to close to early when the mouse pointer is moved down the pop-up while reading.
- A hidden pop-up, still blocks mouse wheel scrolling when the mouse pointer is over the area where the pop-up appeared.

If these issues weren't covered, then I can open separate issues for them.

**Comment by NathanLovato** [comment]
No the fix came after the build. I just fixed the rest, we had to defer some instructions because some calculations in the UI don't update until after the processing update step.
