### ISSUE TITLE
Lesson 22 practice solution is completely available in lesson text

### ISSUE THREAD

**Issue by SpeCter** [GDQuest/learn-gdscript#424]
Right now the solution to the practice is completely available from the lesson text, maybe it would be better do the opposite and instead of converting to world_coordinates from grid coordinates the student has to convert to grid_coordinates from world_coordinates.

It's not that big of a deal but leaving it like it is feels too much of a temptation to cheat.

**Comment by NathanLovato** [comment]
The solution for every practice is always one click away. It's not cheating: it's built into the app. The opposite function requires things the student doesn't know (flooring vectors), which is why we repeat the function from the lesson.
