### ISSUE TITLE
Lesson 6 - "Drawing squares of any size" correct solution not accepted

### ISSUE THREAD

**Issue by MrInventor** [GDQuest/learn-gdscript#426]
**Describe the bug**
Leaving out the final turn_right(90) will mark the solution as wrong even though the solution seems correct.

**To Reproduce**
Steps to reproduce the bug:
1. Go to [https://gdquest.github.io/learn-gdscript/#course/lesson-6-multiple-function-parameters/practice-v5tT6n1T.tres](url)
2. `func draw_square(length):
	move_forward(length)
	turn_right(90)
	move_forward(length)
	turn_right(90)
	move_forward(length)
	turn_right(90)
	move_forward(length)
`

**Expected behavior**
The solution is accepted

**Screenshots**
![image](https://user-images.githubusercontent.com/2348455/156916983-12ec1ac8-c52f-4292-9b57-9062cb38ab3c.png)

**Information about your device (please complete the following information):**
Windows 10 and Chrome.

**Comment by NathanLovato** [comment]
Yes, gotta change the practice description, the code doesn't complete the shape as we'd like you to: as the turtle changes direction, it causes subsequent shapes to end up in unintended positions (the second square should be inside the first one). We'll correct this.
