### ISSUE TITLE
Color "Confusion" in Modulo lesson 15

### ISSUE THREAD

**Issue by MrInventor** [GDQuest/learn-gdscript#430]
**Issue description:**
In Lesson15 Modulo in the modulo illustration on the right. 
(Which i really like 😊 )

The "number" slider is green and show by green boxes. Makes sense.
The "modulo" is grey but the grey boxes illustrate the remainder. 

![image](https://user-images.githubusercontent.com/2348455/156927471-187527e7-b3e7-480e-b011-fd7bbf0ea938.png)

_Suggestion:_
Move the math part with "Remainder: x" under the sliders. 
Change color of "Remainder: x" test to reflect the color of the boxes. 
Change the colors for Modulo slider to one that is not used on the boxes.

**Comment by razcore-rad** [comment]
How's this looking?
![](https://cdn.discordapp.com/attachments/927720565417058416/950412217881329684/Peek_2022-03-07_17-18.gif)

**Comment by NathanLovato** [comment]
No, that doesn't read well. It was clearer before. I think it's just a matter of tweaking the original visuals - as mentioned in the first issue, the point causing confusion is that the modulo slider is grey like the grey boxes.

**Comment by razcore-rad** [comment]
No. This is wrong. In the original, both sliders are green (on mouse hover). The original screenshot makes sense just cause it happens that number = 3 and reminder = 3 as well so there are only 3 green boxes. With number = 4, modulo = 6, the reminder is  2 so would mean 2 green boxes. It doesn't correspond to number = 4.

**Comment by razcore-rad** [comment]
I guess what I'd change in my version is to color-code the slider the same way weather the mouse hovers or not over them.
