### ISSUE TITLE
Lesson 25: The second question, accepts an incorrect answer

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#435]
**Describe the bug**

Lesson 25, second question.
>How would you access how many gems the player has?

Accepts an incorrect answer: `inventory["gem"]`

The "Your right!" text says:
>In our case, var item_count = inventory["gems"] is correct.

**To Reproduce**
Steps to reproduce the bug:
1. Go to https://gdquest.github.io/learn-gdscript/staging/#course/lesson-25-creating-dictionaries/lesson.tres
2. Scroll down to the second question:
>How would you access how many gems the player has?

3. Click on the correct answer: `inventory["gems"]`
4. Click on the `Submit` button.
5. See that it isn't accepted. The question frame gets a red border.
6. Click on the incorrect answer: `inventory["gem"]`
7. Click on the `Submit` button
8. See that it's accepted.

**Expected behavior**

The correct answer should be accepted.

If this is the line that's causing the issue:
https://github.com/GDQuest/learn-gdscript/blob/fecda26712a76fc1b80730d1c2162ba715d02081/course/lesson-25-creating-dictionaries/lesson.tres#L175

Then it might be enough to change: `gem` to `gems`

**Information about your device (please complete the following information):**

 - Operating System: Windows 10 21H2
 - Browser: Microsoft Edge 98.0.1108.62 (Official build) (64-bit)

**Comment by NathanLovato** [comment]
Closed by f57fd683165c2bdeda3a2b96487fa18fe8e3b849
