### ISSUE TITLE
Second quizz from lesson 25

### ISSUE THREAD

**Issue by jaspior** [GDQuest/learn-gdscript#439]
A simple typo. The dictionary is:

var inventory = {
    "healing heart"  : 3,
     "gems" : 5,
     "sword": 1,
}

and the quizz ask "How would you access how many gems the player has?"

The image show what happens when you try the right answer

![teste2](https://user-images.githubusercontent.com/38392025/157311778-7c320082-cabe-4546-b127-d4809e9321b8.png)

If you choose var item_count = inventory["gem"], you have the right output:

![image](https://user-images.githubusercontent.com/38392025/157312112-b97d55f5-7244-44ef-879e-9e0e08d36e1a.png)

**Comment by jaspior** [comment]
> Just wanted to report this too, one little addition to this is that the issue title is incorrect. It is in fact quiz from lesson 25 - Creating dictionaries and not from lesson 22.

Sorry, I corrected the title. Thank you!

**Comment by NathanLovato** [comment]
It's already fixed: https://github.com/GDQuest/learn-gdscript/issues/435
