### ISSUE TITLE
Lesson 28 - Float cell_size error example

### ISSUE THREAD

**Issue by ferryman10** [GDQuest/learn-gdscript#440]
**Issue description:**
Hello, 
I would like to report a typo/copy-paste issue in the first half of the lesson 28. In the code example cell_size is a whole number and not a float. 
![image](https://user-images.githubusercontent.com/12326997/157330411-df5cbcb0-045a-4046-953b-4ecca406e257.png)

Also I'm not entirely sure as a GDscript newbie but even if it was integer it would most likely fail as we are trying to sum Vector2 **(cell * cell_size)** and INT **(cell_size/2)**.

**Comment by NathanLovato** [comment]
It can work as a float here, but we should tweak the code, definitely.

Int and float is the one case where Gdscript always does conversions automatically, giving you warnings but not errors when it does so. And that even if you use type hints.

**Comment by NathanLovato** [comment]
Fixed in 660e68332412c28e426e7e298378bb5d1000f218
