### ISSUE TITLE
You can hide the robot and reset won't show me him again

### ISSUE THREAD

**Issue by IkutiDev** [GDQuest/learn-gdscript#442]
**Describe the bug**
If you run the function hide() in Make the Robot Upright, you can hide it. You need to call show() to make him visible again, while reset doesn't do it, it keeps him hidden.

**To Reproduce**
Steps to reproduce the bug:
1. Call hide() function in Make the Robot Upright practice
2. Run Reset to make the practice go back to default
3. Robot is still hidden, need to call show() function to make him visible

**Expected behavior**
A reset should probably return the practice to default/start behaviour.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/40697587/157752327-0c739fae-f9e2-47a2-b662-b184f0741cda.png)
![obraz](https://user-images.githubusercontent.com/40697587/157752356-b23a009f-b837-4090-9a74-284be84e45fe.png)
![obraz](https://user-images.githubusercontent.com/40697587/157752405-42a128c1-26a9-48f0-b567-14e0a4240a8e.png)

**Information about your device (please complete the following information):**
 - Windows
 - Desktop app for Windows

**Comment by NathanLovato** [comment]
You can always do that indeed. That's a bit tricky, we don't have a great way to reset the whole state for the character. Perhaps we can store its visibility and transform to safeguard against these particular case.

**Comment by IkutiDev** [comment]
Storing just should suffice, although I don't know how it looks with future functions since I'm only on lesson 6 so far. But at least some kinda basic safeguards should help in case someone who hides the character on accident
