### ISSUE TITLE
Word "Type" is highlited when it probably shouldn't be

### ISSUE THREAD

**Issue by IkutiDev** [GDQuest/learn-gdscript#446]
**Describe the bug**
When lesson 6 talks about typing on keyboard, the highlight on it is talking about programming types.

**To Reproduce**
1. In lesson 6 highlight the type word in extra information box

**Expected behavior**
It should probably be disabled there

**Screenshots**
![obraz](https://user-images.githubusercontent.com/40697587/157932969-16c731d6-daa1-4a22-9065-49afb3ce0244.png)

**Information about your device (please complete the following information):**
- Windows (Desktop app)

**Comment by NathanLovato** [comment]
There are probably a number of instances of this, but as the glossary's automatic, for now, it's gonna stay this way unless someone wants to do the busywork of making the glossary work with stronger rules or by hand.
