### ISSUE TITLE
Warning, the app is not suitable on mobile device, is not fully readable

### ISSUE THREAD

**Issue by jacky-brownsteen** [GDQuest/learn-gdscript#448]
**Describe the bug**
I'm not sure if this is a bug or merely a text problem. It's for sure a veeery small one with low priority!
If I follow the link https://gdquest.github.io/learn-gdscript/ on my smartphone (/e/OS, Brave Browser), there pops up a warning, that the app is not suitable on a mobile device. So far so good. The only "problem" is, that the text is not fully readable as the text window is sized in a way, I cannot access all the text. Sometimes I was able to scroll to the right, but I never was able to see the text which is cut off on the left side.

**To Reproduce**
Steps to reproduce the bug:
1. Go to https://gdquest.github.io/learn-gdscript/ from a smartphone (/e/OS, Brave Browser)
2. See warning popup

**Expected behavior**
The full text should be readable.

**Screenshots**
![Screenshot_20220312-115854_Brave](https://user-images.githubusercontent.com/63466503/158015563-b2e17881-1f04-4509-849c-b860be06a051.png)

**Information about your device (please complete the following information):**
 - Operating System: /e/OS
 - Browser: Brave

**Comment by NathanLovato** [comment]
We should definitely make the modal fit the browser and the text wrap as needed. Thanks!
