### ISSUE TITLE
Lesson 15. Modulo freezes up

### ISSUE THREAD

**Issue by MaggieKix** [GDQuest/learn-gdscript#451]
When executing the script in "advancing traffic lights", browser will freeze up.

Steps to reproduce the bug:
1. Go to lesson 15, "advancing traffic lights"
2. Complete script
3. Run
4. See error "ERROR connection timed out"

I have reset my cache and cookies but it still does happen, I have a stable connection

 Windows 11, Chrome

**Comment by MaggieKix** [comment]
[gdquest-1647394061185.log](https://github.com/GDQuest/learn-gdscript/files/8258255/gdquest-1647394061185.log)

**Comment by NathanLovato** [comment]
Could you try again? Might've just been the server restarting after a crash. If it works now, we can close the issue.

**Comment by NathanLovato** [comment]
Should be fixed with #462 now solved, that was the root issue, server-side. We're also now working on #300 to remove the need for an internet connection and server entirely.
