### ISSUE TITLE
Lesson 25 Question 2 does not have the right answer.

### ISSUE THREAD

**Issue by sugarsthenewwhite** [GDQuest/learn-gdscript#453]
It's pretty self explanatory. It is supposed to choose var item_count = inventory["gems"] as the right answer, but the correct option is "gem" instead.
![resim](https://user-images.githubusercontent.com/53354625/159007690-329ee0d4-4de9-4abd-b4ff-6a9cf008889a.png)

**Comment by NathanLovato** [comment]
Already fixed, duplicate of https://github.com/GDQuest/learn-gdscript/issues/435
