### ISSUE TITLE
15. Modulo - Calculating a random number within a range

### ISSUE THREAD

**Issue by cramsey86** [GDQuest/learn-gdscript#455]
In lesson **15. Modulo**, the **calculating a random number within a range section**, the example code does not have a **modulo** in it.

**Comment by rnwolf** [comment]
I also wondered about that and then I noticed that the line wraps round.  I think it is ok.

```
func roll_dice():
    var dice_value = randi() % max_number + 1
    display_value(dice_value)
```

![image](https://user-images.githubusercontent.com/117415/159173574-96d02a10-13e3-42bd-85f7-0e140238395a.png)

**Comment by cramsey86** [comment]
OK cool. must have just been showing weird on my browser
