### ISSUE TITLE
Long time to validate Code on RUN - Timeout errors

### ISSUE THREAD

**Issue by maranr** [GDQuest/learn-gdscript#458]
**Describe the bug**
It takes a long time to run the code when pressing the RUN button for the stand-alone windows version. I also get a time-out errors.

**To Reproduce**
1. Go to Limited Healing Conditions Module
2. Complete the code. 
3. Press Run
4. Takes up to a minute to evaluate code

**Expected behavior**
Code checking should be a lot faster. No timeout errors.

**Screenshots**
If applicable, drag and drop screenshots here to help explain your problem.

**Information about your device (please complete the following information):**
 - Operating System: [e.g. iOS, Windows]
 - Browser: [e.g. Chrome, Safari]

**Additional context**
[2022-03-19-17-15.log](https://github.com/GDQuest/learn-gdscript/files/8310146/2022-03-19-17-15.log)

**Comment by NathanLovato** [comment]
The server stalled, that may happen from time to time
