### ISSUE TITLE
Text/Input field not focused on mousepress (Qutebrowser)

### ISSUE THREAD

**Issue by b4raba** [GDQuest/learn-gdscript#46]
**Describe the bug**
This is an issue (I believe) specific to Qutebrowser.  
Text input field (where you edit code) isn't focused automatically on mousepress like you would expect.
Qutebrowser users need to manually enter "Insert mode" to be able to edit the code. This effectively means you need to type "i" to edit code every time you focus away from the text box (like pressing "run" or clicking somewhere else). 

**To Reproduce**
Steps to reproduce the bug:
1. Run demo in Qutebrowser

**Expected behavior**
I expected my browser to automatically enter Insert mode, like it does in every other input field when I click it.

**Information about your device (please complete the following information):**
 - Operating System: Linux
 - Browser qutebrowser v2.4.0 (QtWebEngine 5.15.7, based on Chromium 87.0.4280.144)

**Additional context**
This is probably qutebrowser specific issue, I don't expect much here. It's just annoying.

**Comment by pycbouh** [comment]
If it's browser specific, we can probably report it upstream on the Godot repo. We wouldn't be able to fix it on the project level, in all likelihood. We'll try to reproduce the issue and see what we can do about it.

**Comment by NathanLovato** [comment]
That does sound like something that depends on Godot and not on us as Yuri says. We probably won't be able to fix it ourselves. Have you tried any other Godot html5 app in your browser? And if so, did you experience the same issue?

**Comment by Xananax** [comment]
Qutebrowser detects HTML input boxes, but a webgl context isn't that. It won't automatically focus webgl, nor automatically set input mode. This is similar to opening a web game on itch.io.

You want to set passthrough mode in the tab for this to work <kbd>ctr</kbd><kbd>v</kbd>.

You cannot automatically set passthrough per url, it's a planned enhancement: https://github.com/qutebrowser/qutebrowser/issues/5524 (solution at https://github.com/qutebrowser/qutebrowser/issues/4960 if you're willing to fiddle with the source).

**Comment by NathanLovato** [comment]
Should we keep this issue open? Its not something we could fix in the app, right? If we can't solve this, you can mark it as wontfix and close.

**Comment by b4raba** [comment]
You can close this, passthrough mode works around this as @Xananax  suggested.
Happy New Year!

**Comment by Xananax** [comment]
Happy new year!
