### ISSUE TITLE
Lesson 2 "My first error" won't run the initial program/times out

### ISSUE THREAD

**Issue by Syweb2** [GDQuest/learn-gdscript#461]
**Describe the bug**
When I press "run" on the first activity of Lesson 2, it will say "validating your code" for a a little under a minute and then show two error messages: "ERROR: Connection timed out" and "ERROR: Oh, no! The script has an error, but the Script Verifier Server did not catch it"

**To Reproduce**
Steps to reproduce the bug:
1. Go to Lesson 2: My first Error's first activity, "Fix Your Error"
2. Click on 'Run'

3. Scroll down to the bottom-right, where the output and error messages are

**Expected behavior**
The program would show an error message related to the program itself, not my connection.

**Screenshots**
If applicable, drag and drop screenshots here to help explain your problem.
![error_msg_01](https://user-images.githubusercontent.com/54687034/159213061-1bf34310-9436-41ce-80ac-23a44193dd95.JPG)

**Information about your device (please complete the following information):**
 - Operating System: Windows
 - Browser: Firefox

**Additional context**
[gdquest-1647842725456.log](https://github.com/GDQuest/learn-gdscript/files/8313421/gdquest-1647842725456.log)

**Comment by NathanLovato** [comment]
It's the server process freezing, despite our crash/freeze detection mechanisms, there are cases where it doesn't restart. I just restarted it manually but that may keep happening until we find someone to work on #300

**Comment by Syweb2** [comment]
The problem seemed to stop for a bit a couple of days ago, but it's back now. Did I just get lucky briefly?

**Comment by NathanLovato** [comment]
Please check out #462
