### ISSUE TITLE
Lesson 5: running example of `draw_three_lines` function in the in-lesson viewer

### ISSUE THREAD

**Issue by Sheshuk** [GDQuest/learn-gdscript#465]
**Describe the bug**
The turtle in the in-lesson viewer (when you hit the `draw_three_lines` button) behaves differently than reproducing the code in the Practice part

*Screenshot1*: 
An erroneous behavior in the lesson: 
![screenshot1](https://user-images.githubusercontent.com/6203997/159680420-7f181cfb-7c90-4aac-a9cd-b1b22002c275.png)

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'Lesson 5: Coding your first function'
2. Scroll down to 'Instantly moving the turtle to a different position'
3. Click on `draw_three_lines` button on the left
4. See the turtle jumping each time to the starting point  on `jump(-100, 50)` and making sloped lines (see screenshot above)

**Expected behavior**
A `jump(-100,50)` should position a turtle 50pt below the starting point. A turtle would produce three parallel horizontal lines.

*Screenshot2: 
The expected output image:
![screenshot2](https://user-images.githubusercontent.com/6203997/159682797-ff0ca03d-0228-46bb-ac47-48ca5d221c10.png)

Steps to check the expected behavior:
1. Click 'Practice'
2. Write code similar to the example
3. Change the function name to `draw_square()`
4. Run

**Information about your device (please complete the following information):**
 - Operating System: Linux
 - Browser: Firefox

**Comment by NathanLovato** [comment]
Thanks, this is a regression, and a tricky one. I gave it some work but couldn't nail the fix yet. Gotta think about this.

**Comment by NathanLovato** [comment]
Thanks for the report!
