### ISSUE TITLE
Lesson 4: using rotate() in "Drawing a corner" test glitches out the turtle

### ISSUE THREAD

**Issue by theMotionblur** [GDQuest/learn-gdscript#471]
**Describe the bug**
Using rotate() in the "Drawing a corner" test glitches out the turtle, even before it hits the rotate() function
The lines drawn before the code hits rotate() aren't straight any more.

**To Reproduce**
Enter the following code into the playground console
https://gdquest.github.io/learn-gdscript/#course/lesson-4-drawing-a-rectangle/practice-Gx0c7DDi.tres

```
func draw_corner():
	move_forward(150)
	turn_right(60)
	move_forward(150)
	turn_right(60)
	move_forward(150)
	turn_right(60)
	move_forward(150)
	turn_right(60)
	move_forward(150)
	turn_right(60)
	move_forward(150)
	turn_right(60)
	rotate(45)
	move_forward(200)
```

**Expected behavior**

**Screenshots**
![grafik](https://user-images.githubusercontent.com/29011290/160298192-d528ed2b-0894-4013-a058-36a581433508.png)

When omiting the rotate() function it actually works as expected
![grafik](https://user-images.githubusercontent.com/29011290/160298281-12c40185-677c-47ed-9240-07e813db37bc.png)

**Information about your device (please complete the following information):**
Windows 11 Home
Mozilla Firefox 98.0.2

**Comment by NathanLovato** [comment]
That's normal, you shouldn't rotate the turtle. As mentioned in the practice, you need to use its functions turn_right and turn_left

**Comment by theMotionblur** [comment]
PLease try the actual code in the demo console. I mean - I am aware that this is not the expected solution to the question. What baffles me is that in that example the turtle slides diagonally and produces slightly diagonal lines even _before_ the code hits the rotate() statement.

**Comment by NathanLovato** [comment]
Yes but again, that's normal, you can't use `rotate()` with the turtle, it's unsupported. You have to use its API, as shown and explained in the lessons and practices.
