### ISSUE TITLE
Lesson 6: using a for loop produces correct result but isn't accepted

### ISSUE THREAD

**Issue by theMotionblur** [GDQuest/learn-gdscript#472]
**Describe the bug**
The goal of the second Practice is to create a function that takes one parameter and the turtle has to end facing right.
https://gdquest.github.io/learn-gdscript/#course/lesson-6-multiple-function-parameters/practice-v5tT6n1T.tres

**To Reproduce**
Actually writing the code with a for loop instead of duplicates produces the correct result but it's not recognised by the program:
```
func draw_square(length):
	for i in 4:
		move_forward(length)
		turn_right(90)
```

**Expected behavior**
Despite using a method only introduced later in the course it does produce the correct result and adheres to the requirements.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/29011290/160300715-5a6596b8-993b-4056-a260-6fbdea4e52ae.png)

**Comment by theMotionblur** [comment]
Sorry - just realized that this is a duplicate:
https://github.com/GDQuest/learn-gdscript/issues/466

**Comment by NathanLovato** [comment]
No worries, thanks for the report. Closing as it's a duplicate
