### ISSUE TITLE
Lesson 14: Practice 1 - should have the variables in the code

### ISSUE THREAD

**Issue by theMotionblur** [GDQuest/learn-gdscript#473]
**Issue description:**
(from: https://gdquest.github.io/learn-gdscript/#course/lesson-14-multiplying/practice-0c7DDizK.tres)
It's understood that the lesson focuses on the level up via multiply and linear level progression/addition but I find it a little off putting that the variables aren't defined above the function.

Maybe there should be some sort of convention to explicitly show that this is only a part of the code and the rest is statically defined for the user. Maybe greyed out. If I didn't know the scripting basics already I know I would be confused as to why I don't need to define the variables in this case.
Or in my case I actually tried to define the variables first and got the hint that they are already defined, which I would find equally 
confusing.

**Comment by NathanLovato** [comment]
They should definitely be there, you're right!
