### ISSUE TITLE
Lesson 16: Vector2 closing bracket outside of Codebox

### ISSUE THREAD

**Issue by theMotionblur** [GDQuest/learn-gdscript#474]
**Issue description:**
The closing bracket in the example under the turtle doesn't show the closing bracket:
![grafik](https://user-images.githubusercontent.com/29011290/160699224-e2a8f99a-7771-4a66-9658-954e42c35166.png)

**Comment by NathanLovato** [comment]
Yes, it's, unfortunately, an issue on Godot's side. See #99. This can happen in many places in the app depending on your text settings, so it's not something we can solve easily. We looked into the engine's source code and that's really tricky.

Godot 4 should address this with its complete rewrite of text rendering. It's taken them months of work to do this, so we abandoned the idea of trying to fix this issue in Godot 3.x.

I'm closing this as #99 encompasses all those specific issues. But thanks for the report.
