### ISSUE TITLE
Lesson 23 APpending and Popping from Arrays - Practice: Clearing up the crates

### ISSUE THREAD

**Issue by martindm33** [GDQuest/learn-gdscript#477]
The practice asks you to use a while loop to remove elements from the array. There is no explanation of the size method in the lesson but it is explained in lesson 24. This was confusing as it seemed like something I should know already.

Suggest moving the use of the .size method to lesson 23.

**Comment by NathanLovato** [comment]
Thanks. Actually, I'd rather not teach people to use `Array.size()` as this will typically compute the size on every run, which requires counting the elements in the array. Instead, you can use `while crates` or the longer but more explicit `while not crates.empty()`
