### ISSUE TITLE
Lesson 20 typo?

### ISSUE THREAD

**Issue by fro9butt** [GDQuest/learn-gdscript#478]
**Issue description:**
A clear and concise description of what the issue is.

After the first multiple choice. ( Making a turtle walk, with a loop )
Something wrong with the tag of "Array"

**Comment by NathanLovato** [comment]
I looked for an issue but can't spot one there. Is it supposed to be in this part of the lesson?

![image](https://user-images.githubusercontent.com/12694995/161844202-29df6506-2dbc-4471-babe-e51a176e745f.png)

**Comment by fro9butt** [comment]
it is ok after reload(F5)
perhaps that's something wrong with my browser
thanks for the reply

Nathan Lovato ***@***.***> 於 2022年4月6日 週三 上午4:33寫道：

**Comment by NathanLovato** [comment]
It was probably an older version of the app that was cached. Thanks for letting me know
