### ISSUE TITLE
Lesson 27, Cant assign to an expression

### ISSUE THREAD

**Issue by SRhinocodes** [GDQuest/learn-gdscript#483]
**Describe the bug**
"Cant assign to an expression" is the error message I get asking me to report it.

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'Lesson 27'
2. Edit Code to  'func buy_selected_item():
	                   int(player_input) = get_player_input()'      the edited part is the added "int()" at the wrong place
3. Click  'Run'

**Expected behavior**
To see if this code works or not, and get an error message explaing what kind of error it is.

**Screenshots**
![image](https://user-images.githubusercontent.com/92609269/162151831-ca60e8a2-f418-44e6-a77c-1b6d622b6e88.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows
 - Browser: Chrome

**Comment by NathanLovato** [comment]
Seems we don't have a pattern check or message for this particular error. We'll look into adding it.

**Comment by NathanLovato** [comment]
This should be fixed by https://github.com/GDQuest/learn-gdscript/pull/648
