### ISSUE TITLE
Test fails in lesson 6 "Drawing Squares Of Any Size" 

### ISSUE THREAD

**Issue by Sanasheym** [GDQuest/learn-gdscript#486]
**Describe the bug**
Test "Draw squares of varying sizes" fails, although the code is correct.

**To Reproduce**

```
func draw_square(length):
	turn_right(90)
	move_forward(length)
	turn_right(90)
	move_forward(length)
	turn_right(90)
	move_forward(length)
	turn_right(90)
	move_forward(length)
```

When I add an additional `turn_right(90)` at the end, also the second test (Turtle ends facing torwards the right) fails.

**Expected behavior**
All tests should pass.

**Information about your device (please complete the following information):**
 - Operating System: Windows 10

**Comment by NathanLovato** [comment]
Yeah it's also in the practice description:

> The turtle should face towards the right **when starting or completing a square**.

I'll flesh this out a little more and add a dedicated check, thanks for the suggestion
