### ISSUE TITLE
Tests fail in lesson 11 "Moving in a circle using delta"

### ISSUE THREAD

**Issue by Sanasheym** [GDQuest/learn-gdscript#488]
**Describe the bug**
The first two tests fail.

**To Reproduce**

```
func _process(delta):
	rotate(2*delta)
	move_local_x(100*delta, false)
```

**Expected behavior**
All tests should pass.

**Information about your device (please complete the following information):**
 - Operating System: Windows 10

**Comment by NathanLovato** [comment]
Fixed in a1c35b092d9397b7eaa701ad8a5c993e9acf84c5
