### ISSUE TITLE
English Contributing.md

### ISSUE THREAD

**Issue by MoppyDev** [GDQuest/learn-gdscript#493]
When looking to contribute to the learn-gdscript repo, github recommends a visit to the contributing.md.

The contributing.md file is in russian currently. It would be helpful if there was an english version to state the guidelines of contributing to this project.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/31117299/162859457-a72ab197-f763-4866-a455-3bcbeb8c893f.png">

https://github.com/GDQuest/learn-gdscript/blob/f41ca69344aeae63ab3e5384e7640da4111100f0/CONTRIBUTING.md

**Comment by NathanLovato** [comment]
Closed with 60431acc92fff13b29618593444406e9bafd7f79
