### ISSUE TITLE
Add pattern match for error "Can't get index ... on base ..."

### ISSUE THREAD

**Issue by markicoder** [GDQuest/learn-gdscript#499]
Describe the bug
if you make a myuscula in practice it comes out that it is wrong and also the error of "we have not covered this error"

To Reproduce
Steps to reproduce the bug:
1. Go to the practice
2. do it corect but put one capital leter
3. click ''run''
4. See the error

Information about the version and device
 I'm using the operating system windows 7 and the newest version
 for the browser i use microsoft edge

screnshots
![error of capital leters](https://user-images.githubusercontent.com/104135937/164703579-d7c9b781-86bb-47dc-bf7c-f45899b8045f.png)

**Comment by NathanLovato** [comment]
It seems we already do have explanations for this error but the error message pattern match doesn't catch this one.

> do it corect but put one capital leter

Note that if you use a capital letter, your code's not correct anymore. In code you must type exact names with the correct case. For the computer, `X` is different from `x`
