### ISSUE TITLE
Linux Version. Segmentation fault on Lesson 20, "Back to the Drawing Board" practice.

### ISSUE THREAD

**Issue by AlphaVDP2** [GDQuest/learn-gdscript#500]
Upon pressing Run, user's code appears to run, however the application crashes before the step it would report errors in user code.

**To Reproduce**
Steps to reproduce the bug:
1. Load up Lesson 20 and "Back to the Drawing Board" practice on Linux.
2. Add any(?) code after func run()

**Expected behavior**
A segmentation fault should result.

**Information about your device (please complete the following information):**
 - Operating System: AMD Pop OS 21.10, AMD Ryzen 9 4900HS
 - Build: learn-godot-gdscript-linux-release.zip (version 2)

**Terminal Output**
ERROR: Can't take value from empty array.
   at: back (core/array.cpp:132)
Segmentation fault (core dumped)

**Comment by andy-000** [comment]
I'm also using linux (Mint) and I got an issue with this lesson. 
Don't know if it is related to this, but I can't successfully complete the practice. 

I get "ERROR: At least one of the rectangles does not have the expected size" even if I copy the suggested solution. I tried it by increasing the jump.x but that doesn't help.

**Comment by AlphaVDP2** [comment]
Clone the repo and running the code in the Godot editor, points more specifically to the problem:
Godot points to line 23 of "TestsDrawingInLoops.gd" for the error, with the debugger stating: 
Invalid call. Nonexistent function 'is_empty' in base 'Nil'.

**Comment by NathanLovato** [comment]
This should be fixed now, the issue had to do with an older build using Pool arrays or something, and they had a feature that worked in debug builds but caused segfaults in release builds.

I tested with the latest builds and it doesn't happen anymore. If it does for you please let me know and we´ll reopen the issue.

**Comment by NathanLovato** [comment]
This should be fixed now, the issue had to do with an older build using Pool arrays or something, and they had a feature that worked in debug builds but caused segfaults in release builds.

I tested with the latest builds and it doesn't happen anymore. If it does for you please let me know and we´ll reopen the issue.
