### ISSUE TITLE
Instantly moving the turtle to a different position - Code doesn't match the action

### ISSUE THREAD

**Issue by HPCR-SD** [GDQuest/learn-gdscript#502]
**Issue description:**
In this section only move_forward and jump are used, yet the turtle doesn't draw the 2nd and 3rd line forward, but at an angle. No introduction of this was done or talked about in this section and therefore would also mean that rotate is missing.

Of course simply adding rotate into the code and rotating the turtle (30 degrees?) would resolve this disconnect between the code and the turtles actions and would fix the visual confusion as well.

**Comment by NathanLovato** [comment]
Do you remember in which section or lesson this issue was about? You can copy paste the URL when using the browser version to point at the lesson or practice with the issue you want to report.

**Comment by NathanLovato** [comment]
Closing due to missing info, but please note that if you see this and add the missing info we'll reopen and look into the issue
