### ISSUE TITLE
Lesson 6 - Practice - Drawing corners of different sizes - Jump, but no jump code - No length value mention - General Confusion

### ISSUE THREAD

**Issue by HPCR-SD** [GDQuest/learn-gdscript#503]
**Issue description:**

In this practice you add length as a parameter and use what it's set to in the function call (outside our visibility) to draw a corner. 
         Having no mention of lengths value makes this a slightly confusion practice. I don't believe the student needs to be able to set it but a mention in instructions of what it's value is or even to just not worry about it's value will be helpful

When the first corner is created the turtle jumps and this is not in the code. At this time a second corner is made and is smaller. This starts to add a lot of confusion, where is this happening? What determined it's value of the smaller concern and where is the code to make that corner? So many questions come into place and the only thing surrounding this that makes some sense is the name of the lesson. 

The student didn't write the code and theres no mention of that code nor is it visibly pre-written, and this is clean, but should be mentioned to prevent confusion about what the student has done.

**Comment by HPCR-SD** [comment]
The very next practice is basically the same idea except add in that you've done the same with with angle as you did with length

**Comment by NathanLovato** [comment]
This is not exactly a duplicate but it's the same problem as issue #72. So I'll close this and keep #72 open - addressing it is the way to address this too. Thanks for the report.
