### ISSUE TITLE
Lesson 20 - Back to the drawing board - Impossible solution

### ISSUE THREAD

**Issue by HPCR-SD** [GDQuest/learn-gdscript#505]
**Describe the bug**
Given solution doesn't satisfy checks as it in itself is incorrect leaving every square overlapping the previous square on the left side. This could be by design, but I consider it overlapping and it still doesn't clear all checks, but even with what improvement made to correct it is not enough to satisfy the checks.

**To Reproduce**
Given Solution:
var rectangle_sizes = [Vector2(200, 120), Vector2(140, 80), Vector2(80, 140), Vector2(200, 140)]

func run():
	for size in rectangle_sizes:
		draw_rectangle(size.x, size.y)
		jump(size.x, 0)

Corrected Solution: (may not be best but is an example)
var rectangle_sizes = [Vector2(200, 120), Vector2(140, 80), Vector2(80, 140), Vector2(200, 140)]

func run():
	for size in rectangle_sizes:
		draw_rectangle(size.x, size.y)
		jump(500, 0)

**Expected behavior**
Check would clear for rectangles not overlapping and that the solution would be a viable solution

**Screenshots**
Can't clearly show you all aspect of this and instead of uploading 4 - 6 screen shots to try and show everything I think it's pretty clear once you go and try it at the very least the solution given definitely shouldn't be the solution.

**Information about your device (please complete the following information):**
 - Operating System: [e.g. iOS, Windows] Windows 11
 - Browser: [e.g. Chrome, Safari] Vivaldi (Chromium) - Using Windows App instead though

**Additional context**
Nothing additional to add

**Comment by NathanLovato** [comment]
Actually it's already fixed, just not part of the stable release it seems. You can try using the staging version of the app: https://gdquest.github.io/learn-gdscript/staging/#course/lesson-20-looping-over-arrays/practice-clsFcSrG.tres
