### ISSUE TITLE
Animated images overlapping the issue window

### ISSUE THREAD

**Issue by pareylook** [GDQuest/learn-gdscript#506]
**Describe the bug**
Animated images overlapping the issue window

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'lesson 9'
3. Scroll down to 'any animated images'
4. Try to "report an issue"

**Screenshots**
<img width="653" alt="Screenshot 2022-04-29 at 23 48 27" src="https://user-images.githubusercontent.com/10572103/166068211-d8c64cb8-0df7-428f-ae86-52b6a3a99cd0.png">

**Information about your device (please complete the following information):**
 - Operating System: osX
 - Browser: Firefox

**Comment by NathanLovato** [comment]
Fixed along with #534
