### ISSUE TITLE
Lesson 9 Health bar haven't limitations

### ISSUE THREAD

**Issue by pareylook** [GDQuest/learn-gdscript#507]
**Describe the bug**
You can increase or decrease the health variable without limitations 

**To Reproduce**
1. Go to 'Lesson 9'
2. Click on 'take_damage(25) or heal(25) buttons many times'

**Screenshots**
<img width="790" alt="Screenshot 2022-04-29 at 23 48 53" src="https://user-images.githubusercontent.com/10572103/166069089-f5a43d31-a752-499a-bd48-d80cb9f5f1b9.png">
<img width="1050" alt="Screenshot 2022-04-29 at 23 48 42" src="https://user-images.githubusercontent.com/10572103/166069107-addd9c23-c4f2-4de2-b12e-16792ab4a634.png">

**Comment by pareylook** [comment]
UPD. In lesson 13 I met an explanation about this. But it looks very weird without context

**Comment by NathanLovato** [comment]
It's mentioned in lesson 9 too and done on purpose, you probably just missed it. Also, it matches the code shown as the code only increases the health value.
