### ISSUE TITLE
Look into adding Cmd C Cmd X Cmd V shortcuts for macOS users in the browser

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#509]
In the browser, the app can't know if a user is on macOS. So copy-paste shortcuts use Ctrl instead of Cmd. We should look into adding Cmd shortcuts for mac users - as most keyboards don't have the key, this change will benefit mac users and be transparent to others.

We've just got to see if we can somehow add the shortcuts to the TextEdit fields. Iirc it exposes the necessary functions.

**Comment by pixelclef** [comment]
I came here to comment on this issue.

If the editor requires Ctrl, then perhaps ignoring Cmd keys is better. I lost _seconds_ of code! Heh.

**Comment by NathanLovato** [comment]
No, we can actually add the Cmd shortcuts and because this button is not on non-mac keyboards the shortcuts would just work with either Ctrl or Cmd for mac users. That's a relatively easy contribution a mac Godot user could make actually.
