### ISSUE TITLE
Text size issues

### ISSUE THREAD

**Issue by Maltavius** [GDQuest/learn-gdscript#514]
**Describe the bug**
I'm on a 2560x1440 screen, if I maximize the window, even with the smallest font size it's too big.
If I have the application in Windowed mode I can only have it in the 16:9 ratio and the minimum text size is then too small and squished.

Whitespace between rows/paragraphs are too big 

Fullscreen
![image](https://user-images.githubusercontent.com/10133945/167098985-f28ddc56-dbfa-43a6-ae9a-fa1726b40014.png)

Windowed
![image](https://user-images.githubusercontent.com/10133945/167099026-50eae285-b574-46da-8320-0fd6ca1bd3a4.png)

**Expected behavior**
Smaller text in fullscreen
The text not to be squished in window mode

**Screenshots**
If applicable, drag and drop screenshots here to help explain your problem.

**Information about your device (please complete the following information):**
```
██████████████████  ████████   Manjaro
██████████████████  ████████   ----------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Kernel: 5.17.1-3-MANJARO 
████████            ████████   Uptime: 9 days, 3 hours, 43 mins 
████████  ████████  ████████   Packages: 1664 (pacman), 35 (flatpak) 
████████  ████████  ████████   Shell: bash 5.1.16 
████████  ████████  ████████   Resolution: 2560x1440 
████████  ████████  ████████   DE: Plasma 5.24.4 
████████  ████████  ████████   WM: KWin 
████████  ████████  ████████   Theme: Breath2 2021 Light [Plasma], Breath-Dark [GTK2/3] 
████████  ████████  ████████   Icons: Papirus-Dark [Plasma], Papirus-Dark [GTK2/3] 
████████  ████████  ████████   Terminal: yakuake 
████████  ████████  ████████   CPU: Intel i7-6700K (8) @ 4.400GHz 
                               GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT 
                               Memory: 12789MiB / 32040MiB 
```

**Comment by Maltavius** [comment]
On Fri, 6 May 2022, 13:17 Nathan Lovato, ***@***.***> wrote:

> If I get it right, there are three things in this issue:
>
>    - You'd like to be able to make the text smaller,
>    -
>
> Yes. It's like playing s console game on the PC right now.

>
>    -
>    - You'd like less vertical space between paragraphs. Basically you'd
>    like the text to be denser.
>
> At least that the vertical space also scales with text size.


>    - And then the text is blurry in windowed mode at this resolution
>
> Are you using the desktop Linux release, or is this with a web browser? It
> looks like the desktop build, but if so, we're already using the 2D render
> scale mode, which should update the render resolution as you change the
> window size.
>

In using the desktop release, I tried finding a version number, but
couldn't.
I blevie the Text size issue is present on the web as well.

But it only scales so far. I can't for instance have it be top to bottom on
the left/right side of my screen. Then the contents would be in the middle
with black bars above and below.

**Comment by NathanLovato** [comment]
For blurry text, let's try to address it through #381. I can't reproduce the issue on Linux or Windows so not sure why it's happening for you.

The spacing between lines is intentional right now, to remove it you have to remove all the line returns.

For the text size, I'll update the slider shortly to let you reduce it further.
