### ISSUE TITLE
Lesson 11: Rotating Using Delta

### ISSUE THREAD

**Issue by kuri-majo** [GDQuest/learn-gdscript#515]
**Describe the bug**
In Lesson 11 - Rotating Using Delta, it does not matter what value I set the radians in the rotate function to, the check whether rotation speed is 2 radians per second always passes. 

**To Reproduce**
Steps to reproduce the bug:
1. Go to Lesson 11 - Rotating Using Delta
2. Enter the following: 
   func _process(delta):
      rotate(0.2 * delta)
3. Click 'Run'
4. See the second check pass (Rotation Speed Is 2 Radians Per Second

**Expected behavior**
The check should fail if rotation speed is not set to 2 radians. 

**Screenshots**
![scrshot](https://user-images.githubusercontent.com/25233470/167260580-7844fc52-fdf3-4d45-9124-ccc3f61625bb.PNG)

**Information about your device (please complete the following information):**
 - Operating System: Windows 10
 - Browser: Firefox 100.0

**Comment by NathanLovato** [comment]
Closed by 6256081abeb601d561051ad304172e216ba6dc02
