### ISSUE TITLE
Lesson 15 - modulo sign can disappear due to text wrapping, depending on the font size

### ISSUE THREAD

**Issue by seancwall** [GDQuest/learn-gdscript#517]
In lesson 15, the modulo lesson, the code block for the `roll_dice()` function is not displaying the '%' operator.  I've attached a screen shot showing the problem as well as the log.  I think it may be an issue related to the font size used.

<img width="937" alt="Screen Shot 2022-05-13 at 10 46 59 AM" src="https://user-images.githubusercontent.com/3537902/168308920-1ca5289e-0a01-4ef3-b173-65ac6f32fbe6.png">

[gdquest-1652453007637.log](https://github.com/GDQuest/learn-gdscript/files/8688843/gdquest-1652453007637.log)

**Comment by NathanLovato** [comment]
Thanks, it's unfortunately linked to #99 and due to text wrapping issues in Godot. It's not something we can fix easily - Godot 4 and its new text rendering should hopefully fix this, but for now, we don't have a great solution for this.

**Comment by NathanLovato** [comment]
Actually as it's the same issue as #99, closing this one to avoid duplicate issues
