### ISSUE TITLE
Lesson 26 - unit coordinates have inconsistent values

### ISSUE THREAD

**Issue by seancwall** [GDQuest/learn-gdscript#518]
In the dictionary `unit_cells` in lesson 26, assuming the coordinates of the top left cell are `(0, 0)`, then the coordinates of the `"robot"` units should be `(1, 0)` and `(3, 0)`.  The `"turtle"` is correct at `(2, 2)` in this scheme.  I think that's consistent with other cell grids in the lessons.

<img width="942" alt="Screen Shot 2022-05-13 at 1 32 35 PM" src="https://user-images.githubusercontent.com/3537902/168375412-1a0d74a3-157b-4543-bc39-587b4fee4274.png">
.

**Comment by NathanLovato** [comment]
I fixed this yesterday I think, but forgot the commit. Anyway it'll be fixed with the update.
