### ISSUE TITLE
Add a close button to the Practice completed window

### ISSUE THREAD

**Issue by pycbouh** [GDQuest/learn-gdscript#52]
From backer's comments:

> I've completed the first lesson Practice, and I don't like that it pushes me out of the lesson as soon as I press Play. I wanted to close the Well done! dialog and review the execution status of the program (in particular, whether the print("Welcome!") line had been printed to the Output console), but the "Got it!" button closes the environment and I need to navigate back to the lesson and re-read the full text and answer all the quizzes to access the practice environment again.

And they have a point. So I think we could just add a button to close the popup and remain in the practice, while still tracking that practice as completed. We can maybe even add another button to the bottom of the practice screen itself to go to the next practice/lesson that is unlocked after you complete it once.

**Comment by NathanLovato** [comment]
Yup our tester said the same. I thought I have logged an issue for that, might have forgotten.

**Comment by dialmove** [comment]
While you're at it, could you please also add a button to the _previous_ practice as well? I solved lesson #3 practices out of order, starting with "Make the robot upright", and I was surprised when completing it that it moved me to lesson #4 while I had still one more practice to go.

(Also, there's an off-by-one error in the top-left lesson title) ;-)

![image](https://user-images.githubusercontent.com/3824360/147691111-f66187ba-8420-4358-a09b-cdc945825e25.png)

![image](https://user-images.githubusercontent.com/3824360/147691180-0c82cede-f63f-4761-8bce-91ae170d968c.png)

**Comment by pycbouh** [comment]
Sure, we should probably add some indication that the user has unfinished practices before moving them to the next lesson, and allow them to go back to them and finish them.

**Comment by xix-xeaon** [comment]
I think you shouldn't even be able to "move on" right away. You want the student to review the work they did (now that they got it right) Before moving on. You should only have a close button, and then a button to move on to the next part / lesson should be easy to find but also "in the corner" or something.
