### ISSUE TITLE
Minor issue in content of Lesson 18 "Introduction to for loops"

### ISSUE THREAD

**Issue by NPException** [GDQuest/learn-gdscript#521]
**Issue description:**
In lesson 18 "Introduction to for loops", right at the beginning of the section "Using a for loop instead of a while loop", the code example using the for loop is not equivalent to the one using the while loop. It would behave wrong if `cell.x` is not `0` when the function is called.

![image](https://user-images.githubusercontent.com/6052580/169087463-38ee01f3-e079-467a-add1-17b0f0b97c4d.png)

It could be this instead:

```gdscript
func move_to_end():
	for number in range(cell.x, board_size.x - 1):
		cell.x += 1
```

**Comment by NPException** [comment]
I see how this would add unnecessary cognitive load for a new programmer though, so please just close if it was intentionally so.

**Comment by Remixful** [comment]
There's another error here too.., we don't need to subtract 1 from board_size.x because the range function already does that.

**Comment by NPException** [comment]
> There's another error here too.., we don't need to subtract 1 from board_size.x because the range function already does that.

If I'm not mistaken, subtracting 1 is needed to avoid overshooting the board. Example: without it, when `cell.x` is 0 and the board width is 3, we would do 3 iterations of `+= 1`. Which would result int `cell.x` being 1 too large.

**Comment by NathanLovato** [comment]
It's intentional yes, and subtracting 1 is also correct
