### ISSUE TITLE
(on staging) Lesson 20, Exercise "Back to the drawing board"

### ISSUE THREAD

**Issue by NPException** [GDQuest/learn-gdscript#522]
**Describe the bug**
I tried using the following solution, and even the example solution from the task itself, but it gives an error that "at least one of the rectangles does not have the expected size"

**To Reproduce**
Steps to reproduce the bug:
1. Go to https://gdquest.github.io/learn-gdscript/staging/#course/lesson-20-looping-over-arrays/practice-clsFcSrG.tres
2. Use the following solution:
```gdscript
var rectangle_sizes = [Vector2(200, 120), Vector2(140, 80), Vector2(80, 140), Vector2(200, 140)]

func run():
	for rect in rectangle_sizes:
		draw_rectangle(rect.x, rect.y)
		jump(rect.x + 100, 0)
```

**Expected behavior**
Solution is accepted without error.

**Information about your device (please complete the following information):**
 - Operating System: Windows
 - Browser: Chrome

**Additional context**
I had a slightly different erroneous solution before, which might have contributed to the issue.
```gdscript
var rectangle_sizes = [Vector2(200, 120), Vector2(140, 80), Vector2(80, 140), Vector2(200, 140)]

func run():
	for rect in rectangle_sizes:
		draw_rectangle(rect.x, rect.y)
		jump(rect.x + 100) # missing second parameter
```
After leaving and re-entering the exercise, it worked without issue and I could no longer reproduce it.

Here's the generated error-log: [gdquest-1652891543985.log](https://github.com/GDQuest/learn-gdscript/files/8718317/gdquest-1652891543985.log)

**Comment by MeshVoid** [comment]
Same, it's broken for me. Can't complete chapter 20 because of that, doing it in online version of the application. https://gdquest.github.io/learn-gdscript/#course/lesson-20-looping-over-arrays/practice-clsFcSrG.tres

**Comment by NPException** [comment]
> Same, it's broken for me. Can't complete chapter 20 because of that, doing it in online version of the application. https://gdquest.github.io/learn-gdscript/#course/lesson-20-looping-over-arrays/practice-clsFcSrG.tres

@MeshVoid Here's a workaround that worked for me: I went back to a previous lesson via the menu in the top left:
![image](https://user-images.githubusercontent.com/6052580/169636980-fdd9e74a-c73a-4557-b3e9-e8330c6132c5.png)
After that, I selected chapter 20 again and it worked that time.

**Comment by MeshVoid** [comment]
> > Same, it's broken for me. Can't complete chapter 20 because of that, doing it in online version of the application. https://gdquest.github.io/learn-gdscript/#course/lesson-20-looping-over-arrays/practice-clsFcSrG.tres
> 
> @MeshVoid Here's a workaround that worked for me: I went back to a previous lesson via the menu in the top left: ![image](https://user-images.githubusercontent.com/6052580/169636980-fdd9e74a-c73a-4557-b3e9-e8330c6132c5.png) After that, I selected chapter 20 again and it worked that time.

Thank you very much! It worked!

**Comment by jackwkinsey** [comment]
Just ran into this issue as well. It seems that if you don't get the solution right the first time the second check always fails until you go to another less via the navigation menu and then come back to the practice. Then entering the correct solution has no issue.

So the bug is still there, but the workaround of going to another lesson and coming back to this practice seems to work.

**Comment by Jaune9** [comment]
![image](https://user-images.githubusercontent.com/47558505/172046984-44c1d80f-8a70-4393-97f0-f2047947e589.png)
Same issue, with notably the error message not giving the proper hint.

**Comment by Euphoreka7** [comment]
same issue
