### ISSUE TITLE
Lesson 24. Incorrect text in "Using the right crystal" practice's goals

### ISSUE THREAD

**Issue by robherre** [GDQuest/learn-gdscript#527]
In Lesson 24, practice "Using the right Crystals", when it says:

"Call the **use**() function with the item as an argument to use an item. For example, you can use the first item by calling **use**(inventory[0])."

It must say:
"Call the **use_item**() function with the item as an argument to use an item. For example, you can use the first item by calling **use_item**(inventory[0])."

And when it says:
"They want to use the pink and yellow crystal(...)"
there's no pink crystal, in my computer they have a color between red and orange.

**Comment by NathanLovato** [comment]
This is already fixed but not available in the stable release yet.
