### ISSUE TITLE
enhancement :lesson 1 show the result in the output box

### ISSUE THREAD

**Issue by survivant** [GDQuest/learn-gdscript#53]
at the end of the lesson 1, when you click on RUN, it should at least show the message "Welcome!" output in the output screen before showing the modal popup.
![image](https://user-images.githubusercontent.com/191879/147686909-afd90bee-1a65-47e3-835c-fc8a6c68673b.png)

or maybe show the "success popup" at the center With on the right the robot box and bellow the output box with the message.

**Comment by pycbouh** [comment]
Thanks for the report. We'll address this with https://github.com/GDQuest/learn-gdscript/issues/52 by introducing a button to close the "Well done" popup so you can inspect the code, the output, and play around with it as you wish.

Adding the output console to the popup would rarely be useful during the course, so we think it's the best course of action.
