### ISSUE TITLE
Lesson 11. Time Delta - Moving in a circle using delta: minor issue with not passing

### ISSUE THREAD

**Issue by EljestOwl** [GDQuest/learn-gdscript#531]
**Describe the bug**
The practical lesson started with a "pass" a line below "func _process()". After testing i found that it was preventing a the first check, "Movement Is Time Dependent", from turning green.

**To Reproduce**
Steps to reproduce the bug:
It was there when i first loaded the lesson.

**Expected behavior**
Up intill this point there had never been a "pass" line in the other lessons. As soon as i remove that line it works.

**Screenshots**
![Skärmbild 2022-06-03 134929](https://user-images.githubusercontent.com/106814558/171848069-5e4e199c-3528-4fec-9bcc-44455dabc982.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows 10 x64

**Additional context**
[2022-06-03-13-40.log](https://github.com/GDQuest/learn-gdscript/files/8832025/2022-06-03-13-40.log)

**Comment by NathanLovato** [comment]
Seems that you're using an older release, there's no pass line anymore
