### ISSUE TITLE
mobile browser wrongly detected

### ISSUE THREAD

**Issue by davidak** [GDQuest/learn-gdscript#532]
**Describe the bug**

I get the message:

>You appear to be using a mobile browser. This application is not suitable for small screens and portrait orientation. If you want to continue, it's at your own risk!

But i'm using Google Chrome on desktop Linux.

**To Reproduce**
Steps to reproduce the bug:
1. Go to https://gdquest.github.io/learn-gdscript/ (also happens on https://gdquest.github.io/learn-gdscript/staging/)
4. See message

**Expected behavior**
Desktop Browser should not be detected as Mobile Browser.

**Screenshots**

![Screenshot from 2022-06-03 21-29-15](https://user-images.githubusercontent.com/91113/171936292-8348fc05-64f3-4f9d-8aac-781237e4086f.png)

**Information about your device (please complete the following information):**
 - Operating System: NixOS 22.05beta67.6efc186e607 with Pantheon Desktop
 - Browser: Google Chrome 101.0.4951.64

**Additional context**
I have checked that i don't send a custom user-agent.

Feel free to give me further instructions to help debug this.

**Comment by NathanLovato** [comment]
It depends on your window size, we use a media query. Is this taking your full desktop or did you make the window smaller? Or do you perhaps have a small laptop?
