### ISSUE TITLE
Windows Version 24 Using right crystals practice, wrong function name.

### ISSUE THREAD

**Issue by Cordilius** [GDQuest/learn-gdscript#533]
**I'm submitting a...**

- [ x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
Just a mislabeled function in the Goals description, on lesson 24 practice "Using the right crystals"

**What is the expected behavior?**
currently listed as 'use()' but the correct name should be 'use_item()' according to the solution

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.**

**Comment by NathanLovato** [comment]
You might have downloaded the app right before I fixed this, it should already be fixed, see #527
