### ISSUE TITLE
Enhancement : add "reset to default" in the customize settings

### ISSUE THREAD

**Issue by survivant** [GDQuest/learn-gdscript#54]
in the customize settings window you should have a "reset to default values".  Will be useful when you will have lots of settings and in this course, we assume that the people are not to familiar with programing so a fallback to the default values could help them.

![image](https://user-images.githubusercontent.com/191879/147687439-11dda9c6-21e3-4d60-ab6b-7fcd8650974b.png)

**Comment by pycbouh** [comment]
> Will be useful when you will have lots of settings

Sure, but keep in mind that we don't really have many settings now and we don't have more settings planned. Those that are already there don't really require such functionality by themselves.

**Comment by NathanLovato** [comment]
Perhaps if we add keyboard shortcut customization at some point (after things like #40) but there won't be many settings. For now we don't have any other setting planned. Do you still think this would be useful?

**Comment by survivant** [comment]
Not at this point, but we never know if the application becomes more
complex

Le dim. 2 janv. 2022, 14 h 46, Nathan Lovato ***@***.***> a
écrit :

**Comment by NathanLovato** [comment]
Alright, I'll close for now then. If and when we add more settings and need a feature to reset them, we'll add it along the way.
