### ISSUE TITLE
Practice descriptions get cut off with larger fonts

### ISSUE THREAD

**Issue by Kazeheki** [GDQuest/learn-gdscript#543]
**Describe the bug**
Not sure whether this fits better under content but my reasoning for bug was the display is *not working right*.

The description of the practice "Reducing Damage At Higher Levels" of lesson 14 is moved to the left or too big and thus not fully in the main "window" as the other practices.

This happens only if you use the bigger font-size option from the application settings.

**To Reproduce**
In the app-settings choose the biggest "Text Size".
Open lesson 14, practice "Reducing Damage At Higher Levels".

**Expected behavior**
Fully visible and contained practice description like in the other lessons/practices.

**Screenshots**

Problem (with comparison to working other practice):
![lesson14Practices](https://user-images.githubusercontent.com/11597609/172633237-77424b7d-108d-4192-88b8-440507f38cb4.gif)

Settings:
![grafik](https://user-images.githubusercontent.com/11597609/172631082-7770e3ff-8a0a-458f-92aa-4e10c808f7bf.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows
 - Browser: Firefox + Chrome (tested with both)
 - Version information: 2022/06/03 19:12:28 | staging::6256081abeb601d561051ad304172e216ba6dc02

**Comment by Relected** [comment]
hello, i also stilll have this problem right now on lesson 8 practice 3

![image](https://user-images.githubusercontent.com/61807003/185482249-0fd9aa8d-94bb-4cb5-9671-a08ee637938c.png)

**Comment by NathanLovato** [comment]
Indeed, it's caused by a different thing, just pushed a fix (but it's not in the online release yet)
