### ISSUE TITLE
Add keyboard focus and scrolling support

### ISSUE THREAD

**Issue by dialmove** [GDQuest/learn-gdscript#55]
**Describe the bug**
Keyboard standard scrolling functions don't work (namely: up and down arrows, page up and page down keys).

Also the scroll bar has two [usability papercut bugs](https://en.wikipedia.org/wiki/Paper_cut_bug), making it quite hard to scroll the page with a mouse without a mousewheel, or for users with disabilities using an unconventional pointer:
- The scroll bar is really thin, making it a small target to point an click.
- The scroll bar does not run all the way to the edge of the screen, making it impossible to use the ["Fitt's Law infinite width" trick](Fitts' Law and Infinite Width) of maximizing the window and throwing the mouse to the edge in order to scroll.

**To Reproduce**
Steps to reproduce the bug:
1. Open a lesson page. The page content should get the interface focus.
2. Without using the mouse to focus, press down arrow and up arrow keys. The page does not scroll.
3. Press page down and page up. The page does not scroll.
4. Maximize the window.
5. Move the mouse to the right edge of the screen, and drag up and down. The page does not scroll.

**Expected behavior**

-With the up and down arrow keys, the page should scroll by one line.
-With the page up and page down keys, the page should scroll by about half of the screen (adjusted with respect to the screen size, so that on small screens the page does not scroll by more than one screen).
-With the pointer at the right edge of the screen, dragging up and down should scroll the page.

**Screenshots**
If applicable, drag and drop screenshots here to help explain your problem.

There is a gap between the scroll bar and the screen edge, and the bar is too narrow.
![image](https://user-images.githubusercontent.com/3824360/147690260-1f9662ac-d529-4117-8176-f0b987a92a62.png)

The standard browser scroll bar is wider and it is placed all the way to the screen edge on a maximized window, having effectively infinite width (or adequate width when the window is not maximized):
![image](https://user-images.githubusercontent.com/3824360/147689939-34fba84e-aa9f-4740-a36f-14a251a25049.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows 10
 - Browser: Chrome

**Comment by pycbouh** [comment]
Thanks for your report!

The scrollbar not aligning with the side of the window visually is an aesthetic choice. It doesn't have to, as long you can interact with it. And to that end, we can make sure that the area for interactivity is big enough that throwing your cursor with a touchpad to the edge still works.

**Comment by dialmove** [comment]
`> The scrollbar not aligning with the side of the window visually is an aesthetic choice. `

Yeah I don't mind that it is visually narrow, but I'm concerned that it doesn't have a wide mouse target. Allowing the mouse to drag it when the pointer is a few pixels off _might_ be a valid solution - though it seems trickier than it sounds, since the number of pixels separating the bar from the edge is a variable amount depending on screen size, resolution and browser zoom level; so it is not guaranteed that this drag area will always reach the window's edge.

**Comment by pycbouh** [comment]
> since the number of pixels separating the bar from the edge is a variable amount depending on screen size

Keep in mind that this is an application, not a web page. We only have control within the frame of the application, so yes, on wider screens it can be far from the side of the screen, which is actually good. I don't want to drag my mouse across the entirety of my ultrawide display 🙃 But on screens up to 1080p it should be aligned at all times, I think.

We could make the app adjust to any screen resolution, in theory, but for some reason we are using fixed rendering size and rely on scaling instead. I'm not entirely sure, why, so we may need to rethink that. Godot can, of course, support any resolution and aspect ratio.

**Comment by dialmove** [comment]
The problem will happen in an app window as well if different people have different-sized screens. A scroll bar that is near the window's edge, _but not quite_, is a classical usability paper cut.

If you are using a fixed content column width, maybe the scroll bar should be located at the side of the content column? Therefore, near the center of the screen, instead of near the edge? This way, the mouse has much less travel and by Fitts' law it's easier to target.

**Comment by pycbouh** [comment]
I don't mind having it closer to content, makes perfect sense to me. But, a disclaimer, I also almost never use scrollbars.

> The problem will happen in an app window

In a window you have to hunt it either way, there is no physical bound that would stop the mouse, like the edge of the screen would. So we can only address it by having it wider (which we should do regardless). I was just saying that for that particular scrollbar we can have it _much_ wider by giving it bigger hitbox rather than making it itself too wide. After all, no matter how big you make the elements, humans are bad at judging the distance all the time, and it's a good practice to have a hitbox that is bigger than the visual element.

**Comment by dialmove** [comment]
`> In a window you have to hunt it either way, there is no physical bound that would stop the mouse, like the edge of the screen would.` 

I know, I was thinking of running the app on maximized or full screen mode. Full-page scrollbars are expected to be draggable from the edge in those modes (even if visually they are placed a few pixels afar).

`> After all, no matter how big you make the elements, humans are bad at judging the distance all the time, and it's a good practice to have a hitbox that is bigger than the visual element.
`
Sure. I was pointing out that in maximized mode, the hitbox placement should be calculated from the edge of the screen which is a fixed known position, not from the visual center or edge of the scrollbar, which may be affected by styling or layout concerns such as zoom level or pixel density.

**Comment by NathanLovato** [comment]
The commit above should complete all the requirements for this task. My teammate had covered the scrollbar and mouse part, and this adds focus-grabbing. We don't have full keyboard navigation support at the moment. If someone needs that, the scope would be a bit larger in scope and a bit challenging (tab and ctrl tab are typical to navigate but you need to insert tabs in code for indentation).

Anyway, for now, the experience is a bit better at least!
