### ISSUE TITLE
Lesson 10: Creating Circular Movement

### ISSUE THREAD

**Issue by ricardovandervlag** [GDQuest/learn-gdscript#551]
**Bug description**
`move_local_x()` function isn't checked by answer.
 
**To Reproduce**
Steps to reproduce the bug:
1. Go to `Lesson 10: Creating Circular Movement`
2. Only fill in `rotate(0.05)` / add `move_local_x()` without parameter / comment `#move_local_x()`
3. Click Run

**Expected behavior**
Condition not met and task failed.

**Screenshots**
![image](https://user-images.githubusercontent.com/22623673/173103315-06038229-a213-42bd-b0c0-a67ab5cdfd82.png)

![image](https://user-images.githubusercontent.com/22623673/173103743-faa97efa-beb4-41d9-8b14-400f69ab4cb3.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows 11 Pro
 - Application type: exe version (not tested in a browser)

**Comment by NathanLovato** [comment]
Thanks for the report, it was a different bug but it's good that you brought it up

**Comment by ricardovandervlag** [comment]
You're welcome. Excellent application btw :)
