### ISSUE TITLE
Lesson 20, Practices, Back To The Drawing Board, Crash on check

### ISSUE THREAD

**Issue by OleGraf** [GDQuest/learn-gdscript#552]
**Describe the bug**
The second Practice of the 20. Lesson ("Looping over Arrays") crashes upon pressing "Run".
The Splash Screen "Running your code..." shows for a short time and the Programm closes automatically.

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'Lesson 20. Looping over arrays'
2. Click on 'Practice' - Back To The Drawing Board
3. Fill in some Code (with a loop, as requiered by the test)
4. Click on 'Run'
5. Wait a few secondes for the Splash Screen and the program closes.

**Expected behavior**
Check if the code is correct and depending of the fulfilled requierments, green checkmarks on the left side.

**Screenshots**
14sec clip: https://youtu.be/iCQg8ob5oFw

**Information about your device (please complete the following information):**
 - Operating System: [Windows 10 Pro, 21H2] OS build: 19044.1706
 - Browser: [N/A] Stand Alone Programm

p.s. love the project

**Comment by NathanLovato** [comment]
It should be already fixed. Could you please download and try with the latest version? It was just released 25 minutes ago: https://gdquest.itch.io/learn-godot-gdscript

**Comment by OleGraf** [comment]
Can confirm has been fixed.
Had the version from yesterday.

**Comment by NathanLovato** [comment]
Thanks!
