### ISSUE TITLE
Lesson 24 Using The Right Items

### ISSUE THREAD

**Issue by AdamDee64** [GDQuest/learn-gdscript#553]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
The correct solution doesn't work. The output window shows an error that the script has an error but the script verifier didn't catch it

**What is the expected behavior?**

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 
start exercise
on an indented line after func pick_items(): type use_item(inventory[6]) 
on the next indented line type use_item(inventory[8]) 
click on run button

or click on solution button, use solution, and run

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information** 

![screenshot-lesson-24](https://user-images.githubusercontent.com/101023742/173196680-7b00046c-104c-4c11-aa28-7ddcd97080de.png)
[gdquest-1654964377773.log](https://github.com/GDQuest/learn-gdscript/files/8884367/gdquest-1654964377773.log)

**Comment by NathanLovato** [comment]
Just fixed it moments ago, you'll need to download the latest version when it's live (it can take 10+ minutes if a rebuild fails on github). Closed by 5703c7540a537af992f34bb1984461a475af2e18
