### ISSUE TITLE
Hey there, lesson 24: Using the right items is broken

### ISSUE THREAD

**Issue by melodymetall** [GDQuest/learn-gdscript#554]
**Describe the bug**
Hey there, it is impossible to run the code since I got an unidentified error. It appears that inventory array is empty. I tried to fill it up but it didn't work.

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'Lesson 24 under the practice section called Using the right items'
2. Click on 'the code panel'
3. Type the code 'use_item(inventory[3]) under pick_items() func'
4. See error: 

**Expected behavior**
I'd expect the result: selecting the sword item

**Screenshots**
![image](https://user-images.githubusercontent.com/22403971/173201687-319353b0-bf57-45c8-9a2b-c321dc10b9d8.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows 11
 - Browser: Chrome

**Additional context**

**Comment by abumbalough** [comment]
Same issue in Firefox 101.0 on Wnidows 10 version 10.0.19044

**Comment by NathanLovato** [comment]
I fixed this yesterday night. When did you download this? And could you link me to the version you're using for testing? I'll check if the automated builds failed. Another possibility if you use the browser version is that you need to clear your cache by clicking the url line and pressing Ctrl Shift R

**Comment by NathanLovato** [comment]
Oh wait are you using the staging version? I.e. this link that ends with https://gdquest.github.io/learn-gdscript/staging/ `staging/` ? If so that might be why.

**Comment by NathanLovato** [comment]
I just triggered a rebuild for the staging version. You can alternatively use https://gdquest.github.io/learn-gdscript/ to get the latest stable release. The bug shouldn't occur anymore.

**Comment by melodymetall** [comment]
Thank you Nathan, I was using the online version https://gdquest.github.io/learn-gdscript/

I could finish the course as well, just skipped this one. It's ok since I have a good programming foundation.. Thank you for your support and quick answer. I took too long to reach your response, sorry. =)

**Comment by abumbalough** [comment]
I was also using the online staging version. Thanks for the very quick fix!

**Comment by NathanLovato** [comment]
You're welcome!
