### ISSUE TITLE
"back to the drawing board" on lesson 20 not recognising completion

### ISSUE THREAD

**Issue by dandyRoot** [GDQuest/learn-gdscript#559]
Trying to complete the test, where for loops are used to draw rectangles, code that should be successful has been put in (and checked against given solution), but the program always says the rectangles are not all the correct size. also, in experimenting, the "Jump" step was removed entirely, and the code still reported that the rectangles were *not* overlapping, even when they all started at the same position.

**To Reproduce**
in Lesson 20, test "back to the drawing board", apply the following code under the given array:

func run():
	for size in rectangle_sizes :
		draw_rectangle(size.x, size.y)
		jump(size.x + 100, 0)

turtle should complete the program successfully, but the output box will report that "at least one of the rectangles does not have the expected size"

**Expected behavior**
After the turtle completes its path, this should be marked as completed. as it stands, even using the given solution doesn't successfully complete the lesson

**Screenshots**
![image](https://user-images.githubusercontent.com/107350166/173230401-d96b81b0-49f1-4074-92bf-9722327e106a.png)

**Information about your device (please complete the following information):**
I'm on windows 10, using a firefox browser

**Comment by NathanLovato** [comment]
This issue's already fixed in the live version but you may have to clear your browser cache to re-download it. Please click on the address bar and press Ctrl Shift R

**Comment by dandyRoot** [comment]
ahh thank you, i scanned back a bit but didn't see anyone else mention it, so probably not far back enough

i'm starting out with programming and this has been a rewarding resource so far
