### ISSUE TITLE
Lesson 10: app crashes if running a second time

### ISSUE THREAD

**Issue by Fallenhero83** [GDQuest/learn-gdscript#560]
**Describe the bug**
App Freezes if practice is run for a second time

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'Lesson 10: Creating Circular Movement'
2. Click on 'Run a second time'

**Information about your device (please complete the following information):**
 - Operating System: Windows 10
 - Browser: Chrome

**Comment by Fallenhero83** [comment]
All happened on Lesson 11: Time Delta - Moving in a Circle Using Delta

**Comment by MissLav** [comment]
having the same issue

**Comment by MissLav** [comment]
move_local_x in lesson 11 crashes for me on firefox linux

**Comment by NathanLovato** [comment]
Could you please share the exact code you used that caused the issue?

**Comment by MissLav** [comment]
heres a screenshot of it being frozen 
![image](https://user-images.githubusercontent.com/51702517/178799761-0e506852-3557-4589-bd1c-d417baf20b80.png)

**Comment by MissLav** [comment]
also happened on one the previous tests 
![image](https://user-images.githubusercontent.com/51702517/178799963-d370e6e4-10d7-4c05-bd49-28894e4a77d6.png)
screenshot i sent  to a friend

**Comment by NathanLovato** [comment]
I could reproduce the freeze, but have no idea what's causing it. The error's not helpful, unfortunately. In the meantime, I recommend downloading one of the desktop versions; https://gdquest.itch.io/learn-godot-gdscript

**Comment by henriquelalves** [comment]
The freeze appears to  be fixed on bleeding edge, most likely because of the Debug build.

**Comment by NathanLovato** [comment]
Thanks!

**Comment by KareemFarrag** [comment]
this lesson crash on windows 10 exe when run code at full screen
