### ISSUE TITLE
Lesson 12: Typo in Example Comment

### ISSUE THREAD

**Issue by alexporth** [GDQuest/learn-gdscript#562]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
The comment reads, "This variable is defined outside of t function"

**What is the expected behavior?**
The comment should read, "This variable is defined outside of the function"

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. Open Lesson 12
2. Scroll to the example in the image.

![image](https://user-images.githubusercontent.com/4528445/174045494-06bbe0be-a26c-4fd6-81bc-fadc5671401c.png)

**Comment by NathanLovato** [comment]
It's not a typo, it's Godot's text wrapping failing. Duplicate of #99
