### ISSUE TITLE
Missing use of modulo in lesson 15?

### ISSUE THREAD

**Issue by FrankyS74** [GDQuest/learn-gdscript#563]
Windows 10 App.
Lesson 15 - Calculating a random number within a range,

The modulo operator sometimes not visible. See screenshot.

![grafik](https://user-images.githubusercontent.com/107789643/174472405-773afd7c-f899-4423-b864-a3d505004810.png)

After restarting the lesson it is.

Thank you very much for the app. It helps a lot.
Best regards.

**Comment by NathanLovato** [comment]
This is due to #99, closing as it's the same issue.
