### ISSUE TITLE
Lesson 7: "Draw Rectangles at Different Positions" doesn't recognize solution with move_forward(), etc.

### ISSUE THREAD

**Issue by antartica** [GDQuest/learn-gdscript#569]
**Describe the bug**
Doesn't recognize a correct answer done with move_forward() and turn_right() instead of draw_rectangle()

**To Reproduce**
In lesson 7 Draw Rectangles at Different Positions, enter the following program:
```
func run():
	position.x = 100
	position.y = 100
	draw_square()
	position.x = 300
	draw_square()
	position.x = 500
	draw_square()

func draw_square():
	move_forward(100)
	turn_right(90)
	move_forward(100)
	turn_right(90)
	move_forward(100)
	turn_right(90)
	move_forward(100)
	turn_right(90)
```

**Expected behavior**
The answer should be marked as correct

**Screenshots**
![lesson7drawsquaresaterror](https://user-images.githubusercontent.com/5132542/175805533-a61ae61f-9eef-416f-9056-baac8267c052.png)

**Information about your device (please complete the following information):**
 - Operating System: Linux
 - Browser: Firefox

**Comment by NathanLovato** [comment]
As mentioned in the instructions, you need to edit only the run() function. If you look at the code reference, you'll see you need to use draw_rectangle(). You're not supposed to define a new function (it's not in the practice instructions/requirements)
