### ISSUE TITLE
Automatic )

### ISSUE THREAD

**Issue by Fantoser** [GDQuest/learn-gdscript#572]
I write an "(", now the program put AFTER the cursor a ")", and so the cursor between the two, and if I write a ")" the result is "())"

Either don't write out automatically the ")" or when I write a ")" in this situation put the cursor after the already present ")" because now I have to lift my hand, go to the arrows, hit right, and I know this is not much, but still annoying. Thank you.

**Comment by dannysband** [comment]
Definitely agree this is annoying and not an issue within Godot Engine itself.
