### ISSUE TITLE
Lesson 22 discrepancy

### ISSUE THREAD

**Issue by DexLovesGames** [GDQuest/learn-gdscript#581]
At the end of the lesson, before practice it says this:
![image](https://user-images.githubusercontent.com/108374760/177018868-96dfc61a-769b-40ff-b0ae-1d48f5d9be80.png)

This implies that we should check documentation first in this practice,
but then, in the practice itself, there isn't any documentation for any functions at all.
![image](https://user-images.githubusercontent.com/108374760/177018894-8a9adba4-8e21-4c43-9373-24b57c60f429.png)

**Comment by NathanLovato** [comment]
It doesn't imply the next practice must have the panel. The practice screen is the screen in which every practice shows. But we can rephrase if that's confusing to you. Any ideas on how to rewrite that sentence? Is it OK like this?

> You can learn which functions return a value using the documentation panel in practices that have it.

**Comment by Kemeros** [comment]
> During practices, you can learn which functions return a value using the documentation panel when provided.
