### ISSUE TITLE
lesson 28 misinformation

### ISSUE THREAD

**Issue by DexLovesGames** [GDQuest/learn-gdscript#582]
I could very well be wrong here, but I think this is supposed to say "You'll likely pick one of two types for that: integer or Vector2" since you wouldn't typically use subpixels for a grid in a game, and because the example given just uses the integer 50.

![image](https://user-images.githubusercontent.com/108374760/177021228-3d8f065b-7192-4fc3-8ac0-5ef87e4dc15a.png)

**Comment by NathanLovato** [comment]
The numbers need a .0 to clear the confusion. But if you don't use strong typing, 50 is not strictly an int. It'll start as an int but will get converted automatically depending on the context like you can write a Vector2() with `50` as the coordinates - they're both floats.
