### ISSUE TITLE
"Lesson 14. Multiplying"  Crash

### ISSUE THREAD

**Issue by sweabread** [GDQuest/learn-gdscript#584]
**Describe the bug**
the program crashes to desktop while trying to run the code 

**To Reproduce**
Steps to reproduce the bug:
1.type  on line 14&15 
```
 if level >2:
    teake_damage (amount*0.5)
```
2. run

**Expected behavior**
either bring up an error in the code or bring up the popup to stay or continue to the next lesson

**Screenshots**
[2022-07-09-12-09.log](https://github.com/GDQuest/learn-gdscript/files/9077761/2022-07-09-12-09.log)

**Information about your device (please complete the following information):**
 - Operating System: Windows 10

**Comment by NathanLovato** [comment]
Could you please show me the exact practice and the complete code with all the characters written in the code editor?
