### ISSUE TITLE
Lesson 17 - Reason for moving one less than the board's size is unclear

### ISSUE THREAD

**Issue by ghost** [GDQuest/learn-gdscript#589]
The explanation that "we move one less than the board's width because the robot is already on the first cell" is unclear and makes it sound as though the robot's starting position matters (suggesting we would move two less than the board's width if the robot started on the second cell, which is not correct). If I'm understanding correctly, the actual reason we move one less than the board's width is because the equivalent robot position is one less than the board's width (or height) due to each being counted differently - A (0,0) board doesn't exist and a (1,1) board only has one square, but for the robot (0,0) means being on the first square. Which is in itself confusing, it would make far more sense if the cell variable being (1,1) meant the robot was on the first square but I don't know if it can be made to work that way.

Also, in the practice it would help if the description said that the robot's position is stored in the "cell" variable. This is shown if you scroll to the Documentation section, but it would still be easier to understand if instead of saying "The robot's current cell is Vector2(2, 0)." it said "The robot's current cell is Vector2(2, 0) and is stored in the cell variable."

**Comment by Kemeros** [comment]
I had to start printing the variable's content in the while loop to understand what was happening. I see little reason for `cell `and `board_size` to have different beginning and end positions. The -1 would not be necessary if both variables were built to go from 1 to 5. Maybe you wanted to teach people about off by one errors? It would make more sense to teach that with indexes. Maybe i'm misunderstanding the goal as well.
