### ISSUE TITLE
link to the official Godot documentation

### ISSUE THREAD

**Issue by survivant** [GDQuest/learn-gdscript#59]
suppose that I have no idea what to do in a lesson, there are the hints that can help you, but also the official Godot documentation that could give more explanations about the method and maybe with example too.  So the documentation should offer a link to external documentation (like when we are using a IDE)

![image](https://user-images.githubusercontent.com/191879/147705027-1320ba78-bcb2-4570-9197-24a86ac5cb26.png)

**Comment by NathanLovato** [comment]
This is an app for programming beginners. The Godot documentation assumes you already know how to program. So it wouldn't be a good resource to link to. See the other tasks, we have improvements planned to help users get started. If a user gets stuck with a specific practice or lesson, then they should report that and we'll address it per issue.
