### ISSUE TITLE
Modulo 0 crashes the program

### ISSUE THREAD

**Issue by IAmSamIsMe** [GDQuest/learn-gdscript#594]
When working in the modulo practices, I accidentally used modulo 0, and anytime the code is run, it crashes the program.

1. go to modulo practices
2. run a program with % 0
3. game crashes

I thought it would give a red error and how to explain it, but it crashes it

Windows and chrome.

**Comment by NathanLovato** [comment]
Just tested this, and it seems we need to intercept any division by zero
