### ISSUE TITLE
Error message not covered

### ISSUE THREAD

**Issue by Gabira10** [GDQuest/learn-gdscript#598]
**Issue description:**
I hope this is the right type of issue submit to put this, but I was on Lesson 3, practice 2, just completed it and was tinkering to see if I could rotae the robot in degrees, so I wrote the code:
```
func run():
    rotate(90'degrees)
```
and in the output, received the error

"ERROR  Parse error: Unexpected EOL at String.
in MakeRobotUpright at line 2, column 1"

but the error doesn't have any description/explanation in the app, and it said to report it, so here I am. Hope I can help with this, and not be a waste of time.

Here's the error log (if that's helpful in this case)
[2022-07-27-13-23.log](https://github.com/GDQuest/learn-gdscript/files/9201027/2022-07-27-13-23.log)

And here's a screenshot of the issue.
![image](https://user-images.githubusercontent.com/110120191/181302115-e65a52be-cbd7-4ce8-bd69-dfe532e7d5f7.png)

**Comment by NathanLovato** [comment]
Absolutely, issues like these are most welcome, thanks for letting us know!
