### ISSUE TITLE
Allow to go straight to the next practice when continuing a lesson

### ISSUE THREAD

**Issue by survivant** [GDQuest/learn-gdscript#60]
I did some lessons
![image](https://user-images.githubusercontent.com/191879/147705290-e7812675-7b65-46f5-8813-d3f32beb9487.png)

suppose that I forgot and I did in lesson 3.  I want to go back to the practice and see what I did (or the official solution).  

Maybe a link or button beside 2/2  like "Show solution".

It's could still possible by the user to reset a lesson by cliking "Start the lesson"

if you check online courses you will have a navigation at the top or bottom to skip to the next session or go back.

**Comment by survivant** [comment]
and How can I got directly to the second part of the practice ?

![image](https://user-images.githubusercontent.com/191879/147706317-3bf3a544-fc26-4361-908c-0cba1934c7b8.png)

**Comment by pycbouh** [comment]
You don't restart the lesson when you click "Start the Lesson" button, your progress is always saved. You just open the course at the top of the lesson, but you can still scroll to the bottom and select any practice from that lesson. We could add some ways to navigate directly to each practice from the course index, but that may make it a bit too loaded for people to experience.

**Comment by NathanLovato** [comment]
Changing the button text to "continue" when you started the lesson already, why not. I don't think it's necessary to add the ability to navigate to any practice.

Continuing from the last open practice automatically wouldn't be good either: what if you saw the lesson 5 days ago? You kinda need to do the practice with the lesson fresh in your mind.

Lastly, the ability to directly navigate to different practices would make the UX heavier for the target audience, I agree. The idea is to keep things simple. Individuals may want to do all kinds of little things, but that doesn't mean we need to cater for all those wishes - to me, it's more important to keep the app straightforward to use for the target audience, i.e. programming beginners.

**Comment by pycbouh** [comment]
> Changing the button text to "continue" when you started the lesson already, why not.

It's already a thing. If you haven't read the lesson, it says "Start", if you've started it says "Continue", and if you've finished it says "Open".

**Comment by NathanLovato** [comment]
Alright, then, I think it's good for this issue as far as I'm concerned. I'll close for now. If you really need to reopen practices often, please let me know and we'll reconsider this.

Note that I can see a use case for exploring code snippets in a separate app, for a wider audience: some kind of GDScript playground and example library.

In this app, it'd be of a much lower priority to me as we designed it as a linear course, with the option to skip things you already learned elsewhere (or continue even if you get stuck in a specific lesson).
