### ISSUE TITLE
Link typo in Lesson 18 for loops/while loops

### ISSUE THREAD

**Issue by kat-fromluckshop** [GDQuest/learn-gdscript#601]
In the 6th block of text "We recommend favoring for loops]for loops[/url] over while loops]while loops[/url]" , I believe it's a typo. 

![image](https://user-images.githubusercontent.com/110356458/182046051-97466a0d-5274-4582-93fd-6c2604f5cd83.png)

[2022-07-31-14-24.log](https://github.com/GDQuest/learn-gdscript/files/9229736/2022-07-31-14-24.log)

**Comment by kat-fromluckshop** [comment]
Saw that there's another typo in the 3rd text content block, increment]increment[/url]

But I actually just realized that this issue only arises because I am alt-tabbing between the program and desktop. Re-launching the app fixes it.

**Comment by NathanLovato** [comment]
It's issue #511, I'm not sure exactly why that happens because we've not been able to nail the reproduction steps for this issue. The issue may even be on Godot's side, not sure.
