### ISSUE TITLE
Port to Godot 3.5

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#608]
- [x] Replace font causing syntax highlighting to fail
- [ ] Complete #535 
- [x] Create build of Godot 3.5 with the GDScript parser exposed (task for @Razoric480)
- [ ] Replace `GDScriptParserWrap` with `GDScriptErrorChecker` and `parse_script` with `set_source`
- [ ] Replace themes with project default theme, use variations for buttons
- [ ] Replace old tweens with the new SceneTreeTween
- [ ] Test that every screen still works as intended
- [ ] #673

Work in progress in branch `refactor-godot-3.5`

Known issues to fix:

- [x] Code highlighting in regular lesson text doesn't work anymore

**Comment by NathanLovato** [comment]
Closing as it's now time to remake the app in Godot 4, no need to do an intermediate port to 3.5 anymore

**Comment by vmedea** [comment]
Is a port to godot 4 / gdscript 2.0 in progress somewhere? I would love to help.

**Comment by winne42** [comment]
@vmedea see #852
