### ISSUE TITLE
"View solution" button on Well Done popup to see GDQuest's suggested solution

### ISSUE THREAD

**Issue by redactedscribe** [GDQuest/learn-gdscript#613]
**Is your feature request related to a problem? Please describe.**
Most times that I complete a practice, I want to view the solution GDQuest suggested.

**Describe the solution you'd like**
Instead of having to press Stay and then Solution, a "View Solution" button could be added directly to the Well Done popup to immediately open the Solution side panel. It seems to be a common enough action to want to take after solving the problem that a button for this on the popup would be nice.

**Comment by NathanLovato** [comment]
You can already do that. Click "stay" to stay on the practice, then use the Solution button like normal. You also have a Continue button to continue to the next practice or lesson.

![image](https://user-images.githubusercontent.com/12694995/185628218-762b9369-8f7e-4eb7-837c-bce82f76d761.png)
