### ISSUE TITLE
"Well done" popup appear while the output was generated

### ISSUE THREAD

**Issue by survivant** [GDQuest/learn-gdscript#62]
I was surprise a little.  I wrote the code and press RUN.  The animation /rectangle was drawing itself and I got a popup while the output was generated.
![image](https://user-images.githubusercontent.com/191879/147706003-a40bca87-8c29-42f6-a578-fb4a8a871711.png)

Maybe the popup appear as soon as the output is completed, but it's to fast.  If it's the case, there should have a little delay after the animation is completed and the popup is shown.

and when the "Well done" appear the animation /output was generated again in the popup, it's normal ?

**Comment by pycbouh** [comment]
> and when the "Well done" appear the animation /output was generated again in the popup, it's normal ?

It's not generated again. You see them at the same time, because the animation is simply translated from the background into the popup.

**Comment by generrosity** [comment]
I was definitely caught offguard too. It seemed like there was a momentary pause after clicking 'run', as if the website had stalled! Then the popup immediately appeared.

Is this a 'juice' and 'stealing player focus' suggestion perhaps? I certainly would love to see the animation run, get that juicey output field tickmark bounce / sparkles / border pulse for success, then have the popup? But I can see why getting on with the lesson works too.

**Comment by xix-xeaon** [comment]
This was a pretty jarring experience. The "well done" needs to happen After the "execution" is completed, even a few hundred milliseconds after the drawing is completed.

**Comment by pycbouh** [comment]
You should now be able to see the full execution, then checks passing, and only then have the popup appear.

https://user-images.githubusercontent.com/11782833/149584220-3feb4021-5dd8-4b79-ae45-da637b493212.mp4


This is just one improvement to the practice flow, so stay tuned :)
