### ISSUE TITLE
Keyboard doesn‘t Show up in Safari Browser on IPad

### ISSUE THREAD

**Issue by SkaOArts** [GDQuest/learn-gdscript#621]
The Keyboard doesn‘t Show up in Safari Browser on IPad. I‘m in the second chapter where I need to remove the # and I can’t, cause of that. 

Operating system: iOS 15.6
Browser: Safari

**Comment by NathanLovato** [comment]
This app doesn't support virtual keyboards at the moment, you need to connect a Bluetooth keyboard to use it.
