### ISSUE TITLE
error with the translation to Spanish

### ISSUE THREAD

**Issue by drcucaracha** [GDQuest/learn-gdscript#629]
hello I was reading the Learn GDScript From Zero application and there are parts where the text is in English, I asked in the discord forum to see if the translations were missing but when looking at the files (.po) I see that they are but for some reason the application does not apply them both in the web version and the one on github
![a1](https://user-images.githubusercontent.com/49615968/185993726-4ec3e58b-9ebd-4020-aa27-d32d4ae1172c.png)

**Comment by NathanLovato** [comment]
It's a known issue, it's because the translation strings have to be perfectly synchronized, and there are some tasks left for translations. See #561 #557 #556
