### ISSUE TITLE
Missing link to "this" example

### ISSUE THREAD

**Issue by aR-Dee** [GDQuest/learn-gdscript#63]
Section "0.What code is like" - "By the end of the series you will create **this.**" - the _this_ has no link to example
<img width="995" alt="image" src="https://user-images.githubusercontent.com/9952398/147710155-01d5b043-4eee-495c-b591-41a38865f012.png">

**Comment by generrosity** [comment]
It is likely a placeholder, maybe for an image, as obviously they haven't gotten that far into lessons yet.

Exciting!! 😁💚

**Comment by aR-Dee** [comment]
Yeah, I figured - still thought it is worth mentioning :)
