### ISSUE TITLE
Question : In lesson 17. the editor notes that the code is delayed to show the code in action, whats the code for this?

### ISSUE THREAD

**Issue by ghostOfStPeter** [GDQuest/learn-gdscript#637]
Also, I put a screenshot from another lesson. Why doesnt the code run the same? All I did was define a robot and its position and used its position in the array instead of just putting in a position within the array

![Capture1](https://user-images.githubusercontent.com/111779852/187499209-edc68e9b-b82e-4ff1-be33-16506e06e2d1.PNG)

**Comment by NathanLovato** [comment]
Robot_4 is a variable. It's a name that when used, gets replaced for the computer by the assigned value. Here, `Vector2(5, 1)`.

In other words, you could just write `Robot_4` in the array, but without the following `(5, 1)` which the computer treats as a function call in this context. Except that there is no function named `Robot_4`!

Normally you should get an error for this code as it's invalid. We're trying to address this with the next release.

Instead, you should either just write `Robot_4` or `Vector2(5, 1)` inside of the array.
