### ISSUE TITLE
Lesson 28: Add := adds autocomplete

### ISSUE THREAD

**Issue by p0lrr** [GDQuest/learn-gdscript#646]
In lesson 28, := is mentioned to add type inference. I'd like to suggest adding that := helps enable autocomplete. Though this doesn't change much about the course, it could be a handy piece of information to add. Thanks, this has been an amazing course!

**Comment by NathanLovato** [comment]
This is beyond the scope of the course, students don't see or know what autocompletion is at this stage.

**Comment by p0lrr** [comment]
> This is beyond the scope of the course, students don't see or know what autocompletion is at this stage.

Ok, thanks :>
