### ISSUE TITLE
Code formatting is inconsistent

### ISSUE THREAD

**Issue by generrosity** [GDQuest/learn-gdscript#65]
**Issue description:**
Some of the example code is formatted slightly differently.

I do love your highlighting, especially using the explicit 'space' character when describing function definitions. I hope that you are not formatting these by hand however! Or at least are using some kind of automation on it.

- Tab markers are usually missing but obviously important to Godot;

![image](https://user-images.githubusercontent.com/12838061/147718832-200c5142-62ff-4e14-8932-5d449d46aa73.png)
![image](https://user-images.githubusercontent.com/12838061/147718848-c85ab30f-2571-4b95-a34f-72c21a924c1a.png)

- I think that second screenshot included invalid inline comments [=20] - asw always, totally your decision, but you could also use comment at the end

- You aren't using the Godot ">|" image - the ">>" symbols might be better in bold for visability?

- Would you consider adding hover elements? Little automatic tips on linenumbers, "= is used for assignment, for comparions Godot uses ==", "func is the start of a function statement and must always be followed by a space"?

**Comment by NathanLovato** [comment]
Thanks for the report. I made 3 of the 5 elements as they were instantly actionable. For comments regarding the slider values, we have another task: #84 

Regarding hovering over bits of code, we're not planning this. It would be complicated to do as we don't have access to the GDScript tokenizer/abstract syntax tree. We'd basically have to rewrite the gdscript tokenizer to know the meaning of what you're hovering over in context. Or, without that, the functionality would be really limited and inconsistent (only look at a couple of hard-coded bits of text).

Now, we already intend to partly address this issue with #21 and by iteratively improving the lessons. We'd also need a good use case for that extra feature. I think it could be nice but maybe not worth the work right now.

**Comment by generrosity** [comment]
Nice. Thanks for reviewing and considering 👍💚
