### ISSUE TITLE
Consider adding a subtle background to make game examples with movement easier to read

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#652]
> I think the visual example of executing the code (with the robot character) could use a subtle background. Especially when executing code that moves the character it is just not clear how it is being moved.

The feedback from this user suggests that having a background with some kind of grid would help to better see how much characters are moving, for examples with characters.

**Comment by Wolfy7** [comment]
Not sure for which 

> visual example of executing the code (with the robot character)

this is missing. I see for example in Lesson 17. Introdcution to While Loops

![image](https://user-images.githubusercontent.com/16044116/193684736-fc89a721-f302-497d-905f-88034adc2fc5.png)

**Comment by NathanLovato** [comment]
If I understood the user right, It´s more about doing something like this, literally adding a background to code examples:

![image](https://user-images.githubusercontent.com/12694995/193813245-51db9a9e-4776-4046-8597-471332d71e2d.png)

Just to make the character's motion a little easier to parse for students. This is a really quick change but the issue is more about the art. We have some tiling patterns we could use, like the one on the above screenshot. I just need to change the colors.

**Comment by Wolfy7** [comment]
Alright, understand.
So you will handle this.
