### ISSUE TITLE
Keyboard layout issue for square brackets and curly brackets

### ISSUE THREAD

**Issue by SkaOArts** [GDQuest/learn-gdscript#653]
Can't type the square brackets and curly brackets, because of the keyboard layout. 
I have a german keyboard from logitech and the square brackets are on 8 and 9. But I need to press the key compination Strg + Alt + 8 or  9. It seams that the app doesn't accept key compination. Same for the curly brackets.
Key compination is for you more familiar in contex of the @ symbol.

This is how it looks like:
![image](https://user-images.githubusercontent.com/44909283/189224379-e6ccb474-7716-4bd0-a6c7-946bc7a85574.png)

**Comment by henriquelalves** [comment]
I tested using a german layout on my keyboard, and I was able to write it using the right Alt key. Did you test it with both Alt keys? And can you write the square/curly brackets on other apps (your browser or text editor)?

**Comment by SkaOArts** [comment]
Yes I can write square/curly brackets in other apps, like browser. 
And I tested it out with the right Alt key. Didn't come up with that idea cause I leard the keycompination to acces the other keys. 
So keycombination with Strg + left Alt  + Key don't work. 
right Alt + Key work. 
Never use the right Alt key in any other programm so far.
