### ISSUE TITLE
Web version of app uses 100% of CPU

### ISSUE THREAD

**Issue by ArmoredPony** [GDQuest/learn-gdscript#657]
When I run the app online, right after the page is opened CPU usage goes up to 100% instantly. Also visible stuttering appears. Desktop version does not behave this way. Changing "Framerate cap" option doesn't help.

Steps to reproduce the bug:
1. Open https://gdquest.github.io/learn-gdscript/

 - Operating System: Windows 10
 - Browser: Google Chrome 105.0.5195.102

**Comment by NathanLovato** [comment]
This isn't a general issue with the online version on Windows and Chrome, so we'll need more information. The issue may be specific to your environment.

Could you try in a private browser window, without any addons running?

Also, could you try with another browser and see if you have the same issue? Edge or firefox, whichever you have installed already.

If all the above fails, I then invite you to use the Windows desktop version: https://gdquest.itch.io/learn-godot-gdscript and see how it runs for you.

**Comment by ArmoredPony** [comment]
I had "Hardware acceleration" setting disabled for some reason. After enabling it, everything is fine. Sorry for not checking it first and opening an issue.

**Comment by NathanLovato** [comment]
No worries, glad you could solve this! Indeed without hardware acceleration, rendering is all on the CPU and in the browser it's super slow compared to a native CPU renderer.
