### ISSUE TITLE
Consider adding more infromation about how functions are created and some examples on how implement some of them

### ISSUE THREAD

**Issue by yeet227** [GDQuest/learn-gdscript#658]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NathanLovato** [comment]
Could you please explain your issue and how we can help? In this state it's not a valid issue or request for us as it doesn't describe a problem.

**Comment by NathanLovato** [comment]
I'll close for now as we're missing information, but if you can share details, we'll be happy to reopen the issue and help you.

**Comment by yeet227** [comment]
Sorry about the lateness of my reply what I meant is like adding support for more specific stuff like flight for both 3D and 2D instead of glossing over the math stuff like vector2 and 3

**Comment by NathanLovato** [comment]
I see, then that's beyond the scope of this app at the moment. This app and course teaches the very basics of coding with GDScript: variables, functions, you name it. We have a task loosely related to your request for when we remake the app for Godot 4: #476 

But that's something to prototype and test, we're not even sure that'll work for our target audience.
