### ISSUE TITLE
Suggestions (Lesson 1 - Lesson 14)

### ISSUE THREAD

**Issue by assertchris** [GDQuest/learn-gdscript#671]
These are some things that stand out for me, in the lessons, that might be improved upon. Feel free to check the issues you'd like me to work on, and leave the ones that you want me to ignore.

## General
- [ ] M1 Mac, when in fullscreen, cmd + tabbing to another screen leaves the app in fullscreen mode, and it hangs when returning
- [ ] [Seeing a screen size warning in fullscreen on a MBP M1 (bottom right)](https://github.com/GDQuest/learn-gdscript/issues/715)
- [ ] Can “continue” remember scroll position?
- [ ] #672
- [x] It looks like some of the viewports are styled similarly to the Gameboy. If that’s the case (and it’s cool), it’s unlikely that the target audience will get the reference. It doesn’t look so much like a Gameboy that they’re likely to make the connection, it’s two words etc. “Is the turtle GDQuest Boy?”

## Lesson 2
- [ ] You don’t talk about what comments are. # remains a mystery to someone new to programming
- [ ] “errors are here to help” but then “error messages are here to stay”. These are different things. Error messages are the help you describe, but avoiding errors is the goal.
- [ ] #716

## Lesson 3
- [ ] “what are radians” is out of place. You haven’t mentioned radians until that heading. In fact, you use the term “0.3 units”. “What are radians” should move to where the term is first required to be understood, or you can use `rotate_degrees()` to implicitly describe the unit in a way most folks would understand.
- [ ] #717
- [ ] `move_local_x` says “moves the character”, `move_local_y` says “moves the sprite”
- [ ] The example of `move_local_x` demonstrates wrapping, but the code doesn’t. Is this built-in behaviour? Probably should explain why it’s behaving differently to the code.
- [ ] “make the robot upright” could be simpler with `rotate_degrees`. If the reader didn’t expand the “what are radians” tooltip (because why would they at that point?) then radians will be a new term that they haven’t seen. It’s a foreign concept to a lot of career programmers…

## Lesson 5
- [ ] “functions are sequences of instructions we give a name” -> should there be a “instructions we give a name**to**” or “instructions **we name**”?
- [x] #682
- [ ] Symbol table explanation is too much before scope is explained
- [ ] Conflicting symbols warning is not enough information to be helpful. “Are you saying different scenes can’t have the same function name?” Or “Must every function be unique in my game?”. 
- [ ] “same code block” is not explained after being mentioned for the first time. Just that indents mean code block.
- [ ] “put a name on multiple lines of code” is needlessly ambiguous. This is what it sounds like to me:
```
func my_func():
	draw_square()
	draw_square()
	draw_square()
```
…where `draw_square()` is what you’re describing (not `my_func`)

## Lesson 6
- [ ] Weird highlighting in the answer to the func syntax question

## Lesson 7
- [ ] <img width="734" alt="Screenshot 2022-09-22 at 09 37 17" src="https://user-images.githubusercontent.com/200609/191964171-65d7e13e-5410-4e47-a16e-d8209000cd22.png">
- [ ] “the convention is opposite” isn’t the right word. “Different” might be better since it doesn’t imply a swapped x scale
## Lesson 8
- [ ] Did you explain about case sensitivity in variable names?
- [ ] “but it’s not good” can be more specific. “But the variable name no longer describes what it contains, which causes confusion”

## Lesson 10
- [ ] “from there every frame Godot will run” what’s a frame?
- [ ] “many times a second” how many? Is it important?

## Lesson 11
- [ ] “dozens of times a second”. So far you’ve used “many”, “multiple”, and “dozens”, but not the actual amount.
- [ ] Frame is only explained in lesson 11, but it’s first mentioned in lesson 10
- [x] #673
- [ ] Lesson 11 explains 60 FPS but doesn’t finish the thought: “`_process` isn’t tied to this, so don’t assume it is happening at 60 FPS, wait till we explain delta”
- [ ] “the word ‘delta’” should just be “’delta’” or “the variable ‘delta’”. The word [delta] is generally unrelated to time, and just means a finite increment.
- [ ] The next sentence is almost an exact repeat using “parameter” instead of “word” to refer to delta.
- [ ] The next sentence uses “variations” and “simulation” which are jargon.
- [ ] In the delta question: is it more helpful to say “it’s a value in fractions of a second”, since it’s never going to be full seconds?
- [ ] “angular speed in radians per second” is _a lot_. Is it helpful to talk about this yet?
- [ ] I think chapter 11 is too vague about what is wrong with not multiplying with delta. You could have examples of what would happen; like “players on faster computers will move faster in multiplayer games” or “you would be able to anticipate the movement of enemies as well on a slower computer”. “Messy”, “buggy”, “bad” are empty calories. Further, radian per second is how we think of val * delta. The parameter type stays the same. It’s just “rotate by this much”, but it happens every frame. 

## Lesson 12
- [ ] First question is difficult, because it depends on the specific memory that `3.0 * delta` is radians per second, which is speed (although I’m not sure it’s ever described in that way)
- [ ] `angular_speed` isn’t super helpful as a variable name. `radians_per_second` would be better IMO

## Lesson 14
- [ ] <img width="337" alt="Screenshot 2022-09-23 at 13 44 52" src="https://user-images.githubusercontent.com/200609/191964114-921579c2-5cf9-4e89-b027-ffc468390d66.png">

**Comment by NathanLovato** [comment]
>  First note block was rendered not at full width. After expanded it, it became full width.

This I've seen only with Godot 3.5, it seems like a bug introduced by Godot 3.5. We could add it to the "port to Godot 3.5" issue.

**Comment by NathanLovato** [comment]
> “No script parser class in exported app” has no details, and suggests reporting the error. Is this expected? We might need to document how to install this.

Yeah, you need a custom Godot build to be able to compile at runtime and get GDScript parse errors. We should definitely document that, I'll make an issue

**Comment by NathanLovato** [comment]
>  M1 Mac, when in fullscreen, cmd + tabbing to another screen leaves the app in fullscreen mode, and it hangs when returning

Is this a Safari browser issue or desktop Mac? Any errors when it hangs?

**Comment by assertchris** [comment]
> Is this a Safari browser issue or desktop Mac? Any errors when it hangs?
Desktop (macOS 12.6), app running in debug mode, in Godot 3.5.x

**Comment by Xananax** [comment]
This is a very cool list, but I'd rather we move it somewhere where items can be commented on individually such as Coda. The retained items can then be brought back as issues or improvements here.

**Comment by assertchris** [comment]
Let's close this for now. The list is in Coda if we want to pursue any of the non-content points; and the content points have all been addressed now.
