### ISSUE TITLE
Web/HTML5 version of Lesson 24 Practice 1 text rendering bug

### ISSUE THREAD

**Issue by phealy3330** [GDQuest/learn-gdscript#678]
**I'm submitting a...**

- [ x] Bug report.

## Bug report ##

**What is the current behavior?**
The description of the practice displays

> Call the use_item() function with the item as an argument to use an item. For example, you can use the first item by calling use_i])])[/code].

**What is the expected behavior?**
The description should display

> Call the use_item() function with the item as an argument to use an item. For example, you can use the first item by calling use_item(inventory[0]).

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 
Open the lesson practice here: 
https://gdquest.github.io/learn-gdscript/#course/lesson-24-access-array-indices/practice-ErO9L4MW.tres

**Other information** 
The desktop app doesn't have this same issue

**Comment by NathanLovato** [comment]
I'm suspecting that the regular expressions don't work great in the browser, as there have been some weird, platform-specific bugs like this. Thanks for the report. For this feature, I think we need more robust text parsing code.
