### ISSUE TITLE
Three ways we use the modulo operation example cannot run

### ISSUE THREAD

**Issue by xiliuya** [GDQuest/learn-gdscript#679]
**Describe the bug**
advance button output unchanged

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'lesson-15-modulo‘
2. Click on 'advance()'
3. See traffic light unchanged

**Expected behavior**
traffic light change

**Information about your device (please complete the following information):**
 - Operating System: [ Arch Linux ]
 - Browser: [ FireFox ]

**Comment by henriquelalves** [comment]
Assigning myself to this issue because it's related to the Debugger node modifications I had to make on the App (specifically, how examples have to "reset" by default)
