### ISSUE TITLE
BUG on chapter 6 exercise 1

### ISSUE THREAD

**Issue by maxunch30** [GDQuest/learn-gdscript#684]
The tortoise just jump when the custom rectangle has been drawn.  Next the tortoise draw a square and then the application says that the exercise is wrong.

Steps to reproduce the bug:
1. Just complete the task and press the "[ (1>)Run ]" button.

![bug](https://user-images.githubusercontent.com/73908157/193453412-585fc95a-dd55-444b-b42c-87713215812d.PNG)

**Information about your device (please complete the following information):**
 - Operating System: Windows 10 64-bit Build 21H2
 - Browser: Chrome version 106.0.5249.91 (Official Build) (64-bit)

Thank you so much!

**Comment by maxunch30** [comment]
Sorry my bad. I miss understand the exercise. thank you again. :/ It's about draw corners not squeares or rectangles. So sorry.

**Comment by NathanLovato** [comment]
No worries!
