### ISSUE TITLE
L20: Wrong answer listed as correct

### ISSUE THREAD

**Issue by Tshinanu** [GDQuest/learn-gdscript#693]
Wrote the wrong code but it still worked as a valid answer even though the robot doesn't follow the path and goes straight to the final vector. 

`var robot_path = [Vector2(1, 0), Vector2(1, 1), Vector2(1, 2), Vector2(2, 2), Vector2(3, 2), Vector2(4, 2), Vector2(5, 2)]

func run():
	robot.move_to(Vector2(5,2))`

[2022-10-05-20-08.log](https://github.com/GDQuest/learn-gdscript/files/9719694/2022-10-05-20-08.log)

**Comment by henriquelalves** [comment]
I can't seem to reproduce this error in the stable or bleeding edge versions of the app. Can you tell me which version of the app this happened, and if it was online, which browser you were using?

**Comment by NathanLovato** [comment]
According to the log's date this should be the current version. Though we should add the app version to the log as sometimes the browser caches the app and won't download the latest release.

**Comment by NathanLovato** [comment]
Same, I can't reproduce the error with the latest release. Most likely, your browser cached an older release of the app and didn't re-download the latest version. I invite you to select your address bar when running the app and press Ctrl Shift R to force the browser to download the latest version of the app. Then you shouldn't see this issue anymore.
