### ISSUE TITLE
Lesson 3: Moving sprite example moves up instead of down

### ISSUE THREAD

**Issue by kennethdiedrich** [GDQuest/learn-gdscript#694]
**Describe the bug**
In [lesson 3](https://gdquest.github.io/learn-gdscript/#course/lesson-3-standing-on-shoulders-of-giants/lesson.tres), the "Move a sprite" example under the "Function arguments" header moves the sprite _up_ and to the right, when all the surrounding text and code says it should move _down_ and to the right.

**To Reproduce**
Steps to reproduce the bug:
1. Go to [lesson 3 of the course](https://gdquest.github.io/learn-gdscript/#course/lesson-3-standing-on-shoulders-of-giants/lesson.tres).
2. Scroll down to the "Move a sprite" example underneath the "Function arguments" header.
3. Click the "run()" button in the example.

**Expected behavior**
I expected that the sprite would move to the right and down, as all the surrounding lesson text and code indicates it should.

**Screenshots**

![image](https://user-images.githubusercontent.com/51301860/194336071-bc174eee-20e5-4a71-a8e5-0c6c33a719f7.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows
 - Browser: Brave, Version 1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit)

**Additional context**
None required.

**Comment by NathanLovato** [comment]
It seems that the character is being moved to the top-left corner of the demo's frame, then offset right and down. Thanks for letting us know!
