### ISSUE TITLE
Paste is applied twice in code editor in some browsers

### ISSUE THREAD

**Issue by MartinDanihelDev** [GDQuest/learn-gdscript#698]
**Describe the bug**
When you copy some code in code editor it will paste code twice.

**To Reproduce**
Steps to reproduce the bug:
1. Go to lesson ,,Drawing a bigger rectangle"
2. Copy first two lines of code with CTRL+C
3. Paste those lines with CTRL+V
4. See the issue

**Expected behavior**
Text should be pasted only once, not twice.

**Screenshots**
![2022-10-08 13_04_34-Window](https://user-images.githubusercontent.com/82676222/194704374-f5a819bf-f032-46f4-927c-6ec17eb40484.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows
 - Browser:  Firefox
 
 Maybe this issue happens also in different lessons. I don't tried it now.

**Comment by NathanLovato** [comment]
I just tested and this seems only to occur in the Firefox browser. The bug doesn't happen on desktop or in Brave.

**Comment by NathanLovato** [comment]
Also happens in edge, see #721

**Comment by gs3rr4** [comment]
Also happens in Google Chrome.

**Comment by JakkAeson** [comment]
Encountered this issue in Chrome 107.0.5304.107, Win 11 64-bit. I've noticed that this only occurs when pressing CTRL-V to paste, pasting using the right click menu pastes once as expected.
