### ISSUE TITLE
Exercise 21: Arrays and Strings

### ISSUE THREAD

**Issue by patrick-men** [GDQuest/learn-gdscript#708]
**Describe the bug**
The exercise does not correctly test the code - when using loops instead of hard coding the combo, it's shown as being wrong. However, the robot does as wished, i.e. output is correct

**To Reproduce**
See screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/68388275/195814628-f6f38ba6-15fe-4001-bef8-8cb54587ffb0.png)

**Comment by NathanLovato** [comment]
We want you to populate the array with the appropriate data for your combo. We need to refine the practice description and reported error, basically we expect the array two contain ¨jab" twice.
