### ISSUE TITLE
Show solution shouldn't override the user code

### ISSUE THREAD

**Issue by survivant** [GDQuest/learn-gdscript#71]
I was playing with the lesson 5.  I Entered this code, which is working.

````
func draw_rectangle(length, height):
	move_forward(length)
	rotate(90)
	move_forward(height)
	rotate(90)
	move_forward(length)
	rotate(90)
	move_forward(height)
	rotate(90)
````

I forgot that the method to rotate was ``turn_right()``, so I clicked on ``Show solution``, but by doing that, I lost what I entered, so I can't compare my code with the solution proposed

````
func draw_rectangle(length, height):
	move_forward(length)
	turn_right(90)
	move_forward(height)
	turn_right(90)
	move_forward(length)
	turn_right(90)
	move_forward(height)
	turn_right(90)
````

**Comment by pycbouh** [comment]
I assume you meant "shouldn't"?

**Comment by NathanLovato** [comment]
We kept it simple, but I think that yes, showing the solution doesn't sound like it'll replace your code. It would make sense to me to allow the student to peek at the solution, and optionally let them skip the assignment (apply the solution) when peeking, but the idea is to nudge people towards practicing.

@Xananax and @pycbouh what do you think teaching and UX-wise?

**Comment by Xananax** [comment]
My idea was simply to include an undo button, which works for normal code as well as when the solution is inserted (it replaces code the same way a user would and adds itself to the undo stack).

We could animate the undo button with a quick shine or a wiggle after inserting the solution for attracting the user's attention?

Another would be to insert the code, automatically run it, but bypass checks,  and replace all the buttons at the bottom with a "go back to your code" button. 

We can also pop the solution in a modal and such, but I don't like it if the user can't hit run and test the code.

**Comment by xix-xeaon** [comment]
I think it would be better to just have a popup with the working code, which you can then close again to continue coding. I don't think anyone expects the button to make any changes.

**Comment by pycbouh** [comment]
Now the button brings up a panel instead so you can compare the suggested solution with your code. You can still use it, or copy it over in parts, or look at it and try to reproduce it. Up to the student. Note that clicking "Use Solution" will keep the practice unfinished, so the student can return to it later and try to solve it themselves.

You can also stay in practice upon completion now, so you can actually solve it, let it count towards your progression, then compare your solution afterwards :)
