### ISSUE TITLE
Lesson 3 move_local code example not moving correctly

### ISSUE THREAD

**Issue by BruceMcRooster** [GDQuest/learn-gdscript#710]
**Describe the bug**
When the code example is run, the character moves completely opposite of where it should be. `move_local_x(20)` and `move_local_y(20)` should put it in the bottom right corner, but instead results in the character moving to the top left corner.

**To Reproduce**
Steps to reproduce the bug:
1. Go to Chapter 3
2. Scroll to the third interactive example
3. Click `run()`

**Expected behavior**
The character should move to the bottom right corner of the block

**Screenshots**
Screenshot having just run the code segment
![image](https://user-images.githubusercontent.com/53529192/196057397-b0384e5e-b379-42d8-bcf5-714ef7387254.jpeg)

**Information about your device (please complete the following information):**
 - Operating System: MacOS
 - Browser: Safari

**Comment by NathanLovato** [comment]
Already fixed, fuplicate of #694 and #707
