### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by emot-RGB** [GDQuest/learn-gdscript#719]
**the max size for the font is to small and i can't use extentions to make it bigger**

**Comment by NathanLovato** [comment]
Could you please show me a screenshot of how it looks with the biggest setting on your computer and a screenshot of another text, from another webpage, that's representative of how big you'd need the text to be?

**Comment by NathanLovato** [comment]
I'll close in the absence of a response, but don't hesitate to answer the above and I'll reopen the issue.
