### ISSUE TITLE
Show the parameters used to call the student's function in practices

### ISSUE THREAD

**Issue by survivant** [GDQuest/learn-gdscript#72]
I ran to solution for the lesson 5, but it was a little confusing.  Why 2 rectangles appears in the response output ?
![image](https://user-images.githubusercontent.com/191879/147780191-a9dbc93f-4ead-4458-8599-9d13ca213df3.png)

Maybe you could specified the params used in the response,  In the previous image, we could see that 2 calls were made to the function ``draw_rectangle``

**Comment by NathanLovato** [comment]
The checks in the bottom-left mention drawing rectangles with those dimensions. We've considered something like showing the code we run to the student, but we still have to figure out how to do it well.

**Comment by NathanLovato** [comment]
Superseded by #759
