### ISSUE TITLE
Fix Your First Error - Typo or grammar

### ISSUE THREAD

**Issue by denicolas** [GDQuest/learn-gdscript#723]
[Fix Your First Error](https://gdquest.github.io/learn-gdscript/?ref=godot-docs#course/lesson-2-your-first-error/practice-85733.tres)

In "Where do external errors come from?" dialog box:
"to make sure your **projects runs** smoothly"
should be:
"to make sure your **projects run** smoothly"
or:
"to make sure your **project runs** smoothly"

**Comment by NathanLovato** [comment]
Thanks!
