### ISSUE TITLE
Rotating a Character Continuously - speed/angle

### ISSUE THREAD

**Issue by denicolas** [GDQuest/learn-gdscript#725]
[Rotating a Character Continuously](https://gdquest.github.io/learn-gdscript/?ref=godot-docs#course/lesson-10-the-game-loop/practice-tKRHJMQ2.tres)

"A rotation **speed** of about 0.05 each frame should do."
should be:
"A rotation **angle** of about 0.05 each frame should do."

**Comment by NathanLovato** [comment]
speed is fine here, we're talking about units / time (0.05 per frame / each frame)
