### ISSUE TITLE
Time Delta - takes/took

### ISSUE THREAD

**Issue by denicolas** [GDQuest/learn-gdscript#726]
[Time Delta](https://gdquest.github.io/learn-gdscript/?ref=godot-docs#course/lesson-11-time-delta/lesson.tres)

In the "What do we know about delta?" quiz:
"It's the time it **takes** Godot to complete the previous frame."
should be:
"It's the time it **took** Godot to complete the previous frame."

And in the answer to that quiz:
"delta is the time it **takes** Godot to complete the previous frame in seconds."
should be:
"delta is the time it **took** Godot to complete the previous frame in seconds."

**Comment by NathanLovato** [comment]
To me, the present tense seems OK in this context (general description), but I'll send this to our editor for a professional check.

**Comment by denicolas** [comment]
Yes, I understand and I agree, it seems OK in a general description.

**Comment by NathanLovato** [comment]
Isaac thinks the past tense is better here, more in line with the rest of the lesson. I just made the change. Thanks for pointing it out!
