### ISSUE TITLE
add a message while generating the output

### ISSUE THREAD

**Issue by survivant** [GDQuest/learn-gdscript#73]
In the lesson 6, when I pressed ``RUN``, I waited for maybe 2-3 seconds without the UI updating.  It should write a message like ``Generating output``.  

I suppose that there are not really lot of activity on the server right now, but when there will be more people using the tools, maybe there will be a more delay between the click and the response.  Normally we use a looping icon, a message.. something that tell the use there something running in the background.  It's to give the user a feedback that something going on.

Wait a few ms before showing the message, something the response could be fast enough.

**Comment by NathanLovato** [comment]
This is kind of a duplicate. See #6. The spinner would indicate you're waiting for response.

**Comment by NathanLovato** [comment]
I'll close for now, please let me know if you think there should be a message for that. But the app isn't generating output, it's just waiting for the server to process your request and lint your code.

**Comment by survivant** [comment]
the spinner will do the job.  It just need a way to let the user know that there is something running
