### ISSUE TITLE
Creating arrays - Grammar

### ISSUE THREAD

**Issue by denicolas** [GDQuest/learn-gdscript#733]
[Creating arrays](https://gdquest.github.io/learn-gdscript/?ref=godot-docs#course/lesson-19-creating-arrays/lesson.tres)

"A list of values, numbers or otherwise, has a precise name in code: we call **them arrays**."
should be:
"A list of values, numbers or otherwise, has a precise name in code: we call **it an array**."

**Comment by NathanLovato** [comment]
Thanks!
