### ISSUE TITLE
Congratulations (end of lesson 28) - Links not working

### ISSUE THREAD

**Issue by denicolas** [GDQuest/learn-gdscript#736]
Theses links do not work:

- Getting Started with Godot
- Learn GDScript From Zero (Github repository)

My browser is Chromium 107.0.5304.87.
My OS is Kubuntu 22.04.

**Comment by NathanLovato** [comment]
Thanks, the screen seems outdated, it's been fixed on our end for a while, but it seems the new screen isn't live. I'll push a release now
