### ISSUE TITLE
Using CTRL-X to cut does the cut operation twice

### ISSUE THREAD

**Issue by JakkAeson** [GDQuest/learn-gdscript#737]
**Describe the bug**
Pressing CTRL-X to cut appears to perform cut twice, leading to unexpected behaviour when attempting to cut and paste text. Using the right click context menu to cut text works as expected.

**To Reproduce**
Steps to reproduce the bug:
1. Go to the practice page for "3. Drawing A Bigger Rectangle" in Lesson 4.
2. Place the cursor on a line 3.
4. Press CTRL-X to cut. Both line 3 and 2 get cut.
5. Paste the text that was just cut. The text that gets pasted is from line 2.

**Expected behavior**
Pressing CTRL-X to cut will perform cut once.

**Information about your device (please complete the following information):**
 - Operating System: Windows 11 21H2 64-bit
 - Browser: Chrome 107.0.5304.107

**Additional context**
This seems to be related to #698 in that using the keyboard shortcut to cut/paste both perform the operation twice.

**Comment by Maltavius** [comment]
Ctrl+C and then Ctrl+V pastes two times for me.
Lots of strange things with Copy and cut operations
