### ISSUE TITLE
Lesson numbers in breadcrumbs are off by one

### ISSUE THREAD

**Issue by survivant** [GDQuest/learn-gdscript#74]
I'm in the Lesson 7.  
![image](https://user-images.githubusercontent.com/191879/147781250-7e3bf44b-78ea-44de-9ede-9a73c1446241.png)
When I click on the left menu to see the lesson's index, I can see the correct values for each lesson.
![image](https://user-images.githubusercontent.com/191879/147781177-6cb88175-5314-43b2-b24c-0680cdfbcd70.png)

**Comment by NathanLovato** [comment]
Fixed with https://github.com/GDQuest/learn-gdscript/pull/87
