### ISSUE TITLE
21. Strings - Using an array to play a combo

### ISSUE THREAD

**Issue by AdvanceMancer** [GDQuest/learn-gdscript#745]
Hi! ✌
**Describe the bug**
I was trying to solve this practice (the 1st one of lesson 21), and got this (beautifully explained) error pop-up saying for me to generate a log and report the error, so... Here it is! 

_The script has an error, but the Script Verifier did not catch it_

**To Reproduce**
Steps to reproduce the bug:
Use this code:
`func run():
	combo = [jab, jab, uppercut]
	for action in combo:
		play_animation(action)`
![2022-12-02](https://user-images.githubusercontent.com/7526345/205212901-b2cf7a57-3bd0-4849-9f3b-a2b745a4f9ef.png)

**Expected behavior**
I _think_ it should work? Clearly, it doesn't, but I'll keep tinkering with it. I'm sending the report because it seems that this script broke something outside the script verifier and can't catch for some reason.
[edit: solved it - I had some difficulties to understand _why_ I couldn't define myself the variable 'combo' outside of the function, and why I couldn't set a arbitrary name for it (like robot_combo, etc)]

**Information about your device (please complete the following information):**
 - Operating System: Windows 10 x64, learn-godot-gdscript-windows-release (29-11-2022)
[2022-12-02-00-49.log](https://github.com/GDQuest/learn-gdscript/files/10138020/2022-12-02-00-49.log)

**Comment by NathanLovato** [comment]
I'm getting back to you a bit late, but it doesn't work because `jab` written like this, for the computer, is a variable name. But there is no variable named `jab` here.

Instead, you need to use text strings, and for that you need to write the words inside quotes: `["jab", "jab", "uppercut"]`.

I'll look into the error message not lacking a longer explanation.

**Comment by NathanLovato** [comment]
It seems there's already a long explanation with other related issues I fixed a while ago, so it should be good if you download the latest release from itch.io

![test-compressed](https://user-images.githubusercontent.com/12694995/208410911-b14d7bef-0650-471a-961e-b61842cb9326.png)
