### ISSUE TITLE
lesson 11 practice 1 - test 1 does not detect wrong use of delta

### ISSUE THREAD

**Issue by Gee2k** [GDQuest/learn-gdscript#746]
**Describe the bug**
In Lesson 11 the practice "Rotating Using Delta"
https://gdquest.github.io/learn-gdscript/?ref=godot-docs#course/lesson-11-time-delta/practice-UdOCQiGj.tres

It is possible to "succeed" the practice even when the delta is not applied to the rotation.
The final animation is spinning very fast showing that its not normalised trough delta.

**To Reproduce**
Steps to reproduce the bug:
1. Go to lesson 11 practice 1 "Rotating Using Delta"
2. append `* delta` to line 2
```gdscript
func _process(delta):
	rotate(2) * delta
```
4. click run
5. tests succeed

**Expected behavior**
The first test *rotating character is time dependent* should fail as the rotation is not normalised trough delta
expected valid code
```gdscript
func _process(delta):
	rotate(2 * delta)
```

**Information about your device (please complete the following information):**
 - Operating System: Windows
 - Browser: Brave

**Screenshots**
![2022-12-04 00_04_10-Window](https://user-images.githubusercontent.com/3016381/205465777-7214564e-635f-4008-9261-9c31f7b1fe3b.png)

**Comment by Maltavius** [comment]
I came here to report this bug too.

**Comment by NathanLovato** [comment]
It's already fixed, just not in the current stable release: https://github.com/GDQuest/learn-gdscript/pull/722
