### ISSUE TITLE
Lesson 8 : variable name must be unique in a "function or block of code"

### ISSUE THREAD

**Issue by survivant** [GDQuest/learn-gdscript#75]
in : https://gdquest.github.io/learn-gdscript/#course/lesson-8-defining-variables/lesson.tres
![image](https://user-images.githubusercontent.com/191879/147781471-7f5e04b8-c79d-4ab0-9c0d-a89769e18e74.png)

the variables names should be unique, but in a function or block of code.  Let say that we should tell the beginner that it must be unique within a file.

OK, I didn't try in Godot, I'm not sure if it's the case like other programming language

example

````
var index=0

func method1():
    var index=5
    ....

function method2():
   var index=1
... 
````

**Comment by NathanLovato** [comment]
It's true that should be nuanced. The idea is that you shouldn't shadow properties in your code. I'll rephrase that, thanks
