### ISSUE TITLE
Lesson 24: Display of arrays is cut off, when using small text

### ISSUE THREAD

**Issue by kris-scheibe** [GDQuest/learn-gdscript#753]
**Describe the bug**
The display of the array-items is cut off when using small text:
![image](https://user-images.githubusercontent.com/20039785/207513658-7ef42c6c-9ade-4368-a71e-f7b0094ec2a0.png)

**To Reproduce**
1. Configure the app to use small text: 
![image](https://user-images.githubusercontent.com/20039785/207513832-2697abfc-f649-4862-99f2-4a4484771c2b.png)
2. Go to lesson 24 or reload the page (the layout looks fine if the text size is changed while the lesson is open)

**Expected behavior**
The display should not be cut off on any text-size.

**Information about your device (please complete the following information):**
 - Operating System: Linux
 - Browser: Chrome, Brave, Firefox (looks identical on all three)

**Comment by NathanLovato** [comment]
This is due to #99, so I'm closing this to focus on the underlying issue. It's a known issue that we unfortunately can't solve in Godot 3. We will use a new approach when remaking the app in Godot 4 to address this.
