### ISSUE TITLE
Android keyboard not opening in Code Editor

### ISSUE THREAD

**Issue by Culain** [GDQuest/learn-gdscript#760]
**Describe the bug**
The Android keyboard ist Not opened automatically when clicking inside the Code editor.

**To Reproduce**
Steps to reproduce the bug:
1. In lesson 2-1 click on practice 
2. The Code editor opened
3. Click inside the editor
4. Keyboard doesnt open

**Expected behavior**
The Android keyboard should open.

**Information about your device (please complete the following information):**
 - Operating System: Android 12 on Lenovo Tab P11 plus
 - Browser: Firefox 108.1.1

**Comment by NathanLovato** [comment]
It's intentional, the app is only for desktop. We don't support mobile devices. You can technically use the app on a tablet but you'll need an external keyboard.
