### ISSUE TITLE
Give time to look at your solution before moving on during practices

### ISSUE THREAD

**Issue by maranr** [GDQuest/learn-gdscript#77]
It is important for learners to summarize and evaluate what they did correctly.
Please allow time for us to look at and study our correct solution before instantly moving on when you get a correct solution in the practice. Sometimes you are not exactly sure what you did correctly and/or it is a great time to absorb what you did to be successful to reinforce learning. 

**Describe the solution you'd like**
Leave your solution on the screen with a summary of what is happening instead of instantly jumping to the next lesson on a successful practice.

**Describe alternatives you've considered**

**Additional context**

**Comment by xix-xeaon** [comment]
Related to #52, my take:

> I think you shouldn't even be able to "move on" right away. You want the student to review the work they did (now that they got it right) Before moving on. You should only have a close button, and then a button to move on to the next part / lesson should be easy to find but also "in the corner" or something.

But I think some of you're suggesting could possible be added as well.

**Comment by NathanLovato** [comment]
Definitely, that'll be a great improvement. Thanks for pointing this out.
