### ISSUE TITLE
Locked on 50 FPS on Windows

### ISSUE THREAD

**Issue by Adiveler** [GDQuest/learn-gdscript#771]
**Describe the bug**
App is locked on 50 FPS, no matter what option I choose (30 FPS works as intended though)

**To Reproduce**
Steps to reproduce the bug:
1. Enter the desktop app.
2. Click "Options".
3. In "Framerate cap", choose either 60 FPS or No limit.
4. App is locked on 50 FPS on either option.

**Expected behavior**
60 FPS for 60, and 144 FPS (my desktop cap FPS) for no limit

**Screenshots**
![50locked](https://user-images.githubusercontent.com/58662472/213571793-a34ab0ec-ba6c-47a6-ac04-1ac74c62b24c.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows
 - Browser: Desktop version

**Additional context**
I'm using G-Sync for performance; and MSI Afterburner for monitoring (FPS, RAM, CPU and GPU temperatures during demanding games, etc…)

**Comment by Adiveler** [comment]
Disabling G-Sync doesn't seem to solve the issue, it's still locked on 50 FPS.

**Comment by NathanLovato** [comment]
Thanks, I have no idea of what could be causing this, and it seems to be a low-priority issue. I'll wait to see if someone can pinpoint the cause.

**Comment by Calinou** [comment]
The culprit is here: https://github.com/GDQuest/learn-gdscript/blob/6f52f8f76c3b03fefe8a99fe9aec7398f94e02bd/ui/UICore.gd#L31

When using low processor mode, I recommend not setting `Engine.target_fps`. Instead, set `OS.low_processor_mode_sleep_usec` to `1_000_000 / fps` where `fps` is FPS as an integer.

**Comment by NathanLovato** [comment]
Thanks, gonna fix right away
