### ISSUE TITLE
Lesson 4 Drawing a corner - Use 'argument' instead of 'parameter'

### ISSUE THREAD

**Issue by stewchan** [GDQuest/learn-gdscript#772]
**Issue description:**
Make the lesson clear and consistent with the previous lesson

In the previous lesson the word used to describe a value passed into a function is 'argument' so the same word should be used in this lesson.

Also, the paragraph with 'to the right' is confusing since the function is also 'turn_right()'. Remove 'to the right' since it causes confusion.

Is there an easy way to read and correct the lesson text in Godot? If someone could show me a good workflow to do that, I could create a pull request with the proposed changes as well as any future lesson inconsistencies I might encounter.

**Comment by NathanLovato** [comment]
Thanks, much appreciated. I went ahead and fixed these, but if you'd like to contribute to other lessons, you can open the files named `lesson.tres` in the folder `courses/*/` in a text editor. For example, for lesson 4, it'd be the file `course/lesson-4-drawing-a-rectangle/lesson.tres`

If you spot content issues and you're confident about how to address them, don't hesitate to open a PR right away, without opening an issue.
