### ISSUE TITLE
Lesson7 typo

### ISSUE THREAD

**Issue by sangiye0** [GDQuest/learn-gdscript#773]
![lesson7](https://user-images.githubusercontent.com/22906790/213866239-595e4cea-53dc-4513-a12e-cd6378fe329f.png)Hi
Hi, there is a description that doesn't match to the code. Description says, "The code below places the entity at 180 pixels on the x-axis and 120 pixels on the y-axis." On the code, position.x = 200, position.y = 250. I think one of them should be matched to the other.

**Comment by cadadr** [comment]
this seems to not be fixed; also a few paragraphs down the line the wrong values are referenced once more, right under the "In games, the Y-axis..." title

**Comment by OzOsseus** [comment]
This typo is still present. Glad I checked if someone else posted before duplicating.
