### ISSUE TITLE
Missing return type on the documentation of the exercises 27.1 and 27.2

### ISSUE THREAD

**Issue by mhco0** [GDQuest/learn-gdscript#774]
The return type of the "str()" and "int()" functions shouldn't be "String" and "int" instead of void ?

![image](https://user-images.githubusercontent.com/33491208/214620628-c91082de-2d1f-42eb-aef6-bacb38ab67f1.png)
![image](https://user-images.githubusercontent.com/33491208/214620027-1ea7e4ee-5435-44ae-8fb5-efbd20ccea13.png)

**Comment by NathanLovato** [comment]
Thanks for pointing this out!
