### ISSUE TITLE
Error in Code Example in Lesson 15

### ISSUE THREAD

**Issue by emshuttles** [GDQuest/learn-gdscript#780]
The code in the roll_dice method at the end of the lesson must be missing something. It doesn't make sense, and there's no modulo operator.
![roll_dice](https://user-images.githubusercontent.com/29593197/218335962-f74360a2-fc07-40da-abea-4cdaa05729d5.PNG)

**Comment by NathanLovato** [comment]
It's a text wrapping issue, the modulo is there, it's just clipped outside the code listing on the right. It is linked to issue #99, which we cannot easily fix, it's a limitation of text in Godot 3 in this specific case.

Playing with the font settings in the app can help.

The Godot 4 remake of the app, we're looking to build with native web text, which should not have these kinds of problems.
