### ISSUE TITLE
1/2 is not 0

### ISSUE THREAD

**Issue by Adrian0216** [GDQuest/learn-gdscript#786]
**Issue description:**
there is typo in the sentence. It says 1/2 is equal 0 but 1/2 is remainder 1 and not 0
![Screenshot 2023-02-23 182939](https://user-images.githubusercontent.com/126158920/220881939-e8090426-7fe4-46c3-a2c9-16fa57d413e9.jpg)

**Comment by NathanLovato** [comment]
It's correct, these are whole number divisions. 1 / 2 -> There is 0 times 2 in 1, and 1 remains as a result of the division.
