### ISSUE TITLE
Typo on Lesson 16 last quiz explanation, Vector instead of Vector2

### ISSUE THREAD

**Issue by eh-jogos** [GDQuest/learn-gdscript#792]
**Describe the bug**
After answering the last quiz on lesson 16 we get the following 
![image](https://user-images.githubusercontent.com/13070158/222546568-da6e3f35-2ba1-4693-8766-995612162dba.png)

The second example should be Vector2(50, 0). I think the alternative to choose before this also has the same error.

**To Reproduce**
Steps to reproduce the bug:
Go through lesson 16 up to the last quiz.

**Expected behavior**
Vector2 instead of Vector in the example explanation.

**Information about your device (please complete the following information):**
 - Manjaro Linux using i3

**Comment by NathanLovato** [comment]
Thanks for the report, this should already be fixed
