### ISSUE TITLE
Duplicated word

### ISSUE THREAD

**Issue by ManuMendo** [GDQuest/learn-gdscript#806]
**Issue description:**
The word "that" is duplicated in the second paragraph in section "9. Adding and Substracting". I think it meant to say "that the player".
![image](https://user-images.githubusercontent.com/75464365/225150708-6a160f64-6037-4e56-ba9d-3858a20e63e1.png)

**Comment by NathanLovato** [comment]
Addressed by https://github.com/GDQuest/learn-gdscript/pull/818
