### ISSUE TITLE
Practice - Converting Coordinated From The Screen To The Screen

### ISSUE THREAD

**Issue by AzraiHasanDev** [GDQuest/learn-gdscript#808]
**Describe the bug**
GDQUEST BOY doesen't appear on the right.

**To Reproduce**
Steps to reproduce the bug:
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
Expected GDQUEST BOY to appear on the right.

**Screenshots**
![Screenshot 2023-03-15 160208](https://user-images.githubusercontent.com/25645078/225245011-2266b543-c057-4c25-b058-3e92764601e5.jpg)

**Information about your device (please complete the following information):**
 - Operating System: [Windows]
 - Browser: [Firefox]

**Additional context**
[gdquest-1678867138567.log](https://github.com/GDQuest/learn-gdscript/files/10977304/gdquest-1678867138567.log)

**Comment by NathanLovato** [comment]
On your screenshot, the gdquestboy (the little "game console") is present. What is it that you're missing?

**Comment by NathanLovato** [comment]
Closing as I didn't get an update and can't understand the issue as a result. If you can give me more information, I'll be happy to reopen and look into it!
