### ISSUE TITLE
the free Learn GDScript From Zero

### ISSUE THREAD

**Issue by YNotCodeStudios** [GDQuest/learn-gdscript#810]
The variable 'number' in the while loop example?  Should it be 'while number <' not 'while cell.x <' ?

![Screenshot 2023-03-26 at 7 53 02 AM](https://user-images.githubusercontent.com/128845861/227784251-96e939d7-97a5-4f67-bcd5-bcc154948077.png)

**Comment by NathanLovato** [comment]
The code listing is correct, in a for loop, you name the temporary loop variable however you want.

![image](https://user-images.githubusercontent.com/12694995/236602720-c30c5129-44c3-4539-8c00-ed888e7b34ea.png)
