### ISSUE TITLE
Lesson 20 - Practice 2

### ISSUE THREAD

**Issue by Gigga-Byte** [GDQuest/learn-gdscript#811]
**I'm submitting a...**

- [ ] Bug report.
- [x] Feature request.

## Feature request ##

**Describe the problem you're trying to solve.**
Not telling the user about variables they need inside practices.

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**
I've been forced to use the solution tab to see what variables I need to use, I think people should be told about these variables somewhere else. In the side bar by the documentation would be a good spot./

**Comment by NathanLovato** [comment]
As we've seen in lesson 18 when introducing for loops, in loops, you create a temporary variable and name it however you want

![image](https://user-images.githubusercontent.com/12694995/236602607-1b838b8f-7161-4fe1-9309-44c11cc07a9e.png)

You don't have to use a specific variable name in this practice as a result. We will work on having more gradual exercises in the Godot 4 remake of this app to help students better digest all this info, but it's a brand new project so not happening for this app.
