### ISSUE TITLE
Lesson 7 Practice 2 - Task to create squares but solution are rectangles

### ISSUE THREAD

**Issue by Tabascus** [GDQuest/learn-gdscript#812]
**I'm submitting a...**

- [ x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
Inserting in code as asked however I'm getting errors. 

**What is the expected behavior?**
That I'm correct due to the fact that I'm creating squares as asked rather than rectangles as the solution

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. Enter in code as asked in the course
2. Run the code

![Screenshot 2023-04-05 at 7 32 26 pm](https://user-images.githubusercontent.com/113387955/230049836-3bd0bedc-200d-43b9-a00a-46ae0d28c9f0.png)

**Comment by NathanLovato** [comment]
Could you please share the errors you are getting? With this screenshot we can't assess the problem, and we can't reproduce it here.

**Comment by Tabascus** [comment]
Hiya Nathan, apologies, this was a while back and I think it was focusing more that the Goals indicate to write squares when the code asks to make rectangles. rather than it being draw_square it's draw_rectangle. 

No errors in the code from https://gdquest.github.io/learn-gdscript/staging/#course/lesson-7-member-variables/practice-x0c7DDiz.tres 

Apologies if this caused any grief, was not intended :) Perhaps changing the function to draw_square() might be the best solution.

**Comment by NathanLovato** [comment]
Oh, I see. A square is also a rectangle, just with the same width and height. Hence, the reuse of the same function.

**Comment by Tabascus** [comment]
Understood, I’m really sorry for the mess around. :)

**Comment by NathanLovato** [comment]
No worries, really!
