### ISSUE TITLE
Chapter 19: Typo in explanatory code

### ISSUE THREAD

**Issue by xU77654x** [GDQuest/learn-gdscript#823]
In Chapter 19, there is an incorrect piece of code defining the path to the robot when the turtle has to walk to the robot while avoiding some rocks. This should be an easy fix.

The code is currently listed as:
var path_to_robot = [Vector2(1,0), Vector2(2,0), **Vector2(1)**, Vector2(2, 2), Vector2(3, 2), Vector2(4, 2), Vector2(5, 2)]

The code should instead be:
var path_to_robot = [Vector2(1,0), Vector2(2,0), **Vector2(2, 1)**, Vector2(2, 2), Vector2(3, 2), Vector2(4, 2), Vector2(5, 2)]

**Comment by NathanLovato** [comment]
In the latest version of the app, the code is correct. perhaps what you're experiencing is #99, which we cannot fix unfortunately
