### ISSUE TITLE
Clarify that the methods used are not included in Godot

### ISSUE THREAD

**Issue by winston-yallow** [GDQuest/learn-gdscript#829]
**Issue description:**
In discord there are sometimes people coming from this course asking what `move_forward()`, `turn_right()` and so on were changed to for Godot 4, expecting to find some kind of equivalent. I wonder if the course could make it clearer that these methods are specifically provided for the course and do not exist in stock Godot.

**Comment by NathanLovato** [comment]
Agreed!
