### ISSUE TITLE
Chapter 18 For Loop quiz

### ISSUE THREAD

**Issue by clogan77** [GDQuest/learn-gdscript#833]
Hint 3  says to use (board_size.y - 1) in the range but range already handles the -1 so its not needed.

![image](https://github.com/GDQuest/learn-gdscript/assets/138819338/960b8e9c-98d9-445b-9693-674ee8038b14)

**Comment by NathanLovato** [comment]
If you use range(board_size.y), the character will overshoot the limits of the game grid. Because, if the board has a height of 5 cells, the robot is already on the first cell, and needs to move 4 cells (board height - 1) to reach the last cell.

So, the hint and practice solution are correct.
