### ISSUE TITLE
Lesson 18 breaks cell.y

### ISSUE THREAD

**Issue by MilesFarber** [GDQuest/learn-gdscript#838]
![image](https://github.com/GDQuest/learn-gdscript/assets/24918282/65a29335-14e4-4b91-9243-482929b5366a)

Using Cell.y is more desirable than using Number, because it uses less variables, and if the robot starts from the middle instead of the top, Number will cause it to go outside.

**Comment by NathanLovato** [comment]
Trying to write `for cell.y` is not valid GDScript code, hence the error you're seeing, `"in" expected after identifier`. I'll add the error explanation to the app. Thanks for the report
