### ISSUE TITLE
Redo the inline value display in runnable code examples

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#84]
Two users in #81 reported that this display is confusing:

![image](https://user-images.githubusercontent.com/12694995/147880965-31595aaa-a5fa-4811-9a9d-ee118fc3f511.png)

We could try to improve this by not making the text part of the code.

Instead, I see three options:

1. Make the value appear in a pill upon hovering over the variable name with the mouse. It's not too discoverable though.
2. Make the value appear more clearly in the example window. When changing the slider, for example. Right now, it doesn't really stand out. But that wouldn't make it necessarily super clear the function gets called with this value.
3. Make the value change inside a call to the function. Possibly combined with point 1. That's ideal as it's explicit. Now, our first code examples don't show functions being called due to having to use something like _ready() in GDScript, which we don't introduce.

I'm a bit reluctant to introduce _ready() early on because we can't explain it well (at this stage, it would just be a magical function), but we should consider it if it'll make other aspects of lessons clearer and more precise.

**Comment by Xananax** [comment]
The pill was my intention, but I wanted to get something out before release and without adding too much code complexity.

It doesn't need to show only on hover:

1. The bubble could pop-up on interaction (as well as on hover)
2. Maybe it's even enough to simply highlight the parameter in the same color as the value next to the slider (both in yellow, during usage, then they go back to their normal color). 

We want to establish the notion that this is a variable value, and show it varies. Showing the actual value is less important.

However, now that I read it, I think having an explicit function call is best. I'm also bothered by introducing _`ready()`, but maybe it isn't as bad as we think it is, even for people who never saw code before

**Comment by NathanLovato** [comment]
As we don't have much budget and time to push this right now, I went with the simplest solution possible: displaying on the button. It should already clear the confusion at least

![image](https://user-images.githubusercontent.com/12694995/185783549-fcad0648-818e-4666-a166-9d898bc04730.png)
