### ISSUE TITLE
Can you please integrate Turkish translations, they are ready now

### ISSUE THREAD

**Issue by yilmazdurmaz** [GDQuest/learn-gdscript#841]
**Is your feature request related to a problem? Please describe.**

I don't know how fast you are integrating translations.
So, it is better to ask than wait.

**Describe the solution you'd like**

There might be still typos I missed, but the Turkish translations are complete.
Please integrate them into the application

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by NathanLovato** [comment]
I just integrated them, and launched the build of a new HTML5 release. Thanks much for your work!
