### ISSUE TITLE
Chapter 10 Spanish translation

### ISSUE THREAD

**Issue by Kumangs** [GDQuest/learn-gdscript#842]
In lesson 10 there is a part that is not translated into Spanish.

![gdquest-lesson10-translation-issue](https://github.com/GDQuest/learn-gdscript/assets/12156740/5a4792fd-4fd1-4433-acb1-42da42e86b7a)

**Comment by NathanLovato** [comment]
Thanks for the report. Seems it's a more general issue that the Spanish translations need updates. Closing to merge with #859
