### ISSUE TITLE
Lesson 28: specifying types error in initial assignment values

### ISSUE THREAD

**Issue by theuerc** [GDQuest/learn-gdscript#844]
**Describe the bug**

[] should be Vector(1,1) in the image below, which shows the initial problem setup. It is unsolvable otherwise.

<img width="1320" alt="Screen Shot 2023-07-24 at 3 54 41 PM" src="https://github.com/GDQuest/learn-gdscript/assets/60138157/2770a3ed-7442-4e29-a60d-49cde099f3e6">

**To Reproduce**
Steps to reproduce the bug:
1. Go to ['Lesson-28 Exercise'](https://gdquest.github.io/learn-gdscript/staging/#course/lesson-28-specifying-types/practice-UdOCQiGj.tres)

**Information about your device (please complete the following information):**
 - Operating System: Mac OS
 - Browser: Chrome

**Comment by NathanLovato** [comment]
Closed by #845
