### ISSUE TITLE
lesson 13 if not working correctly

### ISSUE THREAD

**Issue by helloimcheese** [GDQuest/learn-gdscript#848]
**Describe the bug**
so this is the solution:
func heal(amount):
	health += amount
	if health > 80:
		health = 80

but when i write the if health > 80: the text doesnt have two arrows in the start of the line but in the solution there are 2 arrows in the start.i know its hard to understand by text so look at the screenshots.
**To Reproduce**
Steps to reproduce the bug:
1. Go to 'lesson 13' or 'lesson 14'
2. Write 'if health > 80:'
3. there wont be 2 arrows on the start so you cant add codes to the if condition while to solution does it.
4. See error 'expected an intended after 'if' '

**Screenshots**

![Ekran Alıntısı](https://github.com/GDQuest/learn-gdscript/assets/142108595/96dc956a-4307-45ff-be63-56eb3e1bcbb3)

sorry if my text is trash btw,its my first time submitting a new issue

**Comment by helloimcheese** [comment]
i didnt know how to label this so i wrote bug

**Comment by NathanLovato** [comment]
The arrows on the left side are indentation marks. To insert an indentation mark, click before `health = 80` to place the cursor there, and press the Tab key on your keyboard.

Indentation is important in GDScript, like in the Python programming language: the computer uses indentation levels to know what code is part of the "if" block.

The code editor tries to help by inserting indentation marks automatically for you sometimes, but you still need to manage indentations manually (by inserting or removing Tab characters) in many cases.

I hope this helps.
