### ISSUE TITLE
We are making a new course to replace this

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#852]
This post is to inform you all that we are currently working on a new series and technology for you to learn GDScript from zero using Godot 4.

At the time of writing we have not open sourced the technology yet, but we will do so after completing it.

We are making it from scratch to address a number of issues and requests that cannot be fixed with this existing app, because it is a WebGL app and browsers limit what these apps can do.

The new technology will give you access to text search, copy and paste, browser accessibility features like text to speech, and more.

At the time of writing (August 2023) we don't have a precise release date for it, but it will be out by the end of the year.

As we are a busy with this replacement, a new projects, we will not do much maintenance on this existing app anymore. Contributions are still welcome though!

**Comment by ohokusan** [comment]
Thank you for your work! I could help you with design or translation services.

**Comment by MattMx** [comment]
I plan to teach my son Godot and because he is not fluent enough in English to work through this app I would like to provide a translation in Polish. Does it make sense to work on this version or should I wait for the Godot 4 version?

**Comment by NathanLovato** [comment]
@MattMx It still makes sense to work on this in that case, because I don't think we'll have translation support soon on the new app.

**Comment by winne42** [comment]
@NathanLovato thanks, I had the exact same plan as @MattMx , just for German ;-)

**Comment by NathanLovato** [comment]
We've decided to pause the new app temporarily, as this one almost 100% works for Godot 4 (to our surprise! we hadn't thought of it).

Lots of people are asking us to release Godot 4 content faster, so we're gonna prioritize that, launch our new website, and we'll resume work on the new technology later.

And luckily, it appears that despite being in Godot 3, this series remains valid in Godot 4. I'll just make a couple of tweaks this weekend so it works as well as possible for people now learning Godot 4.
