### ISSUE TITLE
Lesson 15 "Modulo" missing the % after randi()

### ISSUE THREAD

**Issue by avantgardian** [GDQuest/learn-gdscript#854]
**Issue description:**
In the "Calculating a random number within a range", in the code example, we are missing the Modulo sign % after the `randi()` function, so the statement doesn't make sense as is.

<img width="654" alt="SCR-20230906-sruh" src="https://github.com/GDQuest/learn-gdscript/assets/3671967/6baaeade-2966-431a-b766-e53a3c11ff99">

**Comment by avantgardian** [comment]
Update here: after leaving to Lesson 14 and coming back to Lesson 15 the "%" appeared. My friend was also able to reproduce it on his machine once, same behaviour.

**Comment by Elbod** [comment]
Can confirm, it sometimes happens, not quite sure why 

![image](https://github.com/GDQuest/learn-gdscript/assets/26551194/e4b29a22-848a-4b9b-b417-2869f2a17f9e)
