### ISSUE TITLE
Missing spanish paragraphs on spanish version

### ISSUE THREAD

**Issue by Cazadragones** [GDQuest/learn-gdscript#859]
The Title its selfexplaining... there are lots of paragraphs in spanish version that remains in english... I'm using Opera browser

**Comment by NathanLovato** [comment]
Could you please tell me in which lessons exactly? Are you using the app from here, or from itch.io? The translations seemed complete, see here: https://github.com/GDQuest/learn-gdscript-translations/

An issue could be, when trying to apply translations, that there's a slight mismatch between Godot and the translation text. Unfortunately, I won't have time to fix this, but if anyone is willing to look into it and contribute a fix, I'll gladly take it.

**Comment by Cazadragones** [comment]
im doing it there: https://gdquest.github.io/learn-gdscript/#course/lesson-17-while-loops/lesson.tres and i started to see english paragraphs time to time since around the 3rd or 4th lesson... i'm actually at lesson 17th...

**Comment by Cazadragones** [comment]
in fact i tried to contacts you yesterday on private twitter XD

**Comment by NathanLovato** [comment]
Just checked and answer the message on Twitter! I see, so the thing is the translation strings appear to be OK, you can see the data file here: https://github.com/GDQuest/learn-gdscript/blob/main/i18n/es/lesson-17-while-loops.po

The French, Turkish, Brazilian Portuguese, and Italian translations are working... I suspect the Spanish translation strings are not 100% up to date.

**Comment by Cazadragones** [comment]
I see... that's bad... one could think spanish would be one of the firsts to be completed because we are a lot of spanish-speakers around the world... Its bad to see spanish being uncompleted against turkish or portuguese... :( 

well thanks for your responses... i could do it myself, but i really have another things to focus... :(
