### ISSUE TITLE
loop discribtion in loop  lesson bug

### ISSUE THREAD

**Issue by Paingphyothu** [GDQuest/learn-gdscript#870]
**Describe the bug**

The run function is not working

**To Reproduce**
Steps to reproduce the bug:
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**
If applicable, drag and drop screenshots here to help explain your problem.

**Information about your device (please complete the following information):**
 - Operating System: [e.g. iOS, Windows]
 - Browser: [e.g. Chrome, Safari]

**Additional context**

**Comment by NathanLovato** [comment]
Could you please explain what is the issue?  You only filled a title, so I don't know what you meant to point out.

**Comment by NathanLovato** [comment]
No answer from OP, closing until we get more details
