### ISSUE TITLE
Lesson 8: Line Text

### ISSUE THREAD

**Issue by Dayhalk** [GDQuest/learn-gdscript#871]
**Issue description:**
On Lesson 8, one of the explanations says that Line 1 holds Health and Line 2 Holds Text. In the example, it shows as Line 2 having the Health value and Line 3 having the Text.

I know this may be nitpicking, but I didn't know if this would confuse beginners.

![image](https://github.com/GDQuest/learn-gdscript/assets/54253172/214f8f50-e448-457c-9481-575e3bcf6a26)

**Comment by NathanLovato** [comment]
Thanks for the report, this is already fixed on my end and will be part of this morning's release.
