### ISSUE TITLE
Lesson 16, Practice 1: Crash

### ISSUE THREAD

**Issue by TheeOBP** [GDQuest/learn-gdscript#873]
**Describe the bug**
Writing Certain Incorrect Code Causes A Crash

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'Lesson 16'
2. Click on 'Practice: Increasing Scale Using Vectors'
3. Type 'scale.Vector2(0.2, 0.2)'
4. Click 'Run'
5. Crash

**Expected behavior**
Program Crashes

**Information about your device (please complete the following information):**
 - Operating System: Windows 10

**Additional context**
I Have Tested This 3 Times To Help Make Sure It Wasn't A Fluke.

**Comment by NathanLovato** [comment]
Could you please try downloading the update I just pushed to itch.io? The Windows version there was over 1 year old: https://gdquest.itch.io/learn-godot-gdscript

**Comment by TheeOBP** [comment]
Downloading from the link fixed the issue. :)

**Comment by NathanLovato** [comment]
Great to hear, thanks!
