### ISSUE TITLE
Spanish Traduction Issue

### ISSUE THREAD

**Issue by deltaGreed** [GDQuest/learn-gdscript#874]
Chapter 7 ; paragraph 7, right down of **In games, the Y axis is positive going down**  it's in english.
![imagen_2023-10-06_143633206](https://github.com/GDQuest/learn-gdscript/assets/147190830/16c105a4-8a4f-4160-9353-3dcf2e856087)

**Comment by NathanLovato** [comment]
If you find other instances of this, could you please let me know? I just checked and the translation exists, so it seems like an issue with the translation system.

**Comment by yilmazdurmaz** [comment]
Same paragraphs in Turkish too.

Having button in static positions helps to check before submitting if the problem exists in other languages too. Recently, I have started my long-delayed proof reading. I may help in the code later if I can keep up my pace ;)
