### ISSUE TITLE
Level 20 missing a quotation mark. (very nitpicky)

### ISSUE THREAD

**Issue by Secay25** [GDQuest/learn-gdscript#876]
Simply missing the first quotation mark in the section "What are strings".
<img width="758" alt="image" src="https://github.com/GDQuest/learn-gdscript/assets/129698157/a691fa6e-ee8c-41cc-81c1-9edb0212cbab">

Yeah, I know very nitpicky. It does do it correctly in the preview below, but issueing this just in case.

**Comment by Secay25** [comment]
Found another one like this in level 26.
<img width="708" alt="image" src="https://github.com/GDQuest/learn-gdscript/assets/129698157/a8885442-a029-4cab-b4a4-113aa9e0b3c2">
The first quotation mark of the second 100 is missing.

**Comment by ganimtron-10** [comment]
Hey @Secay25 Thanks for pointing this out!

@NathanLovato while checking this issue I found that whenever we use ```[code]\"{anything}\"[/code]``` the first quotation mark is not rendered and this is used at lot of places.

I am confused whether the approach I am thinking is a good fix or not which is to take the quotation mark outside the code block at every occurance ie. something like this ```\"[code]{anything}[/code]\"```
or is there a way to fix something while rendering the `[code]` block?

Thanks in Advance!

**Comment by NathanLovato** [comment]
This and other errors are due to the color highlighter code (file `autoload/TextUtils.gd`), I've just worked on fixing this and adding improved color highlighting for strings
