### ISSUE TITLE
Keyboard Not Showing 

### ISSUE THREAD

**Issue by I-am-Hero002** [GDQuest/learn-gdscript#887]
I am using my android tablet and when I click on the code editor the keyboard is not showing than how I suppose to write or edit the code. Please help me🙏🙏🙏🙏🙏

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'Any Lesson'
2. Click on 'Cide editor'
3. See error

**Expected behavior**
The keyboard suppose to pop up so I can edit or write the code

 - Operating System: android 
 - Browser: Chrome

**Comment by NathanLovato** [comment]
The app doesn't support mobile, it's designed for desktop use only. If you want to use it on a tablet, you'll need a physical keyboard. See #765, this is kind of a duplicate as it's about requesting the same feature. So I'm closing this issue to have a single ticket about adding virtual keyboard support on mobile.
