### ISSUE TITLE
Warn students when they are about to leave the practice screen if they changed code

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/learn-gdscript#9]
Students can back out of the practice screen using either the back button or the outliner/index button. We don’t warn about leaving whatsoever, but students may have some unfinished code there and the click on a button might have been a mistake.

It stands to reason, we should warn users before they navigate away and lose any progress, at least if there was some progress (i.e. the code in the code editor is different from the default slice.

**Comment by mathmods** [comment]
I'm currently working on this.
It should be a simple use of a confirmation pop up whenever the functions related to switching sites are called while the current tab is an unfinished edited practice.

**Comment by pycbouh** [comment]
> I'm going to use the _code_editor_is_dirty bool

Correct, I'm pretty sure it was exposed specifically for this issue.

**Comment by NathanLovato** [comment]
Thanks for contributing once more!
