### ISSUE TITLE
Full Screen button should work in both ways, but you cant minimize the app 

### ISSUE THREAD

**Issue by Nskubix** [GDQuest/learn-gdscript#901]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug:
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**
If applicable, drag and drop screenshots here to help explain your problem.

**Information about your device (please complete the following information):**
 - Operating System: [e.g. iOS, Windows]
 - Browser: [e.g. Chrome, Safari]

**Additional context**

**Comment by NathanLovato** [comment]
Could you please explain the issue in detail, filling the form ? Without context, we can't understand what the issue is about.
