### ISSUE TITLE
Completing a practice with wrong code.

### ISSUE THREAD

**Issue by Mirrekatten** [GDQuest/learn-gdscript#920]
**Describe the bug**
I did a practice in "20. String, 2. using an array of strings to play a combo"
and messed up the code but still completed the task.

**To Reproduce**
Steps to reproduce the bug:
1. Go to '20. String, 2. using an array of strings to play a combo' practice.
2. Write code.
3. func run():
	combo = ["jab", "jab", "uppercut"]
	for action in combo:
		play_animation("")
4. See completion.

**Expected behavior**
Thought it would fail.

**Information about your device (please complete the following information):**
 - Operating System: [Windows 10]
 - Browser: [Chrome]

**Comment by NathanLovato** [comment]
Thanks! It was solved by Wolfy7 in the contribution linked above
