### ISSUE TITLE
On firefox scale window work incorect

### ISSUE THREAD

**Issue by allkhor** [GDQuest/learn-gdscript#93]
**Describe the bug**
On Firefox scale window work incorrect. Regression from #70

**To Reproduce**
Steps to reproduce the bug:
1. Open site https://gdquest.github.io/learn-gdscript/ in Firefox.
2. Change Firefox window size.
3. Look how windows it's scaled.

**Screenshots**
![](https://user-images.githubusercontent.com/1049442/147973983-cda8f707-96f3-43c0-b5a5-e6add0ad7fa5.png)

**Information about your device (please complete the following information):**
 - Xubuntu 16.04.7 LTS
 - Firefox 88.0.1

**Comment by pycbouh** [comment]
Do you experience the same behavior in other browsers on that system? Pretty sure @Xananax is using Firefox and he tested that the scaling worked correctly on Linux.

Also, which size is your window there?

**Comment by NathanLovato** [comment]
I can confirm the issue, this happens especially when using Super RMB to scale the window interactively. It's something I don't do much with browsers so I didn't catch it when reviewing the PR. I'll test and merge the fix PR.

**Comment by NathanLovato** [comment]
@Xananax it seems the flex display with an absolute position at (0,0,0,0) on firefox forces the image to stretch to the browser's edges.

**Comment by allkhor** [comment]
This not happen on Google Chrome browser on the same system. 
You can reproduce with Firefox Response Design Mode(Ctrl+Shift+M).
![resize_bug](https://user-images.githubusercontent.com/1049442/148024170-685afdbe-71bf-4d3c-8eef-593b26942032.gif)

**Comment by NathanLovato** [comment]
Yes, it's specific to Firefox.

**Comment by Th-eo** [comment]
Happens to me as well, just to provide some info. If you F11 (Fullscreen) it is alright. Surprisingly enough, this is recent. I played the Demo on Firefox a few days ago and I never noticed this.

**Comment by NathanLovato** [comment]
This is due to the new resizing code Xananax wrote to make the app scale much better on many devices. The thing is, browsers render the same HTML/CSS differently (which is always a pain). Despite testing, we didn't catch this issue in FF and just need to find a way to make scaling work there.

**Comment by pycbouh** [comment]
Should be good now, but it wasn't deployed yet, so no changes on the live website yet!
