### ISSUE TITLE
Dyslexia accessible font option

### ISSUE THREAD

**Issue by S-Davahan** [GDQuest/learn-gdscript#931]
It would be really helpful if there was a font selection option that included the opendyslexic font for accessibility

**Comment by Wolfy7** [comment]
@NathanLovato which textes should be affected when a different font is selected ?

Could a solution be to change all `font_data` of all `font_resource` to the new/selected font? 

More or less similiar to `func scale_all_font_sizes(size_scale: int, and_save: bool = true) -> void:`

And should there defined list (dropdown) with fonts or should this dynamic list generated by parsing all fonts (*.ttf, *.otf) in `ui\theme\fonts`
