### ISSUE TITLE
Hey. I try to do the course on my ipad in my favorite cafe. But i can change the code, because i can’t find the keyboard option. When i click on the intended area where i want to delete something or type, the keyboard option doesn’t pop up. What am i missing? Or isn’t it available on ipad?

### ISSUE THREAD

**Issue by muckxxx** [GDQuest/learn-gdscript#946]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug:
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**
If applicable, drag and drop screenshots here to help explain your problem.

**Information about your device (please complete the following information):**
 - Operating System: [e.g. iOS, Windows]
 - Browser: [e.g. Chrome, Safari]

**Additional context**

**Comment by Muck22** [comment]
![IMG_2114](https://github.com/GDQuest/learn-gdscript/assets/167675234/750dd340-ac01-444c-8275-98c45e1f44c2)

**Comment by NathanLovato** [comment]
The touch keyboard on mobile devices isn't supported. You can learn a little more here: #847

Closing as this is a duplicate issue.

**Comment by muckxxx** [comment]
Okay. That’s a shame. But i’m looking forward to the one that is supported for mobiles. 
Thanks for the quick response.

**Comment by NathanLovato** [comment]
My pleasure!
