### ISSUE TITLE
Cut, Copy and Paste in the internal editor uses Control-X etc. instead of Command-X on MacOS Computers.

### ISSUE THREAD

**Issue by BjoeBrunn** [GDQuest/learn-gdscript#956]
On MacOS the key mappings for cut, copy and paste use Control- instead of Command-, which is normally standard on MacOS machines. Maybe you can implement an additional key mapping for MacOS computers to avoid confusion?

**Comment by NathanLovato** [comment]
It's not something we can easily solve. See issue #711 for more information. Closing as this is a duplicate
