### ISSUE TITLE
error leson 16

### ISSUE THREAD

**Issue by thijmenb1** [GDQuest/learn-gdscript#961]
**Describe the bug**
i got the error "oh no! The script has an error, but the script verifier did not catch it" on leson 16 and it sad i need to report it

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'leson 16'
2. Click on 'practice one'
3. type in 'func move_to_bottom():
	while cell.x < board_size.x - 1:
		cell.x += 1
	while cell.y < board_size.y -1:
		cell.y += 1'

**Expected behavior**
i expected to pess the level or ge a error that told me how to fix it

**Screenshots**
![image](https://github.com/GDQuest/learn-gdscript/assets/145684235/9a74014d-d0de-41a9-9d32-16918a86c974)

**Information about your device (please complete the following information):**
 - Operating System: [Windows]
 - Browser: [duckduckgo]

**Additional context**

**Comment by NathanLovato** [comment]
Thank you very much for taking the time to tackle issues! Your contributions are much appreciated. I'm sorry it's taking me so long to review and merge everything; after being sick I have a lot to catch up on.
