### ISSUE TITLE
Missing ")" sybmol in the example code can confuse the fresh heads learning it

### ISSUE THREAD

**Issue by MindInterceptor** [GDQuest/learn-gdscript#963]
Hi! 

It looks like the Vector2(0.2, 0.2) just went beyond the field for code missing the ")" symbol. It can be obvious for someone and it was for me, but it certainly might raise the questions when all of a sudden you see not closed () working just fine. 

![image](https://github.com/GDQuest/learn-gdscript/assets/173493554/8113d144-0712-4faf-a7ea-f332baa23211)

Let me know if it's just me who missed something before that. I am happy to learn more!

**Comment by NathanLovato** [comment]
It's a text wrapping issue that we can't easily solve with the technology we used to make this app initially. See issue #99. The parenthesis is there but it's not wrapping onto the following line as it should.
