### ISSUE TITLE
20. Strings Lesson 2 Issue with different variable names.

### ISSUE THREAD

**Issue by 228Q922** [GDQuest/learn-gdscript#972]
All animations play out in the correct order. The error statement given was telling me my animations aren't playing out supposedly due to me not calling the function. Code and log below:

func run():
	combo = ["jab", "jab", "uppercut"]
	for number in combo:
		play_animation (number)

[gdquest-1722187700109.log](https://github.com/user-attachments/files/16404679/gdquest-1722187700109.log)

**Comment by NathanLovato** [comment]
I added a new function to preprocess code and ignore whitespace in tests. Ideally this could/would be used everywhere automatically, it's something we use now in [GDPractice](https://github.com/GDQuest/GDPractice) to make checking code syntax a bit more reliable, but well a change like this would need careful testing and perhaps some refactoring. So for now it's only used here and can be used in specific practices when people have trouble.
