### ISSUE TITLE
Lesson 17 misspelled word

### ISSUE THREAD

**Issue by Dreyseth** [GDQuest/learn-gdscript#988]
Lesson 17, under How for loops work:
Text reads as "We'll explain arrays more throughly.." 
Should be spelled as "thoroughly"

**Comment by Wolfy7** [comment]
If you agree I would fix this "typo" in `course\lesson-18-for-loops\lesson.tres`

> We'll explain arrays more throughly in the next lesson

**Comment by n9jlo** [comment]
Can we close this issue?
