### ISSUE TITLE
Lesson 3

### ISSUE THREAD

**Issue by rampa2510** [GDQuest/learn-gdscript#990]
In the 2nd question practice title **Make The Robot Upright**. The hints are not ordered correctly. Here is the image for it
<img width="512" alt="image" src="https://github.com/user-attachments/assets/9acd7f3a-965a-4fe7-b817-bdd253525990">
I think Hint 3 should be before the current Hint 2. Since Hint directly gives the solution but Hint 3 does not.

**Comment by rampa2510** [comment]
Let me know if I can fix this? I would like to contribute as well

**Comment by NathanLovato** [comment]
Absolutely, contributions like these are most welcome! Let me know if you need anything to locate and correct this. I would recommend directly editing the .tres file for this lesson and manually swapping the hints.
