### ISSUE TITLE
Lesson 15: Excersise 1: Increasing scale using Vectors

### ISSUE THREAD

**Issue by vhalragnarok-ffxiv** [GDQuest/learn-gdscript#992]
![Screenshot_20240922_162920](https://github.com/user-attachments/assets/6b79f993-aa2c-454c-9649-282263a3bd26)

Errors out. Scale apparently is not a vector?

![Screenshot_20240922_162944](https://github.com/user-attachments/assets/80e36987-872c-44af-9d81-7c1b31ee202b)

![Screenshot_20240922_163040](https://github.com/user-attachments/assets/fccbb178-4aac-4e02-bb78-369c781d5886)
So the vector does not work, but doing what the lesson says not to do specifically works. 

This bug happens in the Desktop Linux version specifically (Version as of 21 September 2024)

**Comment by NathanLovato** [comment]
You have a syntax error in your first screenshot, decimal numbers need a . as a decimal separator but you use a comma instead.

Just tested, using a Vector2 value works in this practice:

![image](https://github.com/user-attachments/assets/4bc2edf5-33c9-4526-8ed1-5d244dbdafac)
