### ISSUE TITLE
Code cutted 

### ISSUE THREAD

**Issue by Lucatcs** [GDQuest/learn-gdscript#998]
**Issue Description:**
Sometimes longer lines of code are cut, so for a beginner like me is unclear if there's a new line (tab) or not.
Eventually, I figured out that if there's a ">I" it means a new line otherwise is just a line of code split in two due to lack of space, since there's a lot of space in the UI I suggest formatting the code window larger according to the code.

**Comment by NathanLovato** [comment]
Yes, unfortunately, it's a limitation of Godot 3. This is the same issue as #99, so closing this one.
